"""REST API view for Roomba+ -- mission history endpoint.

GET /api/roomba_plus/{entry_id}/mission_history

Query parameters:
  days:   int  (1-90, default 28)   -- lookback window for day-summary format
  format: str  ("summary" | "records", default "summary")
            summary  -- day-aggregated DaySummary array (v0.1-beta card format,
                        always available, sourced from local MissionStore)
            records  -- per-mission array (v1.0 card format, sourced from cloud
                        raw_records when available, falls back to local
                        MissionStore records for robots without cloud credentials.
                        v2.10.2 -- when cloud IS the source, any local record
                        that never got a cloud merge match is unioned in too,
                        so this stays consistent with format=summary's
                        always-local total. See RECORDS-UNION.)

v2.1 changes:
  F4a -- zone names injected into cloud records (120 s timestamp tolerance)
  F7o -- startup race guard (503), coordinator failure (503), unknown format (400)

Registered once per HA instance (sentinel guard in __init__.py).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import datetime
import logging
from typing import TYPE_CHECKING, Any

from aiohttp import web
from homeassistant.components.http import HomeAssistantView
from homeassistant.core import HomeAssistant
from homeassistant.util import dt as dt_util

from .const import DOMAIN, SQFT_TO_M2

if TYPE_CHECKING:
    from .models import RoombaData

_LOGGER = logging.getLogger(__name__)

# F7o -- valid format values; unknown values return 400
_VALID_FORMATS = {"summary", "records", "hazards", "export", "zone_coverage_health"}


def _build_local_zones_index(mission_store_records: list[dict]) -> dict[int, list[str]]:
    """Build a ts -> zone-names index from local MissionStore records.

    F4a -- used to inject zone names into cloud records which carry zones=[].
    Keys are integer Unix timestamps of ended_at. Tolerance matching is done
    at the call site (120 s window).
    """
    index: dict[int, list[str]] = {}
    for r in mission_store_records:
        ended_str = r.get("ended_at", "")
        zones = r.get("zones") or []
        if not ended_str or not zones:
            continue
        try:
            ended_dt = datetime.datetime.fromisoformat(ended_str)
        except (ValueError, TypeError):
            continue
        if ended_dt.tzinfo is None:
            ended_dt = ended_dt.replace(tzinfo=datetime.timezone.utc)
        index[int(ended_dt.timestamp())] = list(zones)
    return index


def _inject_zones(
    record: dict[str, Any],
    local_zones_index: dict[int, list[str]],
    tolerance_sec: int = 120,
) -> dict[str, Any]:
    """Return record with zones populated from local MissionStore when available.

    F4a -- matches on the cloud record's ended_at ISO string against the
    local ended_at index within tolerance_sec.  If a match is found and the
    local record has zone names, they replace the empty zones list.
    """
    end_ts_str = record.get("ended_at")
    if not end_ts_str or not local_zones_index:
        return record

    try:
        end_dt = datetime.datetime.fromisoformat(end_ts_str)
        if end_dt.tzinfo is None:
            end_dt = end_dt.replace(tzinfo=datetime.timezone.utc)
        end_ts_int = int(end_dt.timestamp())
    except (ValueError, TypeError):
        return record

    best_ts = min(local_zones_index, key=lambda t: abs(t - end_ts_int), default=None)
    if best_ts is not None and abs(best_ts - end_ts_int) <= tolerance_sec:
        zones = local_zones_index[best_ts]
        if zones:
            return {**record, "zones": zones}
    return record


def _safe_int(value: Any) -> int | None:
    """v3.2.1 — int-or-null for unified-record fields.

    nMssn arrives as int from cloud_coordinator's type-narrowing, but the
    import endpoint and pre-v3.2.0 stores may hold strings or garbage —
    the converters must never raise on a single bad record.
    """
    try:
        return int(value) if value is not None else None
    except (TypeError, ValueError):
        return None


def _cloud_record_to_unified(record: dict[str, Any]) -> dict[str, Any]:
    """Convert a raw cloud /missionhistory record to the unified per-mission shape."""
    start_ts = record.get("startTime")
    end_ts   = record.get("timestamp")

    started_at = (
        datetime.datetime.fromtimestamp(int(start_ts), tz=datetime.timezone.utc).isoformat()
        if start_ts else None
    )
    ended_at = (
        datetime.datetime.fromtimestamp(int(end_ts), tz=datetime.timezone.utc).isoformat()
        if end_ts else None
    )

    duration_min = int(record.get("durationM") or record.get("doneM") or 0)
    run_min      = record.get("runM")
    pause_id     = record.get("pauseId")
    try:
        pause_id_int = int(pause_id) if pause_id is not None else 0
    except (TypeError, ValueError):
        pause_id_int = 0
    error_code = pause_id_int if pause_id_int > 0 else None

    return {
        "id":           f"c_{start_ts}" if start_ts else f"c_{end_ts}",
        "started_at":   started_at,
        "ended_at":     ended_at,
        "duration_min": duration_min,
        "run_min":      int(run_min) if run_min is not None else None,
        "area_sqft":    record.get("sqft"),
        "result":       record.get("classified_result", "unknown"),
        "initiator":    record.get("initiator", "none"),
        "zones":        [],   # F4a: populated by _inject_zones() below
        "error_code":   error_code,
        "recharges":    record.get("chrgs"),
        "evacuations":  record.get("evacs"),
        "dirt_events":  record.get("dirt"),
        "wifi_signal":  record.get("wlBars"),
        "source":       "cloud",
        # v2.3.0 — from CR4 timeline merge; alignment_confidence injected in get()
        "room_coverage":        record.get("room_coverage"),
        "alignment_confidence": None,
        # v3.2.1 — lifetime mission counter, the key of MissionPathView
        # (/mission/{n_mssn}/path).  Unblocks card F4 (path replay): the
        # card needs it per-row to build the replay request.  Every raw
        # cloud record carries nMssn (see cloud_coordinator.py).
        "n_mssn":       _safe_int(record.get("nMssn")),
    }


def _cloud_record_to_explain_input(record: dict[str, Any]) -> dict[str, Any]:
    """v3.3.1 EXPLAIN-CLOUD — convert a raw cloud /missionhistory record
    to the minimal internal shape MissionStore.anomaly_reason()/
    explain_mission() expect (duration_min, area_sqft, dirt, error_code).

    NOT the same as _cloud_record_to_unified() (the REST-facing
    format=records shape) — that one uses dirt_events (not dirt) and
    carries no recharge_min/npicks_delta at all. This converter targets
    explain_mission()'s field names directly instead of adding a second
    translation hop through the REST shape.

    recharge_min and npicks_delta are deliberately absent: both are
    local-only telemetry (mid-mission recharge tracking, bin-lift pick
    count) that a pure cloud-only record never carries. anomaly_reason()
    already treats recharge_min as optional (skips the excessive_recharge
    check when absent) and explain_mission() defaults npicks_delta to 0
    (robot_lifted reads as False) — an honest "unknown" rather than a
    fabricated "no", same documented-gap class as F22's stuck_count 3-7
    null window.
    """
    start_ts = record.get("startTime")
    end_ts   = record.get("timestamp")
    pause_id = record.get("pauseId")
    try:
        pause_id_int = int(pause_id) if pause_id is not None else 0
    except (TypeError, ValueError):
        pause_id_int = 0
    return {
        "id":           f"c_{start_ts}" if start_ts else f"c_{end_ts}",
        "duration_min": int(record.get("durationM") or record.get("doneM") or 0),
        "area_sqft":    record.get("sqft"),
        "dirt":         record.get("dirt"),
        "error_code":   pause_id_int if pause_id_int > 0 else None,
    }


def _resolve_cloud_explain_record(
    data: "RoombaData", mission_id: str
) -> dict[str, Any] | None:
    """v3.3.1 EXPLAIN-CLOUD — resolve a synthetic "c_{ts}" id (minted by
    _cloud_record_to_unified() for cloud-only mission rows that never
    made it into MissionStore._records) against the cloud coordinator's
    raw /missionhistory cache, so cloud-source rows get Explain support
    too. Mirrors the same startTime-then-timestamp precedence
    _cloud_record_to_unified() uses when minting the id, so the reverse
    lookup matches the same record it was minted from.

    Returns None when unresolvable (no cloud coordinator, malformed id,
    or no matching raw record — e.g. the cloud history window has since
    rolled past that mission) — caller translates that into a 404, same
    as any other unresolvable mission_id.
    """
    if not mission_id.startswith("c_") or data.cloud_coordinator is None:
        return None
    try:
        target_ts = int(mission_id[len("c_"):])
    except ValueError:
        return None
    for raw in data.cloud_coordinator.raw_records:
        start_ts = raw.get("startTime")
        end_ts   = raw.get("timestamp")
        candidate_ts = start_ts if start_ts else end_ts
        try:
            if candidate_ts is not None and int(candidate_ts) == target_ts:
                return _cloud_record_to_explain_input(raw)
        except (TypeError, ValueError):
            continue
    return None


def _resolve_cloud_mission_map_record(
    data: "RoombaData", mission_id: str
) -> dict[str, Any] | None:
    """MISSION-MAP-CLOUD-ROWS — resolve a synthetic "c_{ts}" id (minted by
    _cloud_record_to_unified() for cloud-only mission rows that never made
    it into MissionStore._records) against the cloud coordinator's raw
    /missionhistory cache, so cloud-source rows get Mission Map support
    too. Mirrors _resolve_cloud_explain_record()'s same startTime-then-
    timestamp precedence, so the reverse lookup matches the same record
    the id was minted from — this was the same gap class EXPLAIN-CLOUD
    (v3.3.1) fixed for /explain, never carried over to /mission-map.

    Returns the minimal shape async_fetch_mission_map() actually reads
    (id, pmaps_info, nMssn) — not the full unified shape, same rationale
    as _cloud_record_to_explain_input() targeting its consumer directly
    instead of adding a translation hop through the REST shape.

    Returns None when unresolvable (no cloud coordinator, malformed id, or
    no matching raw record) — caller translates that into a 404, same as
    any other unresolvable record_id. A resolved record with no
    pmaps_info (EPHEMERAL tier, or never merged) is NOT this function's
    concern — that 404s correctly inside async_fetch_mission_map() itself,
    same as any local record in that state.
    """
    if not mission_id.startswith("c_") or data.cloud_coordinator is None:
        return None
    try:
        target_ts = int(mission_id[len("c_"):])
    except ValueError:
        return None
    for raw in data.cloud_coordinator.raw_records:
        start_ts = raw.get("startTime")
        end_ts   = raw.get("timestamp")
        candidate_ts = start_ts if start_ts else end_ts
        try:
            if candidate_ts is not None and int(candidate_ts) == target_ts:
                return {
                    "id":         mission_id,
                    "pmaps_info": raw.get("pmaps_info"),
                    "nMssn":      raw.get("nMssn"),
                }
        except (TypeError, ValueError):
            continue
    return None


def _local_record_to_unified(record: dict[str, Any]) -> dict[str, Any]:
    """Convert a local MissionStore record to the unified per-mission shape.

    After v2.1.3 CR1/CR2: dirt_events, wifi_signal, and evacuations are
    populated when the record has been enriched by backfill_from_cloud()
    (v2.9.0 — now called on every cloud refresh, not just at HA startup).
    recharges stays None (no local accumulator).
    source remains "local" — reflects origin, not field provenance.
    """
    return {
        "id":           record.get("id", ""),
        "started_at":   record.get("started_at"),
        "ended_at":     record.get("ended_at"),
        "duration_min": record.get("duration_min"),
        "run_min":      None,                        # local source never has runM
        "area_sqft":    record.get("area_sqft"),
        "result":       record.get("result", "unknown"),
        "initiator":    record.get("initiator", "none"),
        "zones":        record.get("zones", []),
        "error_code":   record.get("error_code"),
        "recharges":    None,                        # no local accumulator
        "evacuations":  record.get("evacs"),         # from CR1 merge
        "dirt_events":  record.get("dirt"),          # from CR1 merge
        "wifi_signal":  record.get("wlBars"),        # from CR1 merge
        "source":       "local",
        # v2.3.0 — from CR4 timeline merge; alignment_confidence always null for local
        "room_coverage":        record.get("room_coverage"),
        "alignment_confidence": None,
        # v3.2.1 — card F4 (path replay), see _cloud_record_to_unified.
        # Local records never get nMssn at creation (callbacks.py); it
        # arrives via backfill_from_cloud() (_CLOUD_MERGE_SCALAR) — null
        # until enriched, which the card treats as "replay unavailable".
        "n_mssn":       _safe_int(record.get("nMssn")),
    }


def _local_record_has_cloud_merge_signal(record: dict[str, Any]) -> bool:
    """True if this local MissionStore record was ever successfully
    matched against a cloud record by backfill_from_cloud() or
    merge_latest_from_cloud() — i.e. at least one cloud-only analytics
    field landed on it.

    v2.10.2 (RECORDS-UNION) — same heuristic cloud_coordinator.py's CR3
    fallback already uses to identify enriched local records, inverted
    here to find records that NEVER matched any cloud entry. A genuine
    mismatch on one field while the others stayed null is not expected
    in practice (all three are written together by the same merge
    call), so this is a reliable proxy for "cloud never knew about
    this mission" without needing new matching logic.
    """
    return any(record.get(f) is not None for f in ("dirt", "chrgM", "wlBars"))


class MissionHistoryView(HomeAssistantView):
    """GET /api/roomba_plus/{entry_id}/mission_history"""

    url = "/api/roomba_plus/{entry_id}/mission_history"
    name = "api:roomba_plus:mission_history"
    requires_auth = True

    async def get(self, request: web.Request, entry_id: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entry = hass.config_entries.async_get_entry(entry_id)
        if entry is None or entry.domain != DOMAIN:
            return self.json_message("Entry not found", status_code=404)

        # F7o -- startup race guard: runtime_data may not be ready immediately
        # after HA start if a request arrives before setup completes.
        if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
            return self.json_message("Integration initialising", status_code=503)

        data: RoombaData = entry.runtime_data

        fmt = request.query.get("format", "summary").strip().lower()

        # F7o -- reject unknown format values with a clear 400
        if fmt not in _VALID_FORMATS:
            return self.json_message(
                f"Unknown format '{fmt}'. Valid values: {', '.join(sorted(_VALID_FORMATS))}",
                status_code=400,
            )

        # -- format=summary (default, backward compatible) --------------------
        if fmt == "summary":
            if data.mission_store is None:
                return self.json([], status_code=200)
            try:
                days = int(request.query.get("days", 28))
                days = max(1, min(days, 90))
            except (ValueError, TypeError):
                days = 28

            by_day = data.mission_store.query_by_day(days)
            # F12b — P4: per-day dirt density now cached on coordinator after each
            # cloud fetch; read directly instead of re-iterating records here.
            _p30d_baseline: float | None = None
            _daily_density: dict[str, float] = {}
            if data.has_cloud and data.cloud_coordinator is not None:
                _daily_density = data.cloud_coordinator.daily_dirt_density
                # 30-day baseline: median of all cached per-day medians
                all_densities = list(_daily_density.values())
                if len(all_densities) >= 5:
                    import statistics as _stat
                    _p30d_baseline = _stat.median(all_densities)

            # L5: per-room relative dirtiness from RobotProfileStore
            _room_dirt_relative: dict[str, float] | None = None
            _rps = getattr(data, "robot_profile_store", None)
            if _rps is not None:
                rd = _rps.room_dirt_relative()
                if rd:
                    _room_dirt_relative = rd

            result = [
                {
                    "date":               summary.date.isoformat(),
                    "total":              summary.total,
                    "completed":          summary.completed,
                    "stuck":              summary.stuck,
                    "area_sqft":          summary.area_sqft,
                    "result":             summary.result,
                    # F12b — dirt analytics read from coordinator cache
                    "dirt_density":       _daily_density.get(summary.date.isoformat()),
                    "relative_to_baseline": (
                        round(_daily_density[summary.date.isoformat()] / _p30d_baseline, 3)
                        if summary.date.isoformat() in _daily_density and _p30d_baseline
                        else None
                    ),
                    # L5 (v2.6.0) — per-room dirtiness index (once per day, not per-summary)
                    "room_dirt_index": _room_dirt_relative,
                }
                for summary in sorted(by_day.values(), key=lambda s: s.date)
            ]
            return self.json(result)

        # -- format=zone_coverage_health ---------------------------------------
        # v3.2.0 COVERAGE-FREQ — per-room self-calibrated cleaning-cadence
        # health. A distinct format value rather than a field bolted onto
        # format=summary's response: that endpoint returns a bare array
        # (the existing card already consumes it as such), and
        # zone_coverage_health is a per-room snapshot, not a per-day
        # metric — it doesn't have a natural slot inside a day-by-day
        # array without either breaking that array's existing shape or
        # duplicating the same room data onto every day entry.
        if fmt == "zone_coverage_health":
            if data.mission_store is None:
                return self.json({}, status_code=200)
            _region_map = {
                r["id"]: r["name"]
                for r in (getattr(data.cloud_coordinator, "regions", None) or [])
                if r.get("id")
            } if data.cloud_coordinator is not None else {}
            _umf = (
                data.umf_aligner.rid_to_name()
                if not _region_map and data.umf_aligner and data.umf_aligner.aligned
                else None
            )
            # v3.3.0 ROOM-SCHED foundation fix — derive rooms per record
            result = data.mission_store.room_coverage_health(
                dt_util.now().isoformat(), region_map=_region_map, umf_regions=_umf
            )
            return self.json(result)

        # -- format=hazards ---------------------------------------------------
        # F9 — returns GridStore stuck hotspots and UMF-seeded obstacle zones.
        # F22 (v3.3.1) — see dominant_weekday/dominant_hour merge below.
        # Known, accepted gap: stuck_pattern() uses a higher confidence
        # threshold (8) than hotspots() (3), so pins with stuck_count 3-7
        # always carry null dominant_weekday/dominant_hour — not a bug,
        # just below the pattern-detection confidence bar.
        if fmt == "hazards":
            from .models import MapCapability
            if data.map_capability == MapCapability.NONE or data.grid_store is None:
                return self.json([])
            hazards = data.grid_store.hotspots()
            # Append UMF-seeded observed zones (source="robot_learned")
            if data.has_cloud:
                import math
                for centroid in data.cloud_coordinator.observed_zone_centroids:
                    x = centroid.get("x") or 0.0
                    y = centroid.get("y") or 0.0
                    hazards.append({
                        "gx":          None,
                        "gy":          None,
                        "x_mm":        x,
                        "y_mm":        y,
                        "stuck_count": None,
                        "room_name":   None,
                        "bearing_deg": int(math.degrees(math.atan2(x, y)) % 360),
                        "distance_mm": int(math.sqrt(x ** 2 + y ** 2)),
                        "source":      "robot_learned",
                    })
                # v2.3.0 Step 8 / Gap B — keepout zone centroids
                for zone in data.cloud_coordinator.keepout_zones:
                    cx = zone.get("cx") or zone.get("centroid_x") or zone.get("x")
                    cy = zone.get("cy") or zone.get("centroid_y") or zone.get("y")
                    if cx is not None and cy is not None:
                        cx, cy = float(cx), float(cy)
                        hazards.append({
                            "gx":          None,
                            "gy":          None,
                            "x_mm":        cx,
                            "y_mm":        cy,
                            "stuck_count": None,
                            "room_name":   None,
                            "bearing_deg": int(math.degrees(math.atan2(cx, cy)) % 360),
                            "distance_mm": int(math.sqrt(cx ** 2 + cy ** 2)),
                            "source":      "keepout",
                        })

            # F22 (v3.3.1) — merge GridStore.stuck_pattern()'s dominant
            # weekday/hour onto matching stuck_events pins. Runs after the
            # robot_learned/keepout appends above so every hazard dict gets
            # both keys (defaulting null), keeping the response schema
            # uniform across sources.
            patterns = data.grid_store.stuck_pattern()
            for hazard in hazards:
                dominant_weekday = None
                dominant_hour = None
                if hazard.get("source") == "stuck_events" and patterns:
                    slot = patterns.get((hazard["gx"], hazard["gy"]))
                    if slot:
                        dominant_weekday, dominant_hour = slot
                hazard["dominant_weekday"] = dominant_weekday
                hazard["dominant_hour"] = dominant_hour

            # v2.3.0 Step 8 — populate room_name via UmfAligner
            aligner = getattr(data, "umf_aligner", None)
            if aligner and aligner.aligned:
                for hazard in hazards:
                    source   = hazard.get("source")
                    x_mm     = hazard["x_mm"]
                    y_mm     = hazard["y_mm"]
                    if source == "stuck_events":
                        pt_umf = aligner.pose_to_umf(x_mm, y_mm)
                        if pt_umf:
                            hazard["room_name"] = aligner.room_name_at(*pt_umf)
                    elif source in ("robot_learned", "keepout"):
                        hazard["room_name"] = aligner.room_name_at(x_mm, y_mm)

            return self.json(hazards)

        # -- format=export (F15) ----------------------------------------------
        # Returns a versioned JSON bundle of all MissionStore records for
        # backup / migration purposes.  Schema is frozen at version 1;
        # new fields added in later versions carry null defaults.
        if fmt == "export":
            records_out: list[dict] = []
            if data.mission_store is not None:
                records_out = list(data.mission_store.records)
            blid = entry.data.get("blid", "")
            return self.json({
                "export_version": 1,
                "exported_at": dt_util.utcnow().isoformat(),
                "blid": blid,
                "record_count": len(records_out),
                "records": records_out,
            })

        # -- format=records ---------------------------------------------------
        # F7o -- distinguish coordinator failure from genuinely empty data.
        if data.has_cloud and not data.cloud_coordinator.last_update_success:
            return self.json_message("Cloud coordinator unavailable", status_code=503)

        # Build local zone index for F4a injection into cloud records
        local_zones_index: dict[int, list[str]] = {}
        if data.mission_store is not None:
            local_zones_index = _build_local_zones_index(data.mission_store.records)

        if data.has_cloud and data.cloud_coordinator.raw_records:
            unified = [
                _cloud_record_to_unified(r)
                for r in data.cloud_coordinator.raw_records
            ]
            # F4a -- inject zone names from local store into cloud records
            if local_zones_index:
                unified = [_inject_zones(r, local_zones_index) for r in unified]
            # Cloud records are newest-first -- reverse to ascending for card
            records = list(reversed(unified))

            # v2.10.2 (RECORDS-UNION) -- a mission that completed locally
            # (real MQTT state transition) but never got a matching cloud
            # record -- for whatever reason on iRobot's side -- was
            # previously invisible here whenever the cloud was healthy,
            # even though format=summary's `total` (always local) counts
            # it. Confirmed in the field: total=3 for a day while this
            # endpoint, cloud-sourced, only had 2. Fill the gap with any
            # local record from the same window that never got a cloud
            # merge match (see _local_record_has_cloud_merge_signal).
            if data.mission_store is not None:
                try:
                    union_days = int(request.query.get("days", 90))
                    union_days = max(1, min(union_days, 90))
                except (ValueError, TypeError):
                    union_days = 90
                unmatched_local = [
                    _local_record_to_unified(r)
                    for r in data.mission_store.query(union_days)
                    if not _local_record_has_cloud_merge_signal(r)
                ]
                if unmatched_local:
                    records = sorted(
                        records + unmatched_local,
                        key=lambda r: r.get("started_at") or "",
                    )
        elif data.mission_store is not None:
            try:
                days = int(request.query.get("days", 90))
                days = max(1, min(days, 90))
            except (ValueError, TypeError):
                days = 90
            local = data.mission_store.query(days)
            records = [_local_record_to_unified(r) for r in local]
        else:
            records = []

        # v2.3.0 — inject alignment_confidence for cloud-source records
        aligner = getattr(data, "umf_aligner", None)
        if aligner and aligner.aligned:
            conf = round(aligner.confidence, 2)
            for r in records:
                if r.get("source") == "cloud":
                    r["alignment_confidence"] = conf

        return self.json(records)


class ExplainMissionView(HomeAssistantView):
    """GET /api/roomba_plus/{entry_id}/mission/{mission_id}/explain

    v3.2.0 ANOMALY-EXPLAIN — REST counterpart to the explain_mission
    service. Both delegate to MissionStore.explain_mission() so the
    explanation logic lives in exactly one place.

    mission_id path segment "latest" resolves to the most recent mission
    instead of requiring the caller to already know a specific mission id
    (mirrors the service's mission_id=None default).
    """

    url = "/api/roomba_plus/{entry_id}/mission/{mission_id}/explain"
    name = "api:roomba_plus:mission_explain"
    requires_auth = True

    async def get(
        self, request: web.Request, entry_id: str, mission_id: str
    ) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entry = hass.config_entries.async_get_entry(entry_id)
        if entry is None or entry.domain != DOMAIN:
            return self.json_message("Entry not found", status_code=404)

        if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
            return self.json_message("Integration initialising", status_code=503)

        data: RoombaData = entry.runtime_data
        if data.mission_store is None:
            return self.json_message("No mission history available", status_code=404)

        resolved_id = None if mission_id == "latest" else mission_id

        # EXPLAIN-CLOUD (v3.3.1) — a cloud-only synthetic id ("c_{ts}")
        # never exists in MissionStore._records, so find_by_id() alone
        # would always 404 it. Only engage the cloud-resolution fallback
        # for ids that actually look like one ("c_" prefix) — a real
        # local id ("m_...") or a cloud missionId ULID (now also matched
        # directly by find_by_id(), see Fund 2 fix there) never takes
        # this path.
        record_override = None
        if resolved_id is not None and resolved_id.startswith("c_"):
            record_override = _resolve_cloud_explain_record(data, resolved_id)
            if record_override is None:
                return self.json_message("Mission not found", status_code=404)

        result = data.mission_store.explain_mission(
            None if record_override is not None else resolved_id,
            record_override=record_override,
        )
        if result is None:
            return self.json_message("Mission not found", status_code=404)

        return self.json(result)


class MissionPathView(HomeAssistantView):
    """GET /api/roomba_plus/{entry_id}/mission/{nMssn}/path

    v3.2.0 MISSION-REPLAY — room-granular post-hoc reconstruction of a
    mission's path: "Robot was in Kitchen at 09:05, Hallway at 09:23,
    Bedroom at 09:31." Not pixel-accurate pose tracking — built from
    MissionArchive.mission_path()'s collapsed room_visits (same data
    ROOM-ACCESS's traversal-efficiency signal already uses), so this
    needed far less new code than originally scoped: the underlying
    room_visits extraction already existed.

    Room-name resolution: cloud_coordinator.regions (SMART tier) or
    room_seg_store.rooms[rid].name (EPHEMERAL tier) — whichever the
    entry has available. Falls back to the raw rid when neither
    resolves a name for a given room.
    """

    url = "/api/roomba_plus/{entry_id}/mission/{n_mssn}/path"
    name = "api:roomba_plus:mission_path"
    requires_auth = True

    async def get(
        self, request: web.Request, entry_id: str, n_mssn: str
    ) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entry = hass.config_entries.async_get_entry(entry_id)
        if entry is None or entry.domain != DOMAIN:
            return self.json_message("Entry not found", status_code=404)

        if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
            return self.json_message("Integration initialising", status_code=503)

        data: RoombaData = entry.runtime_data
        archive = getattr(data, "mission_archive", None)
        if archive is None:
            return self.json_message("No mission archive available", status_code=404)

        try:
            n_mssn_int = int(n_mssn)
        except ValueError:
            return self.json_message("Invalid mission number", status_code=400)

        record = archive.find_by_nMssn(n_mssn_int)
        if record is None:
            return self.json_message("Mission not found", status_code=404)

        from .mission_archive import MissionArchive, _ts_to_iso
        room_visits = record.get("room_visits") or []
        path = MissionArchive.mission_path(room_visits)

        id_to_name: dict[str, str] = {}
        cc = data.cloud_coordinator
        if cc is not None and cc.regions:
            id_to_name = {
                r["id"]: r["name"] for r in cc.regions if r.get("id") and r.get("name")
            }
        elif getattr(data, "room_seg_store", None) is not None:
            id_to_name = {
                rid: room.name
                for rid, room in data.room_seg_store.rooms.items()
                if room.name
            }

        timeline = [
            {
                "room": id_to_name.get(step["rid"], step["rid"]),
                "time": _ts_to_iso(step["ts"]),
            }
            for step in path
        ]

        return self.json({"nMssn": n_mssn_int, "path": timeline})


class MissionHistoryImportView(HomeAssistantView):
    """POST /api/roomba_plus/{entry_id}/mission_history/import

    F16 — import a v1 export bundle produced by format=export.
    Deduplicates against existing records by id — no overwrites.
    Returns {"imported": N, "skipped": N, "errors": []}.
    """

    url = "/api/roomba_plus/{entry_id}/mission_history/import"
    name = "api:roomba_plus:mission_history_import"
    requires_auth = True

    async def post(self, request: web.Request, entry_id: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entry = hass.config_entries.async_get_entry(entry_id)
        if entry is None or entry.domain != DOMAIN:
            return self.json_message("Entry not found", status_code=404)

        if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
            return self.json_message("Integration initialising", status_code=503)

        data: RoombaData = entry.runtime_data
        if data.mission_store is None:
            return self.json_message("Mission store unavailable", status_code=503)

        try:
            body = await request.json()
        except Exception:
            return self.json_message("Invalid JSON body", status_code=400)

        if not isinstance(body, dict):
            return self.json_message("Body must be a JSON object", status_code=400)

        version = body.get("export_version")
        if version is None:
            return self.json_message(
                "Missing export_version field", status_code=400
            )
        if version != 1:
            return self.json_message(
                f"Unsupported export_version {version!r}. Only version 1 is supported.",
                status_code=400,
            )

        incoming: list[dict] = body.get("records", [])
        if not isinstance(incoming, list):
            return self.json_message("records must be a list", status_code=400)

        # Bug 4 fix: reject oversized payloads before allocating memory.
        # 2 × MAX_RECORDS is a generous ceiling — legitimate exports from a
        # single robot can contain at most MAX_RECORDS (365) entries.
        from .mission_store import MAX_RECORDS
        if len(incoming) > MAX_RECORDS * 2:
            return self.json_message(
                f"records list too large: {len(incoming)} entries "
                f"(maximum {MAX_RECORDS * 2})",
                status_code=400,
            )

        # v3.3.0 STORE-ENCAP — full-history dedup and MAX_RECORDS trimming
        # now live inside MissionStore.append_validated(); this endpoint
        # previously rebuilt both invariants ad hoc (the documented
        # tech-debt bug source).
        imported = 0
        skipped = 0
        errors: list[str] = []

        def _record_type_errors(rec: dict) -> str | None:
            """v3.2.0 full-review fix — field-TYPE validation, previously
            absent entirely: a record only needed an `id` to be accepted,
            so e.g. `\"ended_at\": 12345` (int instead of ISO string) was
            persisted as-is and then crashed room_coverage_health() — and
            every other consumer that feeds timestamps to
            dt_util.parse_datetime — on EVERY subsequent cloud-refresh
            cycle, permanently, since the poisoned record survives
            restarts. Reproduced directly before this fix. Validating
            once at the import gate beats making every one of the many
            store consumers individually defensive."""
            for key in ("started_at", "ended_at", "result", "initiator"):
                if key in rec and rec[key] is not None and not isinstance(rec[key], str):
                    return f"field {key!r} must be a string or null"
            for key in ("duration_min", "area_sqft", "error_code", "bbrun_hr"):
                if key in rec and rec[key] is not None and not isinstance(rec[key], (int, float)):
                    return f"field {key!r} must be a number or null"
            for key in ("zones", "last_cleaned_rooms"):
                if key in rec and rec[key] is not None:
                    if not isinstance(rec[key], list) or not all(
                        isinstance(z, str) for z in rec[key]
                    ):
                        return f"field {key!r} must be a list of strings or null"
            return None

        for i, rec in enumerate(incoming):
            if not isinstance(rec, dict):
                errors.append(f"Record at index {i} is not a dict — skipped")
                skipped += 1
                continue
            rec_id = rec.get("id")
            if not rec_id or not isinstance(rec_id, str):
                errors.append(f"Record at index {i} has no string id field — skipped")
                skipped += 1
                continue
            type_error = _record_type_errors(rec)
            if type_error is not None:
                errors.append(f"Record {rec_id!r}: {type_error} — skipped")
                skipped += 1
                continue
            if not data.mission_store.append_validated(rec):
                skipped += 1  # duplicate id anywhere in the full history
                continue
            imported += 1

        if imported > 0:
            await data.mission_store.async_save(hass, entry_id)
            _LOGGER.info(
                "MissionHistoryImport: imported %d new record(s) for %s",
                imported, entry_id,
            )

        return self.json({
            "imported": imported,
            "skipped": skipped,
            "errors": errors,
        })


class HouseholdSummaryView(HomeAssistantView):
    """GET /api/roomba_plus/household?days=28

    F10b — aggregates all roomba_plus config entries. Returns per-robot
    breakdown with floor label, per-floor breakdown when labels are configured,
    and combined totals.

    v3.4.3 FLEET-1 — each robot entry additionally carries a health rollup
    (health_trend from RobotProfileStore.health_score_trend(),
    battery_capacity_retention_pct, maintenance_due, needs_attention), plus
    a top-level fleet_health summary (robot_count, robots_needing_attention)
    derived from those same per-robot fields.
    """

    url = "/api/roomba_plus/household"
    name = "api:roomba_plus:household"
    requires_auth = True

    async def get(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]

        try:
            days = int(request.query.get("days", 28))
            days = max(1, min(days, 90))
        except (ValueError, TypeError):
            days = 28

        entries = hass.config_entries.async_entries(DOMAIN)
        robots: list[dict] = []
        total_missions = 0
        total_completed = 0
        total_area: float | None = None
        floors: dict[str, dict] = {}

        for entry in entries:
            if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
                continue
            data = entry.runtime_data
            if data.mission_store is None:
                continue

            by_day = data.mission_store.query_by_day(days)
            missions   = sum(s.total     for s in by_day.values())
            completed  = sum(s.completed for s in by_day.values())
            area_vals  = [s.area_sqft   for s in by_day.values()
                          if s.area_sqft is not None]
            area: float | None = sum(area_vals) if area_vals else None
            comp_pct   = round(100 * completed / missions, 1) if missions else 0.0

            floor_label = getattr(data, "floor_label", "") or ""

            # v3.4.3 FLEET-1 — per-robot health rollup. Reuses already-
            # computed/cached signals living directly on RoombaData/
            # RobotProfileStore rather than recomputing the full L8
            # weighted health score (which needs several more live inputs
            # not cached as simple fields) or reading through HA's entity/
            # state layer (no existing precedent in this file for that —
            # every other field here comes from a store object already on
            # `data`, same pattern followed here).
            health_trend = None
            if data.robot_profile_store is not None:
                health_trend = data.robot_profile_store.health_score_trend()

            maintenance_due = False
            if data.maintenance_store is not None:
                # Local import — api_views.py is imported eagerly by
                # __init__.py at module level (unlike platform modules
                # such as switch.py/binary_sensor.py, which HA loads
                # later), so a top-level `from . import
                # roomba_reported_state` here creates a genuine circular
                # import. Deferred import resolves it: by the time
                # get() actually runs (at request time), __init__.py has
                # long since finished initializing.
                from . import roomba_reported_state
                vac_state = roomba_reported_state(data.roomba)
                maintenance_due = bool(
                    data.maintenance_store.due_items(vac_state, entry.options)
                )

            needs_attention = maintenance_due or health_trend == "declining"

            robots.append({
                "entry_id":       entry.entry_id,
                "name":           entry.title or "Roomba",
                "floor":          floor_label,
                "missions":       missions,
                "completed":      completed,
                "completion_pct": comp_pct,
                "area_sqft":      area,
                "health_trend":                    health_trend,
                "battery_capacity_retention_pct":  data.battery_retention_value,
                "maintenance_due":                 maintenance_due,
                "needs_attention":                 needs_attention,
            })
            total_missions  += missions
            total_completed += completed
            if area is not None:
                total_area = (total_area or 0.0) + area

            if floor_label:
                f = floors.setdefault(floor_label, {
                    "label": floor_label, "missions": 0,
                    "completed": 0, "area_sqft": None,
                })
                f["missions"]  += missions
                f["completed"] += completed
                if area is not None:
                    f["area_sqft"] = (f["area_sqft"] or 0.0) + area

        total_comp_pct = (
            round(100 * total_completed / total_missions, 1)
            if total_missions else 0.0
        )

        # v3.4.3 FLEET-1 — fleet-wide health rollup, derived from the
        # per-robot fields already built above (no re-iteration needed).
        robots_needing_attention = [
            r["name"] for r in robots if r["needs_attention"]
        ]

        result: dict[str, Any] = {
            "period_days": days,
            "total": {
                "missions":       total_missions,
                "completed":      total_completed,
                "completion_pct": total_comp_pct,
                "area_sqft":      total_area,
            },
            "fleet_health": {
                "robot_count":              len(robots),
                "robots_needing_attention": robots_needing_attention,
            },
            "robots": robots,
        }
        if floors:
            result["floors"] = list(floors.values())

        return self.json(result)


class DailyDigestView(HomeAssistantView):
    """GET /api/roomba_plus/{entry_id}/digest?date=2026-06-16

    v2.9.0 DAILY-DIGEST — compact one-day summary for the card's "Today"
    status slot. ``date`` defaults to today (robot's local timezone) when
    omitted.

    Response shape:
        {"missions": 2, "area_m2": 72.1, "stuck_events": 0,
         "demand_cleans": 1, "filter_hours_today": 1.4,
         "battery_cycles_today": 2}

    filter_hours_today / battery_cycles_today are TRUE day-attributable
    deltas of the respective lifetime counters (bbrun_hr / battery_cycles,
    both absolute snapshots captured per-mission in MissionStore), not a
    proxy — see _lifetime_delta_for_day() below. Both are None when there
    is no prior record to diff against (e.g. the robot's very first day of
    recorded history) rather than guessing a 0 baseline, which could silently
    misreport an unknown amount as "zero used today".
    """

    url = "/api/roomba_plus/{entry_id}/digest"
    name = "api:roomba_plus:digest"
    requires_auth = True

    async def get(self, request: web.Request, entry_id: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entry = hass.config_entries.async_get_entry(entry_id)
        if entry is None or entry.domain != DOMAIN:
            return self.json_message("Entry not found", status_code=404)

        if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
            return self.json_message("Integration initialising", status_code=503)

        data: RoombaData = entry.runtime_data

        date_str = request.query.get("date")
        if date_str:
            try:
                target_date = datetime.date.fromisoformat(date_str)
            except ValueError:
                return self.json_message(
                    f"Invalid date '{date_str}' — expected YYYY-MM-DD",
                    status_code=400,
                )
        else:
            target_date = dt_util.now().date()

        if data.mission_store is None:
            return self.json({
                "missions": 0, "area_m2": None, "stuck_events": 0,
                "demand_cleans": 0, "filter_hours_today": None,
                "battery_cycles_today": None,
            })

        # MAX_RECORDS (365) is the full retention window — a large enough
        # lookback to find both target_date's records AND the most recent
        # record strictly before it, however far back that is.
        from .mission_store import MAX_RECORDS
        all_records = data.mission_store.query(MAX_RECORDS + 30)

        day_records = [
            r for r in all_records
            if (lambda dt: dt is not None and dt_util.as_local(dt).date() == target_date)
            (dt_util.parse_datetime(r.get("started_at", "")))
        ]

        areas = [r["area_sqft"] for r in day_records if r.get("area_sqft") is not None]
        stuck_events = sum(
            1 for r in day_records
            if r.get("result") in ("stuck", "stuck_and_abandoned")
        )
        demand_cleans = sum(1 for r in day_records if r.get("initiator") == "demand")

        filter_hours_today = self._lifetime_delta_for_day(
            all_records, target_date, "bbrun_hr",
        )
        battery_cycles_today_raw = self._lifetime_delta_for_day(
            all_records, target_date, "battery_cycles",
        )

        return self.json({
            "missions": len(day_records),
            "area_m2": round(sum(areas) * SQFT_TO_M2, 1) if areas else None,
            "stuck_events": stuck_events,
            "demand_cleans": demand_cleans,
            "filter_hours_today": (
                round(filter_hours_today, 1)  # bbrun_hr is already in hours
                if filter_hours_today is not None else None
            ),
            "battery_cycles_today": (
                int(round(battery_cycles_today_raw))
                if battery_cycles_today_raw is not None else None
            ),
        })

    @staticmethod
    def _lifetime_delta_for_day(
        all_records: list[dict[str, Any]],
        target_date: datetime.date,
        field: str,
    ) -> float | None:
        """Return the TRUE increase of an absolute lifetime counter field
        attributable to target_date, or None if there's nothing to diff
        against.

        Both bbrun_hr and battery_cycles are monotonically-increasing
        snapshots of the robot's lifetime counters, captured at mission end
        (NOT per-mission deltas — see callbacks.py async_record_mission()).
        Because these counters only change DURING a mission, the increase
        over a calendar day equals (latest value among that day's records)
        minus (latest value among all records strictly before that day) —
        regardless of how many days back that prior record is, since the
        counter cannot have changed in the gap. all_records must already be
        sorted ascending by started_at (MissionStore.query()'s contract).
        """
        on_day: float | None = None
        before_day: float | None = None
        for r in all_records:
            dt = dt_util.parse_datetime(r.get("started_at", ""))
            if dt is None:
                continue
            r_date = dt_util.as_local(dt).date()
            value = r.get(field)
            if value is None:
                continue
            if r_date == target_date:
                on_day = float(value)   # query() is ascending — last write wins
            elif r_date < target_date:
                before_day = float(value)
        if on_day is None:
            return None
        if before_day is None:
            # No record at all before target_date — cannot isolate this
            # day's share of the counter (would silently understate or
            # overstate it). Honest "unknown" rather than assuming 0.
            return None
        return max(0.0, on_day - before_day)


class MissionMapJsonView(HomeAssistantView):
    """GET /api/roomba_plus/{entry_id}/missions/{record_id}/map.json

    v3.3.0 MISSION-MAP — coordinate-level coverage of ONE finished
    mission (the official app's "Mission Cleaning Map", but for every
    mission in the history). Raw data endpoint: the card renders
    client-side from this; map.png below is the server-rendered bonus.

    record_id path segment "latest" resolves to the most recent mission.
    Error mapping: 404 record unknown / no pmaps_info / empty coverage
    layer (untested lewis firmware), 409 verification-gate mismatch
    (never serve the wrong map), 502 cloud transport failure.
    """

    url = "/api/roomba_plus/{entry_id}/missions/{record_id}/map.json"
    name = "api:roomba_plus:mission_map_json"
    requires_auth = True

    async def get(
        self, request: web.Request, entry_id: str, record_id: str
    ) -> web.Response:
        payload, data, err = await _mission_map_payload(request, entry_id, record_id)
        if err is not None:
            return self.json_message(err[1], status_code=err[0])
        # Current room polygons as rendering context (names resolved) —
        # deliberately the CURRENT map version: room shapes are the
        # backdrop, the mission's own data is the coverage layer.
        rooms: dict[str, list] = {}
        aligner = data.umf_aligner
        if aligner is not None and aligner.aligned:
            name_of = aligner.rid_to_name()
            for rid, poly in aligner.room_polygons_umf.items():
                rooms[name_of.get(rid, rid)] = [list(p) for p in poly]
        return self.json({**payload, "rooms": rooms})


class MissionMapPngView(HomeAssistantView):
    """GET /api/roomba_plus/{entry_id}/missions/{record_id}/map.png

    v3.3.0 MISSION-MAP — server-rendered coverage image: room outlines
    (current map) + this mission's coverage points. Directly usable as
    a picture-card/notification image without any card installed —
    this endpoint IS the v3.3.0 user-visible output; map.json is the
    card-v2.3.0 investment. Same error mapping as map.json.

    v3.4.1 ROTATE-PARAM: optional `?rotate=90|180|270` query parameter,
    clockwise, for Smart Maps whose orientation doesn't match a
    dashboard's expected layout — requested by a field tester (i7/lewis)
    who needed 270° (equivalently, 90° counter-clockwise) to match their
    floor plan. Any other/missing value renders unrotated, matching prior
    behaviour exactly — this is purely additive, no existing caller is
    affected.
    """

    url = "/api/roomba_plus/{entry_id}/missions/{record_id}/map.png"
    name = "api:roomba_plus:mission_map_png"
    requires_auth = True

    async def get(
        self, request: web.Request, entry_id: str, record_id: str
    ) -> web.Response:
        payload, data, err = await _mission_map_payload(request, entry_id, record_id)
        if err is not None:
            return self.json_message(err[1], status_code=err[0])
        hass: HomeAssistant = request.app["hass"]
        rooms: list[list] = []
        aligner = data.umf_aligner
        if aligner is not None and aligner.aligned:
            rooms = list(aligner.room_polygons_umf.values())
        try:
            rotate = int(request.query.get("rotate", 0))
        except ValueError:
            rotate = 0
        from .mission_map import render_mission_map_png
        png = await hass.async_add_executor_job(
            render_mission_map_png, payload["coverage_mm"],
            payload.get("point_area_m") or [], rooms, rotate,
        )
        return web.Response(body=png, content_type="image/png")


async def _mission_map_payload(
    request: web.Request, entry_id: str, record_id: str
):
    """Shared record-resolution + fetch + error mapping for both
    MISSION-MAP views (one rule set, two output formats).

    Returns (payload, data, error): exactly one of payload/error is set;
    error is a (status_code, message) tuple the view renders via its own
    self.json_message (bug-hunt round 1: the first draft called the
    instance method json_message with the CLASS as self — worked only by
    accident because it delegates to the static json())."""
    from .cloud_api import CloudApiError
    from .mission_map import (
        MissionMapMismatch,
        MissionMapUnavailable,
        async_fetch_mission_map,
    )

    hass: HomeAssistant = request.app["hass"]
    entry = hass.config_entries.async_get_entry(entry_id)
    if entry is None or entry.domain != DOMAIN:
        return None, None, (404, "Entry not found")
    if not hasattr(entry, "runtime_data") or entry.runtime_data is None:
        return None, None, (503, "Integration initialising")
    data: RoombaData = entry.runtime_data
    ms = data.mission_store
    if ms is None:
        return None, None, (404, "No mission history available")
    if record_id == "latest":
        record = ms.latest()
    elif record_id.startswith("c_"):
        # MISSION-MAP-CLOUD-ROWS — synthetic cloud-only id, never in
        # ms.records. Same fallback shape as EXPLAIN-CLOUD (v3.3.1);
        # None here means genuinely unresolvable (not merely no
        # pmaps_info — that 404s further down, inside
        # async_fetch_mission_map() itself).
        record = _resolve_cloud_mission_map_record(data, record_id)
    else:
        record = next(
            (r for r in ms.records if str(r.get("id")) == record_id), None
        )
    if record is None:
        return None, None, (404, "Mission not found")
    try:
        payload = await async_fetch_mission_map(data, record)
    except MissionMapUnavailable as exc:
        return None, None, (404, str(exc))
    except MissionMapMismatch as exc:
        return None, None, (409, str(exc))
    except CloudApiError as exc:
        return None, None, (502, f"Cloud error: {exc}")
    return payload, data, None
