"""Blocking Manager for Roomba+ — pre-start environment gate.

Checks configured binary sensors before starting a clean. If any blocking
sensor is active (ON), the start is either aborted or queued (per config)
until all sensors clear or a timeout expires.

Lifecycle (must be respected by callers):
  - Instantiate in async_setup_entry when CONF_BLOCKING_SENSORS is non-empty.
  - Store in entry.runtime_data.blocking_manager.
  - Call cancel_queue() in async_unload_entry — always, unconditionally.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import logging
from datetime import timedelta
from typing import TYPE_CHECKING, Any

from homeassistant.core import HomeAssistant, callback

# Event is available in production HA; guarded for the lightweight test stub environment.
try:
    from homeassistant.core import Event
except ImportError:  # pragma: no cover
    Event = object  # type: ignore[assignment,misc]
from homeassistant.util import dt as dt_util

from .const import (
    CONF_BLOCKING_BEHAVIOR,
    CONF_BLOCKING_SENSORS,
    CONF_BLOCKING_TIMEOUT_MIN,
    DEFAULT_BLOCKING_BEHAVIOR,
    DEFAULT_BLOCKING_TIMEOUT_MIN,
    DOMAIN,
)

if TYPE_CHECKING:
    from .models import RoombaConfigEntry

_LOGGER = logging.getLogger(__name__)

# HA event names fired by the blocking manager
EVENT_START_BLOCKED = f"{DOMAIN}_start_blocked"
EVENT_START_TIMEOUT = f"{DOMAIN}_start_timeout"

# Sensor states that count as "active / blocking"
_ACTIVE_STATES = frozenset({"on", "home", "true"})
# States that mean "sensor is not usable" — treated as non-blocking
_UNUSABLE_STATES = frozenset({"unavailable", "unknown"})


class BlockingManager:
    """Check binary sensors before a smart_start and optionally queue the start.

    The manager is intentionally stateless between calls to check_and_start().
    It holds transient queue state only while a start is pending.
    """

    def __init__(self, hass: HomeAssistant, config_entry: RoombaConfigEntry) -> None:
        self._hass = hass
        self._entry = config_entry
        # Active unsubscribe callables — non-empty iff a start is queued
        self._cancel_listeners: list[Any] = []
        # Queue metadata — set when queued, cleared by cancel_queue()
        self._queued_since: str | None = None
        self._timeout_at: str | None = None
        self._timeout_task: asyncio.Task | None = None
        self._queued_rooms: list[str] | None = None
        self._state_callbacks: list[Any] = []

    # ── Public state ──────────────────────────────────────────────────────────

    def register_state_callback(self, callback_fn: Any) -> None:
        """Register a callable invoked when queue state changes.

        Used by RoombaStartBlocked to receive immediate updates without
        waiting for the next MQTT message. Returns an unsubscribe callable
        that removes the callback when the entity is cleaned up.
        """
        self._state_callbacks.append(callback_fn)

        def _unsub() -> None:
            try:
                self._state_callbacks.remove(callback_fn)
            except ValueError:
                pass

        return _unsub

    def _notify_state_change(self) -> None:
        """Call all registered state callbacks."""
        for cb in self._state_callbacks:
            try:
                cb()
            except Exception:  # noqa: BLE001
                pass

    @property
    def is_queued(self) -> bool:
        """True while a start is pending sensor clearance."""
        return bool(self._cancel_listeners)

    @property
    def queued_since(self) -> str | None:
        """ISO datetime when the current queue started, or None."""
        return self._queued_since

    @property
    def timeout_at(self) -> str | None:
        """ISO datetime when the current queue will time out, or None."""
        return self._timeout_at

    @property
    def blocking_entities(self) -> list[str]:
        """Return entity IDs of sensors that are currently active/blocking."""
        sensor_ids: list[str] = self._entry.options.get(CONF_BLOCKING_SENSORS, [])
        blocking = []
        for eid in sensor_ids:
            state = self._hass.states.get(eid)
            if state is None:
                continue
            if state.state in _UNUSABLE_STATES:
                # Treat unavailable/unknown sensors as non-blocking to avoid
                # permanently blocking starts when a sensor goes offline.
                continue
            if state.state.lower() in _ACTIVE_STATES:
                blocking.append(eid)
        return blocking

    # ── Main entry point ──────────────────────────────────────────────────────

    async def check_and_start(
        self,
        rooms: list[str] | None,
        override: bool,
    ) -> None:
        """Check blocking sensors and start or queue accordingly.

        Args:
            rooms:    Optional room names for targeted clean (SMART only).
            override: When True, start immediately regardless of sensor state.
        """
        if override or not self.blocking_entities:
            await self._do_start(rooms)
            return

        behavior: str = self._entry.options.get(
            CONF_BLOCKING_BEHAVIOR, DEFAULT_BLOCKING_BEHAVIOR
        )
        if behavior == "abort":
            self._hass.bus.async_fire(
                EVENT_START_BLOCKED,
                {"blocking_entities": self.blocking_entities},
            )
            _LOGGER.info(
                "BlockingManager: start aborted — active sensors: %s",
                self.blocking_entities,
            )
            return

        # behavior == "queue"
        if self.is_queued:
            _LOGGER.debug(
                "BlockingManager: already queued — ignoring duplicate request"
            )
            return
        self._queue_start(rooms)

    # ── Queue internals ───────────────────────────────────────────────────────

    def _queue_start(self, rooms: list[str] | None) -> None:
        """Register state listeners and wait for all sensors to clear."""
        self._queued_rooms = rooms
        now = dt_util.now()
        timeout_min: int = self._entry.options.get(
            CONF_BLOCKING_TIMEOUT_MIN, DEFAULT_BLOCKING_TIMEOUT_MIN
        )
        self._queued_since = now.isoformat()
        self._timeout_at = (now + timedelta(minutes=timeout_min)).isoformat()
        self._notify_state_change()

        sensor_ids: list[str] = self._entry.options.get(CONF_BLOCKING_SENSORS, [])

        @callback
        def _on_state_changed(event: Event) -> None:
            """Fire when any tracked sensor changes — check if all clear."""
            if not self.is_queued:
                return
            if not self.blocking_entities:
                # All sensors cleared — start in a new task to avoid blocking
                # the event loop from within the event callback.
                self._hass.async_create_task(
                    self._trigger_queued_start(),
                    name="roomba_plus_blocking_queue_start",
                )

        for eid in sensor_ids:
            unsub = self._hass.bus.async_listen(
                "state_changed",
                _on_state_changed,
                event_filter=lambda e, _eid=eid: (
                    e.data.get("entity_id") == _eid
                ),
            )
            self._cancel_listeners.append(unsub)

        self._timeout_task = self._hass.async_create_task(
            self._run_timeout(timeout_min * 60),
            name="roomba_plus_blocking_timeout",
        )
        _LOGGER.info(
            "BlockingManager: start queued — will try for %d min. "
            "Active sensors: %s",
            timeout_min,
            self.blocking_entities,
        )

    async def _trigger_queued_start(self) -> None:
        """Start the clean now that all sensors have cleared."""
        if not self.is_queued:
            return  # Cancelled between check and execution
        rooms = self._queued_rooms
        self.cancel_queue()
        await self._do_start(rooms)

    async def _run_timeout(self, seconds: int) -> None:
        """Sleep for timeout then cancel queue and fire the timeout event."""
        try:
            await asyncio.sleep(seconds)
        except asyncio.CancelledError:
            return  # Task was cancelled by cancel_queue() — no event
        if self.is_queued:
            _LOGGER.warning(
                "BlockingManager: queue timed out after %d s — "
                "sensors still active: %s",
                seconds,
                self.blocking_entities,
            )
            self._hass.bus.async_fire(EVENT_START_TIMEOUT, {})
            self.cancel_queue()

            # F6c — record the timeout as a blocked_timeout mission result
            from .callbacks import async_record_mission
            self._hass.async_create_task(
                async_record_mission(
                    self._hass,
                    self._entry,
                    mission={},
                    reported={},
                    zones=[],
                    start_ts=int(dt_util.utcnow().timestamp()),
                    nstuck_delta=0,
                    result_override="blocked_timeout",
                ),
                name="roomba_plus_blocked_timeout_record",
            )

            # F6g — increment consecutive skip counter in MaintenanceStore
            store = self._entry.runtime_data.maintenance_store
            if store is not None:
                store.consecutive_skips += 1
                _LOGGER.debug(
                    "BlockingManager: consecutive_skips now %d",
                    store.consecutive_skips,
                )
                # Persist immediately so the counter survives HA restarts.
                # (The consecutive_skips Repair Issue was removed in v3.5.0 —
                # the count is already exposed by the consecutive_clean_skips
                # sensor; the store save below still feeds that sensor.)
                self._hass.async_create_task(
                    store.async_save(self._hass, self._entry.entry_id),
                    name="roomba_plus_consecutive_skips_save",
                )

    async def _do_start(self, rooms: list[str] | None) -> None:
        """Execute the actual start command on the robot.

        CORRECTED (this session): used to unconditionally assume a
        Classic entry (data.roomba, plain hass.services.async_call to
        the Classic-only clean_room service). Both would fail for a
        Prime/CLOUD_ONLY entry -- data.roomba is None (AttributeError),
        and clean_room's underlying region-based transport is still
        unconfirmed for Prime (two live field tests, zero effect so
        far). See services.py's own async_handle_smart_start() for the
        equivalent fix on the OTHER path that can reach a robot start
        (this manager isn't the only caller -- smart_start falls
        through to data.roomba.start directly when no blocking sensors
        are configured at all, i.e. blocking_manager is None)."""
        from homeassistant.helpers import entity_registry as er
        from .models import ConnectionType, RoombaData

        data: RoombaData = self._entry.runtime_data

        if rooms:
            if data.connection_type == ConnectionType.CLOUD_ONLY:
                _LOGGER.error(
                    "BlockingManager: room-targeted start requested for a "
                    "Prime/V4 robot (blid=%s) -- not supported yet, region-"
                    "based cleaning commands are still unconfirmed for "
                    "Prime devices. Nothing was sent.",
                    data.blid,
                )
                return
            # Resolve the vacuum entity_id via the entity registry using unique_id.
            # Never construct entity_id from blid — HA slugifies names at registration
            # time and the result is not guaranteed to match any specific pattern.
            robot_unique_id = f"roomba_plus_{data.blid}"
            ent_reg = er.async_get(self._hass)
            entity_entry = ent_reg.async_get_entity_id(
                "vacuum", DOMAIN, robot_unique_id
            )
            if entity_entry is None:
                _LOGGER.error(
                    "BlockingManager: cannot resolve vacuum entity for blid=%s "
                    "— smart_start with rooms aborted",
                    data.blid,
                )
                return
            await self._hass.services.async_call(
                DOMAIN,
                "clean_room",
                {"entity_id": entity_entry, "room_name": rooms},
                blocking=True,
            )
        elif data.connection_type == ConnectionType.CLOUD_ONLY:
            await data.prime_robot.send_simple_command("start")
        else:
            await self._hass.async_add_executor_job(data.roomba.start)
        _LOGGER.info("BlockingManager: start issued")

    # ── Cleanup ───────────────────────────────────────────────────────────────

    def cancel_queue(self) -> None:
        """Cancel all pending listeners and the timeout task.

        Safe to call multiple times. Must be called in async_unload_entry.
        """
        for unsub in self._cancel_listeners:
            try:
                unsub()
            except Exception:  # noqa: BLE001
                pass
        self._cancel_listeners.clear()
        self._queued_since = None
        self._timeout_at = None
        self._queued_rooms = None
        if self._timeout_task and not self._timeout_task.done():
            self._timeout_task.cancel()
        self._timeout_task = None
        _LOGGER.debug("BlockingManager: queue cancelled / cleaned up")
        self._notify_state_change()
