"""iRobot Cloud API client for Roomba+.

Implements the modern Gigya → AWS Cognito authentication flow and exposes the
iRobot REST endpoints used by SMART-capable robots (i/s/j-series) and for
mission-history polling on all robots.

Auth flow:
  1. Discover deployment endpoints from disc-prod.iot.irobotapi.com
  2. Login via Gigya SSO to obtain UID + signature
  3. Exchange with iRobot /v2/login to get AWS Cognito credentials
  4. Sign all data requests with AWS SigV4

Based on reverse engineering documented in roomba_rest980 (cloudReverse.md).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import hashlib
import hmac
import logging
import urllib.parse
import uuid
from datetime import UTC, datetime
from typing import Any

import aiohttp

from roombapy_prime import (
    AuthConnectionError as _PrimeConnectionError,
    AuthCredentialsError as _PrimeCredentialsError,
    AuthError as _PrimeAuthError,
    AuthRateLimitedError as _PrimeRateLimitedError,
    AuthSSLError as _PrimeSSLError,
    AuthTimeoutError as _PrimeTimeoutError,
    LoginResult,
    login as _prime_login,
)

_LOGGER = logging.getLogger(__name__)

def _discovery_url(country_code: str) -> str:
    """Return the iRobot endpoint discovery URL for the given ISO 3166-1 country code.

    iRobot splits its backend by region. Using the wrong country code results
    in /missionhistory and other endpoints returning empty data for EU accounts.
    The correct code is read from hass.config.country at coordinator startup.
    Falls back to "US" when HA has no country configured.
    """
    return f"https://disc-prod.iot.irobotapi.com/v1/discover/endpoints?country_code={country_code}"


# Backward-compatible name used by existing tests (v1.8.3+: parameterised by country_code)
DISCOVERY_URL: str = _discovery_url("US")

_USER_AGENT_AWS = "aws-sdk-iOS/2.27.6 iOS/18.0.1 en_US"


class CloudApiError(Exception):
    """Base exception for Cloud API errors."""


class AuthenticationError(CloudApiError):
    """The login attempt itself was rejected -- wrong username/password.

    NOT raised for rate-limiting (see RateLimitedError) or malformed/
    incomplete server responses (those stay a plain CloudApiError --
    re-entering the same, correct credentials wouldn't fix a malformed
    response, so telling the user to check their password would be
    misleading). Mirrors roombapy-prime's AuthCredentialsError, since
    v3.6.0 (login consolidation) -- see authenticate()'s docstring."""


class RateLimitedError(CloudApiError):
    """iRobot's backend rejected the login due to too many active app
    sessions/tokens (the "mqtt slot" case) -- distinct from
    AuthenticationError since the fix is "close the iRobot app and try
    again", not "check your password". Mirrors roombapy-prime's
    AuthRateLimitedError, since v3.6.0."""


class SSLCertificateError(CloudApiError):
    """TLS/certificate verification failure -- see
    _raise_clear_ssl_error(). Confidently "not your fault, temporary":
    a cert failure is unambiguous, unlike CloudConnectionError below."""


class CloudConnectionError(CloudApiError):
    """Could not establish a connection at all (DNS failure, connection
    refused, network unreachable). Deliberately does NOT claim to know
    whether this is iRobot's fault or the caller's own network -- that
    confidence isn't justified here, unlike SSLCertificateError.
    Mirrors roombapy-prime's AuthConnectionError, since v3.6.0."""


class CloudTimeoutError(CloudApiError):
    """Request was sent but no response came back in time. Mirrors
    roombapy-prime's AuthTimeoutError, since v3.6.0."""


def _raise_clear_ssl_error(exc: "aiohttp.ClientSSLError") -> None:
    """Re-raise an aiohttp SSL/certificate failure as a CloudApiError with a
    clear, actionable message instead of letting the raw aiohttp exception
    bubble up as an opaque "unknown error occurred".

    v3.5.0 bug-hunt fix, from a real-world report (wecoyote5): iRobot's own
    disc-prod.iot.irobotapi.com TLS certificate briefly expired on their
    end (confirmed by the reporter checking the cert directly in a
    browser) — not a bug in this integration, and not something a user can
    fix locally. Every network call in this module now surfaces that
    distinction clearly rather than a bare stack trace, so a user hitting
    this doesn't need to dig through the log to learn it's external and
    self-resolving.

    Deliberately does NOT offer any way to skip/ignore certificate
    verification — that would remove protection against
    man-in-the-middle attacks for every future connection this
    integration ever makes, to work around a problem that is both
    temporary (resolves once iRobot renews their certificate) and outside
    this integration's control either way.
    """
    raise SSLCertificateError(
        "Could not verify iRobot's cloud server certificate. This is "
        "almost always a temporary problem on iRobot's servers (an "
        "expired or currently-renewing TLS certificate), not something "
        "wrong with your Home Assistant setup — it should resolve on its "
        "own within a few hours. Local vacuum control is unaffected "
        "either way."
    ) from exc


# ── AWS SigV4 ─────────────────────────────────────────────────────────────────

class _AWSSignatureV4:
    """Minimal AWS Signature Version 4 implementation for iRobot API requests."""

    def __init__(self, access_key_id: str, secret_access_key: str, session_token: str) -> None:
        self._key_id = access_key_id
        self._secret = secret_access_key
        self._token = session_token

    @staticmethod
    def _hmac_sha256(key: bytes, data: str) -> bytes:
        return hmac.new(key, data.encode(), hashlib.sha256).digest()

    @staticmethod
    def _sha256_hex(data: str) -> str:
        return hashlib.sha256(data.encode()).hexdigest()

    def _signing_key(self, date_stamp: str, region: str, service: str) -> bytes:
        k = self._hmac_sha256(f"AWS4{self._secret}".encode(), date_stamp)
        k = self._hmac_sha256(k, region)
        k = self._hmac_sha256(k, service)
        return self._hmac_sha256(k, "aws4_request")

    def signed_headers(
        self,
        method: str,
        service: str,
        region: str,
        host: str,
        path: str,
        query_params: dict[str, Any] | None = None,
    ) -> dict[str, str]:
        """Return a dict of headers with AWS SigV4 Authorization included."""
        now = datetime.now(tz=UTC)
        amz_date = now.strftime("%Y%m%dT%H%M%SZ")
        date_stamp = now.strftime("%Y%m%d")

        canonical_uri = urllib.parse.quote(path, safe="/")
        qp = query_params or {}
        canonical_qs = "&".join(
            f"{urllib.parse.quote(k, safe='~')}={urllib.parse.quote(str(v), safe='~')}"
            for k in sorted(qp)
            for v in [qp[k]]
        )

        base_headers = {
            "accept": "application/json",
            "content-type": "application/json",
            "host": host,
            "user-agent": _USER_AGENT_AWS,
            "x-amz-date": amz_date,
        }
        sorted_keys = sorted(base_headers)
        canonical_headers = "".join(f"{k}:{base_headers[k]}\n" for k in sorted_keys)
        signed_hdrs = ";".join(sorted_keys)

        payload_hash = self._sha256_hex("")
        canonical_req = "\n".join([
            method.upper(), canonical_uri, canonical_qs,
            canonical_headers, signed_hdrs, payload_hash,
        ])

        algorithm = "AWS4-HMAC-SHA256"
        scope = f"{date_stamp}/{region}/{service}/aws4_request"
        string_to_sign = "\n".join([
            algorithm, amz_date, scope, self._sha256_hex(canonical_req),
        ])

        sig = hmac.new(
            self._signing_key(date_stamp, region, service),
            string_to_sign.encode(),
            hashlib.sha256,
        ).hexdigest()

        authorization = (
            f"{algorithm} Credential={self._key_id}/{scope}, "
            f"SignedHeaders={signed_hdrs}, Signature={sig}"
        )

        return {
            **base_headers,
            "Authorization": authorization,
            "x-amz-security-token": self._token,
        }


# ── Cloud API client ──────────────────────────────────────────────────────────

class IrobotCloudApi:
    """iRobot Cloud API client.

    Authenticates once per session and exposes the data endpoints used by
    Roomba+. All network calls are async (aiohttp).

    Usage:
        api = IrobotCloudApi(username, password, session)
        await api.authenticate()
        pmaps = await api.get_pmaps(blid)
    """

    def __init__(
        self,
        username: str,
        password: str,
        session: aiohttp.ClientSession,
        country_code: str = "US",
    ) -> None:
        self._username = username
        self._password = password
        self._session = session
        self._country_code = country_code

        self._app_id = str(uuid.uuid4())

        # Filled by authenticate()
        self._deployment: dict[str, Any] = {}
        self._credentials: dict[str, Any] = {}
        self.robots: dict[str, Any] = {}   # blid → robot_info
        self.login_result: LoginResult | None = None

    # ── Auth ──────────────────────────────────────────────────────────────────

    async def authenticate(self) -> None:
        """Run the full Gigya → iRobot auth flow via roombapy-prime's
        shared login() (roombapy_prime.auth). Stores credentials in-place.

        CONSOLIDATED (v3.6.0): previously this method ran its own
        Gigya/discovery/login HTTP handling (~150 lines, since removed).
        roombapy-prime's login() implements the exact same flow --
        confirmed identical endpoint-for-endpoint, payload-for-payload,
        since it was originally carried over FROM this file -- so this
        removes a maintained duplicate rather than changing behavior.

        Catches roombapy-prime's typed exception subclasses and maps
        each to this module's own vocabulary, so existing callers
        (config_flow.py, cloud_coordinator.py) keep working against
        CloudApiError/AuthenticationError/etc. without needing to know
        anything about roombapy-prime directly -- that mapping is this
        method's job, not theirs.
        """
        try:
            result = await _prime_login(
                self._session, self._username, self._password, self._country_code,
                app_id=f"IOS-{self._app_id}",
            )
        except _PrimeCredentialsError as exc:
            raise AuthenticationError(str(exc)) from exc
        except _PrimeRateLimitedError as exc:
            raise RateLimitedError(str(exc)) from exc
        except _PrimeSSLError as exc:
            raise SSLCertificateError(str(exc)) from exc
        except _PrimeConnectionError as exc:
            raise CloudConnectionError(str(exc)) from exc
        except _PrimeTimeoutError as exc:
            raise CloudTimeoutError(str(exc)) from exc
        except _PrimeAuthError as exc:
            # Any other AuthError (malformed/incomplete response, discovery
            # response missing an expected field, etc.) -- deliberately
            # NOT AuthenticationError: re-entering the same, correct
            # credentials would not fix a malformed server response, so
            # telling the user to check their password here would be
            # misleading.
            raise CloudApiError(str(exc)) from exc

        self._deployment = result.deployment
        self._credentials = {
            "CognitoId": result.credentials.cognito_id,
            "AccessKeyId": result.credentials.access_key_id,
            "SecretKey": result.credentials.secret_key,
            "SessionToken": result.credentials.session_token,
        }
        self.robots = result.raw.get("robots", {})
        # NEW (this session, prompted by a real "onboarding is slow" field
        # report): the full LoginResult object, kept alongside the
        # already-extracted pieces above rather than discarded. Lets a
        # caller (config_flow.py, specifically) hand this exact result to
        # PrimeFactory.create_prime_robot()'s new login_result= parameter
        # moments later during the same onboarding run, instead of
        # triggering a second, fully redundant Gigya+iRobot login chain.
        # See config_flow.py's _async_create_prime_entry() and
        # __init__.py's _async_setup_entry_prime() for the actual
        # bridging logic -- this attribute only makes the data available,
        # it doesn't do any caching itself.
        self.login_result = result

        _LOGGER.info("iRobot cloud: authenticated, %d robot(s) found", len(self.robots))
        _LOGGER.debug(
            "iRobot cloud: robots dict — keys=%s  first_robot=%s",
            sorted(self.robots.keys()),
            next(iter(self.robots.values()), {}),
        )

    # ── Authenticated requests ─────────────────────────────────────────────────

    async def _aws_get(
        self, url: str, params: dict[str, Any] | None = None, *, _retry: bool = True
    ) -> Any:
        """GET url with AWS SigV4 signing. Reauthenticates once on 403."""
        if not self._credentials:
            raise AuthenticationError("Not authenticated — call authenticate() first")

        region = self._credentials["CognitoId"].split(":")[0]
        parsed = urllib.parse.urlparse(url)
        signer = _AWSSignatureV4(
            self._credentials["AccessKeyId"],
            self._credentials["SecretKey"],
            self._credentials["SessionToken"],
        )
        headers = signer.signed_headers(
            method="GET",
            service="execute-api",
            region=region,
            host=parsed.netloc,
            path=parsed.path,
            query_params=params or {},
        )
        final_url = url
        if params:
            final_url = f"{url}?{urllib.parse.urlencode(params)}"

        try:
            async with self._session.get(final_url, headers=headers) as resp:
                if resp.status == 403 and _retry:
                    _LOGGER.debug("iRobot cloud: 403 — reauthenticating")
                    await self.authenticate()
                    return await self._aws_get(url, params, _retry=False)
                if resp.status != 200:
                    raise CloudApiError(f"Cloud request failed ({resp.status}): {url}")
                try:
                    return await resp.json()
                except aiohttp.ContentTypeError as exc:
                    # v3.3.0 REVIEW-REMAINDER — a 200 with a non-JSON body
                    # (proxy/CDN error page) must surface as the typed
                    # CloudApiError so the coordinator's F-RB-4 grace period
                    # applies, not as an untyped ClientError.
                    raise CloudApiError(f"Non-JSON cloud response: {url}") from exc
        except aiohttp.ClientSSLError as exc:
            _raise_clear_ssl_error(exc)

    # ── Public data endpoints ─────────────────────────────────────────────────

    async def get_pmaps(self, blid: str) -> list[dict[str, Any]]:
        """Return persistent map list for a robot. Each entry includes pmap_id,
        active_pmapv_id, and active_pmapv_details (regions, zones, UMF header).
        """
        url = f"{self._deployment['httpBaseAuth']}/v1/{blid}/pmaps"
        result = await self._aws_get(url, {"visible": "true", "activeDetails": "2"})
        return result if isinstance(result, list) else []

    async def get_pmap_umf(
        self, blid: str, pmap_id: str, version_id: str
    ) -> dict[str, Any]:
        """Return the Unified Map Format data for a specific pmap version."""
        url = (
            f"{self._deployment['httpBaseAuth']}/v1/{blid}"
            f"/pmaps/{pmap_id}/versions/{version_id}/umf"
        )
        return await self._aws_get(url, {"activeDetails": "2"})

    async def get_mission_history(
        self,
        blid: str,
        count: int = 100,
        before_ts: int | None = None,
    ) -> dict[str, Any]:
        """Return mission history for a robot.

        Args:
            blid:      Robot BLID.
            count:     Maximum number of records to return (default 100).
            before_ts: If set, return only records with startTime < before_ts.
                       Used by GS-QUICK to paginate deeper into history when
                       the last 100 records lack enough traversal missions.
        """
        url = f"{self._deployment['httpBaseAuth']}/v1/{blid}/missionhistory"
        params: dict[str, Any] = {
            "app_id": f"IOS-{self._app_id}",
            "filterType": "omit_quickly_canceled_not_scheduled",
            "supportedDoneCodes": "dndEnd,returnHomeEnd",
            "count": str(count),
        }
        if before_ts is not None:
            params["before"] = str(before_ts)
        return await self._aws_get(url, params)

    async def get_favorites(self) -> list[dict[str, Any]]:
        """Return user-defined favorite cleaning routines."""
        url = f"{self._deployment['httpBaseAuth']}/v1/user/favorites"
        result = await self._aws_get(url)
        return result if isinstance(result, list) else result.get("favorites", [])

    async def get_automations(self) -> dict[str, Any]:
        """Return iRobot Genius scheduling automations for the account.

        F7l — fetches /v1/user/automations discovered in rest980 source analysis.
        The data shape is unknown without a live API trace; the response is logged
        at DEBUG level on first fetch so the shape can be determined empirically.
        No entities are created from this data in v2.1 — that follows once the
        shape is confirmed.

        Returns an empty dict on any error so coordinator update is never blocked.
        """
        url = f"{self._deployment['httpBaseAuth']}/v1/user/automations"
        result = await self._aws_get(url)
        _LOGGER.debug(
            "iRobot cloud: automations response — %d item(s)",
            len(result) if isinstance(result, (dict, list)) else 0,
        )
        return result if isinstance(result, dict) else {}
