"""Cloud data coordinator for Roomba+.

Polls the iRobot cloud API once per HA session (at setup) and again whenever
a map retrain is detected via MQTT (user_pmapv_id change). Between those
events the cloud data is stable — pmaps only change when the user physically
retrains or edits room boundaries.

The coordinator is only created for MapCapability.SMART robots AND when the
user has supplied iRobot cloud credentials. All existing local-MQTT behaviour
is completely unaffected when this coordinator is absent.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio

import aiohttp
import logging
import statistics
from collections import defaultdict
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING, Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import ConfigEntryAuthFailed
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator, UpdateFailed
from homeassistant.util import dt as dt_util

from .cloud_api import AuthenticationError, CloudApiError, IrobotCloudApi
from .const import DOMAIN, SQFT_TO_M2

if TYPE_CHECKING:
    from .mission_store import MissionStore
    from .mission_archive import MissionArchive

_LOGGER = logging.getLogger(__name__)

# Cloud data changes only on mission end or map retrain — poll once per day.
# Real-time mission state comes from MQTT push (callbacks.py), not cloud.
# Post-mission cloud refresh is triggered explicitly by F4b, not by poll interval.
_CLOUD_POLL_IDLE = timedelta(hours=24)

# F-RB-4 — suppress UpdateFailed for this long after the last success.
# Avoids entity unavailability on transient cloud outages (< 2 min).
_MIN_UNAVAILABLE = timedelta(minutes=2)



def classify_mission_result(record: dict) -> str:
    """Classify a raw /missionhistory record into a canonical result string.

    Uses the v2.0 classification scheme, which is more granular than the
    v1.9 MQTT-based scheme in callbacks.py:

      "completed"          — done="done"
      "cancelled_by_user"  — done_raw="usrEnd" (user pressed stop in the app)
      "cancelled"          — done="cncl" but not user-initiated
      "error_{code}"       — done="stuck" + pauseId>0, e.g. "error_17"
      "stuck"              — done="stuck" + pauseId=0 (no specific code)
      "unknown"            — unrecognised done value, logged for analysis

    Priority: done_raw wins over done for user-cancellation detection because
    the iRobot cloud normalises "usrEnd" → "cncl" in the done field, losing
    the user-intent signal. pauseId is the authoritative error code from the
    cloud — more reliable than cleanMissionStatus.error from MQTT, which
    sometimes never arrives on 900-series firmware.

    Args:
        record: A single raw record dict from /missionhistory.

    Returns:
        Canonical result string for use in sensors and REST API.
    """
    done: str = record.get("done", "") or ""
    done_raw: str = record.get("done_raw", "") or ""
    pause_id: int = int(record.get("pauseId", 0) or 0)

    if done == "done":
        return "completed"

    if done_raw == "usrEnd":
        return "cancelled_by_user"

    if done in ("cncl",):
        return "cancelled"

    if done == "stuck":
        if pause_id > 0:
            return f"error_{pause_id}"
        return "stuck"

    # Known done values confirmed from field logs (June 2026, Roomba 980 v2.4.17):
    if done == "ok":
        # Cloud normalisation of a successful mission (alternate to "done")
        return "completed"

    if done == "full":
        # Robot stopped because the bin is full
        return "cancelled"

    if done == "bat":
        # Robot stopped due to battery depletion (failed to reach dock)
        return "error_battery"

    if done == "schErr":
        # Schedule error — robot failed to start at scheduled time.
        # pauseId 215 = schedule conflict, 216 = schedule internal error.
        if pause_id > 0:
            return f"error_{pause_id}"
        return "cancelled"

    if done == "inc":
        # Mission incomplete — robot aborted before finishing.
        # pauseId carries the error code when present (confirmed: pauseId=48
        # from CR3 debug, June 2026 — error during room navigation start).
        if pause_id > 0:
            return f"error_{pause_id}"
        return "cancelled"

    if done:
        import logging
        logging.getLogger(__name__).debug(
            "classify_mission_result: unknown done=%r done_raw=%r pauseId=%d — "
            "logging for further analysis",
            done, done_raw, pause_id,
        )
    return "unknown"


def _normalize_mission_history(raw: dict) -> dict:
    """Normalize a raw /missionhistory record into a consistent shape.

    The iRobot cloud /missionhistory endpoint (confirmed from field logs) returns
    a list of individual mission records. Each record uses iRobot-internal field
    names that differ from the local MQTT state:

      durationM  — mission duration in minutes (cleaning + recharge time)
      done       — True if mission completed successfully
      chrgs      — number of mid-mission recharges
      chrgM      — minutes spent recharging during this mission
      dirt       — dirt detection events (scrub count)
      sqft       — area cleaned this mission in sq ft (may be present)

    This function is called with the FIRST record from the list. For aggregate
    lifetime stats, the coordinator passes the full list to _aggregate_history()
    and stores those results instead.

    This single-record normalizer is kept for backward compatibility and for
    cases where the API may return a summary dict rather than a list.

    Canonical output shape:
      {
        "runtimeStats": {"sqft": int, "hr": int, "min": int},
        "bbmssn":       {"nMssn": int},
      }
    """
    if not raw:
        return {}

    runtime = raw.get("runtimeStats") or {}
    bbrun   = raw.get("bbrun") or {}
    bbmssn  = raw.get("bbmssn") or {}

    # Try legacy/accumulator paths first (some account types return summary dict)
    sqft = runtime.get("sqft") or bbrun.get("sqft")
    hr   = runtime.get("hr")   or bbrun.get("hr")
    mn   = runtime.get("min")  or bbrun.get("min")
    n_mssn = bbmssn.get("nMssn") or raw.get("nMssn")

    # iRobot individual-record format: durationM in minutes
    if hr is None and mn is None:
        duration_m = raw.get("durationM") or raw.get("doneM") or 0
        if duration_m:
            hr = int(duration_m) // 60
            mn = int(duration_m) % 60

    # sqft from individual record — only if no better source found
    # NOTE: raw["sqft"] in individual records = THIS MISSION only, not lifetime.
    # We deliberately do NOT use it here to avoid showing per-mission sqft as
    # lifetime total. The aggregate path handles lifetime correctly.
    if sqft is None:
        sqft = raw.get("sqft")  # per-mission fallback, marked in attributes

    result: dict = {}
    if sqft is not None or hr is not None or mn is not None:
        result["runtimeStats"] = {}
        if sqft is not None:
            result["runtimeStats"]["sqft"] = int(sqft)
        if hr is not None:
            result["runtimeStats"]["hr"] = int(hr)
        if mn is not None:
            result["runtimeStats"]["min"] = int(mn)
    if n_mssn is not None:
        result["bbmssn"] = {"nMssn": int(n_mssn)}

    return result


def _aggregate_history(records: list) -> dict:
    """Aggregate a list of individual mission records into totals.

    Confirmed field names from field logs (980 firmware v2.4.17-138):
      nMssn     — LIFETIME mission count (same value in every record)
      durationM — this mission duration in minutes (run + recharge time)
      runM      — actual cleaning time in minutes (excl. recharge)
      chrgM     — time spent recharging mid-mission in minutes
      chrgs     — number of mid-mission recharges
      done      — mission result string: "done" / "stuck" / other
      pauseId   — error code when done != "done" (17 = cannot find home)
      sqft      — area cleaned this mission in sq ft
      evacs     — bin evacuation count this mission
      initiator — who started the mission

    nMssn strategy: every record contains the LIFETIME mission counter at
    the time of that mission. We read it from the first record to get the
    most recent lifetime total, NOT len(records) which is just the API
    window size (~30 days).

    For running time and area we SUM across all records — these represent
    the total for the API window (not lifetime).
    """
    if not records:
        return {}

    total_min  = 0
    total_sqft = 0
    has_sqft   = False

    # nMssn is the lifetime counter embedded in each record.
    # Use the first valid record's value for the current lifetime total.
    n_mssn_lifetime = None
    for r in records:
        if isinstance(r, dict) and r.get("nMssn") is not None:
            n_mssn_lifetime = int(r["nMssn"])
            break

    # Fall back to record count if nMssn not found (older firmware)
    n_mssn = n_mssn_lifetime if n_mssn_lifetime is not None else len(records)

    for r in records:
        if not isinstance(r, dict):
            continue
        # Use runM (actual cleaning time) preferred over durationM (incl. recharge)
        # Fall back chain: runM -> durationM -> doneM
        duration_m = r.get("runM") or r.get("durationM") or r.get("doneM") or 0
        total_min += int(duration_m)
        sqft = r.get("sqft")
        if sqft is not None:
            total_sqft += int(sqft)
            has_sqft = True

    result: dict = {
        "bbmssn": {"nMssn": n_mssn},
    }
    if total_min > 0:
        result["runtimeStats"] = {
            "hr":  total_min // 60,
            "min": total_min % 60,
        }
        if has_sqft:
            result["runtimeStats"]["sqft"] = total_sqft

    return result


def _compute_daily_dirt_density(records: list[dict]) -> dict[str, float]:
    """P4 — Build a per-calendar-date median dirt density dict from raw records.

    Called once per cloud fetch; result cached on coordinator so api_views.py
    and repairs.py can read it without re-iterating the record list.

    Uses HA's configured timezone (dt_util.as_local) so dates match the
    DaySummary entries produced by MissionStore.query_by_day(), which also
    uses dt_util.as_local. Using the server OS timezone would cause a mismatch
    for users whose HA timezone differs from the server timezone.

    Returns a dict keyed by ISO date string ("2026-06-01") → median dirt/m².
    Empty when records list is empty or no record has both dirt and sqft.
    """
    by_day: dict[str, list[float]] = defaultdict(list)
    for r in records:
        if r.get("dirt") is None:
            continue
        sqft = r.get("sqft")
        if not sqft or float(sqft) <= 0:
            continue
        ts = r.get("startTime") or r.get("timestamp")
        if not ts:
            continue
        try:
            # Bug 2 fix: use HA timezone, not server local timezone
            local_dt = dt_util.as_local(datetime.fromtimestamp(int(ts), tz=UTC))
            day_str = local_dt.date().isoformat()
            by_day[day_str].append(float(r["dirt"]) / (float(sqft) * SQFT_TO_M2))
        except (ValueError, OSError):
            pass
    return {day: statistics.median(dens) for day, dens in by_day.items()}


def _parse_time_estimates(raw: list) -> dict[str, int | None]:
    """TE1 — Normalise a region's time_estimates list to {one_pass_sec, two_pass_sec}.

    Returns None for a key when:
      - confidence != "GOOD_CONFIDENCE" (insufficient cleaning history)
      - entry absent (Auto mode — robot decides passes at runtime)
      - estimate value is not an integer

    Downstream consumers check for None before using the value:
        sec = est.get("two_pass_sec") if is_two_pass else est.get("one_pass_sec")
        # sec is None → Auto mode or insufficient region history
    """
    result: dict[str, int | None] = {"one_pass_sec": None, "two_pass_sec": None}
    if not isinstance(raw, list):
        # Defensive guard: unexpected API shape (string, dict, etc.) returns both None
        return result
    for entry in raw:
        if entry.get("confidence") != "GOOD_CONFIDENCE":
            continue
        params = entry.get("params", {})
        sec = entry.get("estimate")
        if not isinstance(sec, int):
            continue
        if params.get("twoPass") is True:
            result["two_pass_sec"] = sec
        elif params.get("twoPass") is False:
            result["one_pass_sec"] = sec
    return result


class IrobotCloudCoordinator(DataUpdateCoordinator[dict[str, Any]]):
    """Coordinator for iRobot cloud data (pmaps, mission history, favorites).

    data structure after a successful update:
    {
        "pmaps": [...],          # list of pmap dicts from /pmaps
        "mission_history": {...},# from /missionhistory
        "favorites": [...],      # from /user/favorites
    }
    All keys are always present; they default to empty list/dict on error.

    For EPHEMERAL robots (980/900-series): pmaps and favorites are always
    empty lists — only missionhistory is fetched. For SMART robots all
    three endpoints are fetched.
    """

    def __init__(
        self,
        hass: HomeAssistant,
        config_entry: ConfigEntry,
        blid: str,
        username: str,
        password: str,
        has_pmaps: bool = False,
        mission_store: "MissionStore | None" = None,
        mission_archive: "MissionArchive | None" = None,
    ) -> None:
        super().__init__(
            hass,
            _LOGGER,
            name=f"iRobot cloud ({blid})",
            config_entry=config_entry,
            update_interval=_CLOUD_POLL_IDLE,
        )
        self.blid = blid
        self._has_pmaps = has_pmaps
        self._mission_store = mission_store   # CR3 — fallback source
        self._mission_archive = mission_archive  # ARC1 — v2.8.0
        country_code = (hass.config.country or "US").upper()
        self.api = IrobotCloudApi(
            username=username,
            password=password,
            session=async_get_clientsession(hass),
            country_code=country_code,
        )
        # F-RB-4 — track last successful update for failure-suppression grace period
        self._last_success_time: "datetime | None" = None
        # P4: cached per-day dirt density — populated after each successful fetch
        self.daily_dirt_density: dict[str, float] = {}
        # IA74-PMAP: pmap_id seeded from local MQTT before first cloud fetch
        self._seeded_pmap_id: str | None = None
        _LOGGER.debug(
            "iRobot cloud: using country_code=%s, has_pmaps=%s for %s",
            country_code, has_pmaps, blid,
        )

    async def _async_setup(self) -> None:
        """Authenticate once when the coordinator is first started."""
        try:
            await self.api.authenticate()
        except AuthenticationError as exc:
            raise ConfigEntryAuthFailed(
                f"iRobot cloud credentials are invalid: {exc}",
                translation_domain=DOMAIN,
                translation_key="cloud_credentials_invalid",
                translation_placeholders={"error": str(exc)},
            ) from exc
        except (CloudApiError, aiohttp.ClientError, TimeoutError) as exc:
            # v3.3.0 REVIEW-REMAINDER — transient network errors
            # (aiohttp.ClientError incl. ContentTypeError) and the 30 s
            # asyncio.timeout guard previously bypassed this handler —
            # exactly the transient class the F-RB-4 grace period below
            # was built for.
            # Transient — let HA retry via ConfigEntryNotReady pathway
            #
            # NEW (this session): translation_key added for consistency/
            # future-proofing, but currently INERT for UpdateFailed --
            # verified against homeassistant.helpers.update_coordinator's
            # actual source: it stores self.last_exception = err and
            # never reads translation_key/translation_domain anywhere.
            # No consumer renders this today. Kept anyway since the raw
            # f-string fallback is unaffected either way, and this is
            # where the fine-grained CloudApiError subclasses (SSL/
            # connection/timeout/rate-limited) actually surface.
            raise UpdateFailed(
                f"iRobot cloud setup failed: {exc}",
                translation_domain=DOMAIN,
                translation_key="cloud_temporarily_unavailable",
                translation_placeholders={"error": str(exc)},
            ) from exc

    async def _async_update_data(self) -> dict[str, Any]:
        """Fetch current cloud data for this robot."""
        result: dict[str, Any] = {
            "pmaps": [],
            "mission_history": {},
            "mission_history_raw": [],   # v2.0: full per-mission record list
            "favorites": [],
            "automations": {},           # v2.1 F7l: iRobot Genius rules (shape TBD)
            "umf": {},                   # v2.2 F9: UMF floor plan data (SMART robots)
        }
        try:
            async with asyncio.timeout(30):
                # pmaps and favorites require cap.pmaps — SMART robots only.
                # missionhistory is account-level and available for all robots.
                if self._has_pmaps:
                    result["pmaps"] = await self.api.get_pmaps(self.blid)
                    result["favorites"] = await self.api.get_favorites()
                raw_history = await self.api.get_mission_history(self.blid)
                # F7l — fetch automations endpoint; fails gracefully
                try:
                    result["automations"] = await self.api.get_automations()
                except Exception:  # noqa: BLE001
                    _LOGGER.debug(
                        "iRobot cloud: automations endpoint unavailable for %s "
                        "(endpoint may not exist for this account type)",
                        self.blid,
                    )
                    result["automations"] = {}
        except AuthenticationError as exc:
            raise ConfigEntryAuthFailed(
                f"iRobot cloud authentication failed: {exc}",
                translation_domain=DOMAIN,
                translation_key="cloud_credentials_invalid",
                translation_placeholders={"error": str(exc)},
            ) from exc
        except (CloudApiError, aiohttp.ClientError, TimeoutError) as exc:
            # v3.3.0 REVIEW-REMAINDER — transient network errors
            # (aiohttp.ClientError incl. ContentTypeError) and the 30 s
            # asyncio.timeout guard previously bypassed this handler —
            # exactly the transient class the F-RB-4 grace period below
            # was built for.
            # F-RB-4 — suppress transient failures within the grace period.
            # Return the last known good data so entities stay available.
            if (
                self._last_success_time is not None
                and self.data is not None
                and (datetime.now(UTC) - self._last_success_time) < _MIN_UNAVAILABLE
            ):
                _LOGGER.debug(
                    "iRobot cloud: transient failure within grace period — "
                    "returning last data for %s (%s)",
                    self.blid, exc,
                )
                return self.data
            raise UpdateFailed(
                f"iRobot cloud update failed: {exc}",
                translation_domain=DOMAIN,
                translation_key="cloud_temporarily_unavailable",
                translation_placeholders={"error": str(exc)},
            ) from exc

        # F-RB-4 — stamp last success time for future failure-suppression checks.
        self._last_success_time = datetime.now(UTC)

        # The /missionhistory endpoint returns a list of records.
        # Structure varies by firmware/region:
        #   - Some accounts: list where [0] is a lifetime accumulator dict
        #     with runtimeStats.sqft/hr/min and bbmssn.nMssn
        #   - Some accounts: list of individual mission records where lifetime
        #     totals are in bbrun.sqft/hr and bbmssn.nMssn
        #   - Some firmware: a single dict directly
        # We log the raw structure at DEBUG level so users can report issues.
        if isinstance(raw_history, list) and raw_history:
            _first  = raw_history[0] if isinstance(raw_history[0], dict) else {}
            _second = (
                raw_history[1] if len(raw_history) > 1 and isinstance(raw_history[1], dict)
                else {}
            )

            # field_coverage: count of records containing each key.
            # array_stats: min/max element count + first-element shape per array key.
            # nested_keys: sub-keys one level deep for dict-valued fields.
            _all_keys: set[str] = set()
            _field_coverage: dict[str, int] = {}
            _array_stats: dict[str, dict] = {}
            _nested_keys: dict[str, set] = {}

            for _r in raw_history:
                if not isinstance(_r, dict):
                    continue
                _all_keys.update(_r.keys())
                for _k, _v in _r.items():
                    _field_coverage[_k] = _field_coverage.get(_k, 0) + 1
                    if isinstance(_v, list) and _v:
                        _s = _array_stats.setdefault(_k, {"min": len(_v), "max": 0})
                        _s["min"] = min(_s["min"], len(_v))
                        _s["max"] = max(_s["max"], len(_v))
                        if "first_element" not in _s:
                            _s["first_element"] = _v[0]
                    elif isinstance(_v, dict) and _v:
                        _nested_keys.setdefault(_k, set()).update(_v.keys())

            _n = len([_r for _r in raw_history if isinstance(_r, dict)])
            _coverage_summary = {
                _k: f"{_field_coverage[_k]}/{_n}"
                for _k in sorted(_all_keys)
            }

            _LOGGER.debug(
                "iRobot cloud: raw_history len=%d\n"
                "  field_coverage: %s\n"
                "  array_stats: %s\n"
                "  nested_keys: %s\n"
                "  first_record: %s\n"
                "  second_record: %s\n"
                "  for %s",
                len(raw_history),
                _coverage_summary,
                _array_stats,
                {_k: sorted(_v) for _k, _v in _nested_keys.items()},
                _first,
                _second,
                self.blid,
            )
        elif isinstance(raw_history, dict):
            _first = raw_history
            _LOGGER.debug(
                "iRobot cloud: raw_history dict_record=%s for %s",
                raw_history, self.blid,
            )
        else:
            _first = {}
            _LOGGER.debug(
                "iRobot cloud: raw_history unexpected type=%s for %s",
                type(raw_history).__name__, self.blid,
            )

        if isinstance(raw_history, list):
            if raw_history:
                # Store raw per-mission records for v2.0 sensors and REST API.
                # Each record preserves all 28 confirmed fields from the API
                # (startTime, timestamp, sqft, done, done_raw, pauseId, wlBars, etc.)
                # A pre-computed "classified_result" field is added so consumers
                # don't need to call classify_mission_result() themselves.
                result["mission_history_raw"] = [
                    {**r, "classified_result": classify_mission_result(r)}
                    for r in raw_history
                    if isinstance(r, dict)
                ]
                # ARC1 (v2.8.0) — delta-update the persistent mission archive.
                # Process reversed (oldest first) so _last_nMssn advances correctly.
                # async_delta_update skips duplicates via _archived_nmssns.
                if self._mission_archive is not None:
                    for _r in reversed(result["mission_history_raw"]):
                        await self._mission_archive.async_delta_update(
                            _r, self.hass, self.config_entry.entry_id
                        )
                # Aggregate ALL records for lifetime totals.
                result["mission_history"] = _aggregate_history(raw_history)
                _LOGGER.debug(
                    "iRobot cloud: aggregated %d mission records -> "
                    "nMssn=%s hr=%s sqft=%s for %s",
                    len(raw_history),
                    result["mission_history"].get("bbmssn", {}).get("nMssn"),
                    result["mission_history"].get("runtimeStats", {}).get("hr"),
                    result["mission_history"].get("runtimeStats", {}).get("sqft"),
                    self.blid,
                )
            else:
                result["mission_history"] = {}
                result["mission_history_raw"] = []
        elif isinstance(raw_history, dict):
            # Some account types may return a summary dict directly.
            result["mission_history"] = _normalize_mission_history(raw_history)
        else:
            result["mission_history"] = {}
            _LOGGER.warning(
                "iRobot cloud: unexpected mission_history type %s for %s",
                type(raw_history).__name__, self.blid,
            )

        # Log pmap structure to answer: does activeDetails=2 embed polygon
        # geometry, or does that require the separate /umf endpoint?
        for _p in result["pmaps"]:
            _det = _p.get("active_pmapv_details") or {}
            _pmapv = _det.get("active_pmapv") or {}
            _regions = _det.get("regions", [])
            # Determine which key holds the region ID — critical for CR4 attributes.
            # The API uses "region_id" in some account types, "id" in others.
            _rid_key = "region_id" if _regions and "region_id" in _regions[0] else "id"
            _LOGGER.debug(
                "iRobot cloud: pmap_id=%s  pmapv_keys=%s  "
                "region_count=%d  zone_count=%d  "
                "region_id_key=%s  first_region_keys=%s  map_header_keys=%s",
                _pmapv.get("pmap_id"),
                sorted(_pmapv.keys()),
                len(_regions),
                len(_det.get("zones", [])),
                _rid_key,
                sorted(_regions[0].keys()) if _regions else [],
                sorted((_det.get("map_header") or {}).keys()),
            )
            # v2.4.2 — log time_estimates value to confirm structure for
            # mission progress feature (v2.6.0 roadmap). Only logged once
            # per coordinator fetch to avoid log spam.
            if _regions:
                _LOGGER.debug(
                    "iRobot cloud: first region time_estimates=%s",
                    _regions[0].get("time_estimates"),
                )

        _LOGGER.debug(
            "iRobot cloud: fetched %d pmap(s), %d favorite(s) for %s (has_pmaps=%s)",
            len(result["pmaps"]),
            len(result["favorites"]),
            self.blid,
            self._has_pmaps,
        )

        # F9 / F22a — fetch UMF floor plan for SMART robots with active pmaps.
        # Skips gracefully on any error — map data is non-critical.
        if self._has_pmaps and result["pmaps"]:
            try:
                umf_data = await self._fetch_active_umf(result["pmaps"])
                if umf_data:
                    result["umf"] = umf_data
                    _LOGGER.debug(
                        "iRobot cloud: UMF fetched — keepoutzones=%d "
                        "observed_zones=%d points2d=%d for %s",
                        len(umf_data.get("keepoutzones", [])),
                        len(umf_data.get("observed_zones", [])),
                        len(umf_data.get("points2d", [])),
                        self.blid,
                    )
            except Exception:  # noqa: BLE001
                _LOGGER.debug(
                    "iRobot cloud: UMF fetch failed for %s — "
                    "obstacle data unavailable this cycle",
                    self.blid,
                )

        # CR3 — when cloud mission history is empty but MissionStore has enriched
        # records (from a previous successful cloud fetch + merge), serve them as
        # raw_records fallback so CloudRawSensor entities remain available.
        if not result["mission_history_raw"] and self._mission_store is not None:
            fallback = [
                r for r in self._mission_store.records
                if any(r.get(f) is not None for f in ("dirt", "chrgM", "wlBars"))
            ]
            if fallback:
                result["mission_history_raw"] = list(reversed(fallback))
                _LOGGER.debug(
                    "iRobot cloud: CR3 fallback — serving %d enriched "
                    "MissionStore record(s) as raw_records for %s",
                    len(fallback), self.blid,
                )

        # P4: compute and cache per-day dirt density from the final record list.
        # Stored as self.daily_dirt_density so api_views.py and repairs.py can
        # read it without re-iterating the record list on every request.
        self.daily_dirt_density = _compute_daily_dirt_density(
            result["mission_history_raw"]
        )

        return result

    # ── Helpers used by platforms ─────────────────────────────────────────────

    @property
    def last_success_time(self) -> "datetime | None":
        """Return the timestamp of the last successful cloud refresh.

        v2.8.3 (CLOUD-STALE) — exposed so repairs.async_check_cloud_stale()
        can determine how long ago the coordinator last fetched live data.
        None when no successful refresh has occurred yet in this HA session.
        """
        return self._last_success_time

    @property
    def raw_records(self) -> list[dict[str, Any]]:
        """Return the raw per-mission records from the last /missionhistory fetch.

        Records are ordered newest-first (as returned by the API).
        Each record contains all confirmed fields: startTime, timestamp, sqft,
        done, done_raw, pauseId, wlBars, runM, chrgs, evacs, dirt, initiator, etc.

        Returns an empty list when no cloud data is available or the API
        returned an empty/non-list response.
        """
        if not self.data:
            return []
        return self.data.get("mission_history_raw", [])

    @property
    def active_pmap_id(self) -> str | None:
        """Return the pmap_id of the currently active Smart Map.

        v2.7.4 (PMAP-NEWEST): selects the pmap whose user_pmapv_id timestamp
        is most recent — that is the map the robot has been actively using and
        updating after each cleaning run.  The cloud API returns all maps for
        an account without a guaranteed ordering; for robots with multiple Smart
        Maps (e.g. two-storey homes or after a map retrain), returning the first
        entry silently picks the wrong map.

        Lexicographic comparison of YYMMDDTHHMMSS strings is sufficient since
        the format is fixed-width and zero-padded.

        Falls back to _seeded_pmap_id (set from local MQTT) when no cloud data
        is available (pre-first-fetch window).
        """
        if not self.data:
            return getattr(self, "_seeded_pmap_id", None)
        best_pid: str | None = None
        best_ts: str = ""
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details") or {}
            pmapv = details.get("active_pmapv") or {}
            pid = pmapv.get("pmap_id")
            if not pid:
                continue
            ts: str = (
                pmapv.get("last_user_pmapv_id", "")   # Variant B — lewis 22.52.x
                or pmapv.get("active_pmapv_id", "")   # Variant A
                or pmap.get("active_pmapv_id", "")    # Variant C — root level (ia74 / older fw)
            )
            if ts > best_ts:
                best_pid = pid
                best_ts = ts
        return best_pid or getattr(self, "_seeded_pmap_id", None)

    @property
    def active_user_pmapv_id(self) -> str | None:
        """Return the user_pmapv_id (map version) for the active pmap.

        This is the version token the robot requires in start commands that
        target specific rooms (vacuum.clean_area, clean_room). Sourced from
        cloud data which is always authoritative — local MQTT pmaps may be
        stale for lewis firmware robots that do not broadcast pmaps updates.

        Tries three cloud API variants in order (same logic as UMF fetch):
          Variant A: active_pmapv_details.active_pmapv.active_pmapv_id
          Variant B: active_pmapv_details.active_pmapv.last_user_pmapv_id
                     (confirmed for lewis 22.52.10, veronoicc + Thonno)
          Variant C: pmap root-level active_pmapv_id (ia74 fallback)
        """
        if not self.data:
            return None
        active_id = self.active_pmap_id
        if not active_id:
            return None
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details") or {}
            pmapv = details.get("active_pmapv") or {}
            pmap_id_candidate = pmapv.get("pmap_id") or pmap.get("pmap_id")
            if pmap_id_candidate != active_id:
                continue
            return (
                pmapv.get("active_pmapv_id")       # Variant A
                or pmapv.get("last_user_pmapv_id") # Variant B (lewis 22.52.10)
                or pmap.get("active_pmapv_id")     # Variant C
            ) or None
        return None

    @property
    def learning_percentage(self) -> int | None:
        """IA74-LP (v2.6.0): Return map learning_percentage from the active pmap.

        This is the SMART map's own completeness score (0–100). Exposed as a
        SensorDeviceClass.MEASUREMENT sensor. Gate: SMART + cloud only.
        Returns None when no data or the field is absent.
        """
        if not self.data:
            return None
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details") or {}
            pct = (details.get("map_header") or {}).get("learning_percentage")
            if pct is not None:
                try:
                    return int(pct)
                except (TypeError, ValueError):
                    pass
        return None

    def seed_pmap_id_from_local(self, reported_state: dict) -> None:
        """IA74-PMAP — Seed active_pmap_id from local MQTT pmaps field on startup.

        Called once in async_setup_entry after the robot connects, before the
        first cloud fetch.  Only seeds when coordinator data is None so it
        never overrides real cloud data.

        v2.7.5 (SEED-FIX): iterates all pmaps and picks the one with the
        newest pmapv timestamp, mirroring the cloud-side active_pmap_id logic.
        Previously took pmaps[0] unconditionally; on multi-map robots the list
        is ordered oldest-first, so the inactive map was seeded and used until
        the first cloud fetch completed.

        Args:
            reported_state: the reported section of the robot's MQTT state.
        """
        if self.data is not None:
            return   # cloud data already present — don't override
        pmaps: list[dict] = reported_state.get("pmaps", [])
        if not pmaps:
            return
        best_pid: str | None = None
        best_ts: str = ""
        for p in pmaps:
            if not isinstance(p, dict):
                continue
            pid = next(iter(p), None)
            ts  = p.get(pid, "") if pid else ""
            if pid and ts > best_ts:
                best_pid = pid
                best_ts  = ts
        if best_pid:
            self._seeded_pmap_id = best_pid
            _LOGGER.debug(
                "iRobot cloud: seeded active_pmap_id=%s from local MQTT "
                "(pmapv=%s, %d map(s)) for %s",
                best_pid, best_ts, len(pmaps), self.blid,
            )

    @property
    def regions(self) -> list[dict[str, Any]]:
        """Return regions from the ACTIVE pmap only.

        Deliberately ignores disabled/old maps to prevent room-name collisions
        when multiple Smart Maps exist in the same iRobot account. A user with
        an old disabled map and a current map that share room names would
        otherwise get silent wrong-map cleans (Case 1) or rooms_different_floors
        errors (Case 2) from _resolve_rooms.
        """
        if not self.data:
            return []
        active_id = self.active_pmap_id
        if not active_id:
            return []
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details") or {}
            pmapv = details.get("active_pmapv") or {}
            if pmapv.get("pmap_id") != active_id:
                continue  # skip disabled / inactive maps
            regions_raw = details.get("regions", [])
            if not regions_raw:
                return []
            # The iRobot pmaps API uses "region_id" as the identifier key
            # in some account/firmware variants, and "id" in others.
            # Try both to be robust — confirmed as a real divergence from
            # live debug data (June 2026): first_region_keys determines which
            # is present. An empty id silently breaks CR4 attribute generation.
            def _rid(r: dict) -> str:
                return str(r.get("region_id") or r.get("id") or "")

            return [
                {
                    "id":             _rid(region),
                    "name":           region.get("name", ""),
                    "region_type":    region.get("region_type", "default"),
                    "pmap_id":        active_id,
                    "time_estimates": _parse_time_estimates(
                        region.get("time_estimates") or []
                    ),
                }
                for region in regions_raw
                if _rid(region)   # skip entries with no resolvable ID
            ]
        return []

    @property
    def zones(self) -> list[dict[str, Any]]:
        """Return custom zones from the ACTIVE pmap only.

        Same active-map filter as regions — prevents stale zone data from
        disabled maps contaminating zone_data lookups.
        """
        if not self.data:
            return []
        active_id = self.active_pmap_id
        if not active_id:
            return []
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details") or {}
            pmapv = details.get("active_pmapv") or {}
            if pmapv.get("pmap_id") != active_id:
                continue
            zones_raw = details.get("zones", [])
            if not zones_raw:
                return []

            def _zid(z: dict) -> str:
                return str(z.get("zone_id") or z.get("id") or "")

            return [
                {
                    "id":        _zid(zone),
                    "name":      zone.get("name", ""),
                    "zone_type": zone.get("zone_type", "default"),
                    "pmap_id":   active_id,
                }
                for zone in zones_raw
                if _zid(zone)
            ]
        return []

    # ── v2.2.0 UMF properties (F9 / F22a) ────────────────────────────────────

    @property
    def zone_counts(self) -> dict[str, int]:
        """IA74-ZONE (v2.6.0) — count clean zones, keepout zones, observed zones.

        Returns dict with keys: clean, keepout, observed.
        Used by ZoneSummarySensor to surface a high-level map health overview.
        """
        return {
            "clean":    len(self.zones),
            "keepout":  len(self.keepout_zones),
            "observed": len(self.observed_zone_centroids),
        }

    @property
    def zone_id_set(self) -> set[str]:
        """IA74-ZONE full (v2.7.0) — return set of clean zone IDs from active pmap.

        Used by async_clean_segments to distinguish zone segments (zid type)
        from room segments (rid type) when processing CLEAN_AREA segment IDs.
        """
        return {z["id"] for z in self.zones if z.get("id")}

    @property
    def umf_data(self) -> dict[str, Any]:
        """Return the most recently fetched UMF data, or empty dict."""
        if not self.data:
            return {}
        return self.data.get("umf", {})

    @property
    def keepout_zones(self) -> list[dict[str, Any]]:
        """Return keep-out zones from the active UMF floor plan."""
        return self.umf_data.get("keepoutzones", [])

    @property
    def region_suggestions(self) -> list[dict[str, Any]]:
        """v3.2.0 ROOM-TYPE-SUGGEST — iRobot's own ML room-type classifier
        output from the active UMF floor plan: [{"region_id": str,
        "suggested_types": [{"region_type": str, "score": float}, ...]}].
        Confirmed field shape from a real captured pmap (see
        MISSIONSTORE_FIELD_REGISTRY.md) — reliability across many pmaps
        beyond that one sample is unconfirmed, hence the conservative
        score-gating in sensor.py's id_to_display_name()."""
        return self.umf_data.get("region_suggestions", [])

    @property
    def observed_zone_centroids(self) -> list[dict[str, Any]]:
        """Return observed obstacle zone centroids for GridStore seeding.

        Coordinates are in UMF units (space='umf' tag). Not used for pose-space
        rendering until Q6 coordinate units are confirmed in v2.3.
        """
        centroids = []
        for z in self.umf_data.get("observed_zones", []):
            cx = z.get("cx") or z.get("centroid_x") or z.get("x")
            cy = z.get("cy") or z.get("centroid_y") or z.get("y")
            if cx is not None and cy is not None:
                centroids.append({"x": cx, "y": cy, "space": "umf"})
        return centroids

    async def _fetch_active_umf(
        self, pmaps: list[dict]
    ) -> dict[str, Any] | None:
        """Fetch UMF floor plan for the active pmap.

        Returns a dict with keys:
          keepoutzones:   list of keep-out zone dicts (with centroid coords)
          observed_zones: list of robot-learned obstacle dicts (with centroids)
          points2d:       list of wall boundary points (for F8 UmfAligner, v2.3)
          pmap_id:        the pmap_id this UMF belongs to
          version_id:     the pmap version fetched

        Coordinate space: UMF units (Q6 open — store with space='umf' tag,
        do not use for pose-space rendering until Q6 confirmed in v2.3).

        Returns None when no active pmap or UMF fetch fails.
        """
        # Resolve active_pmap_id directly from the pmaps list passed in.
        # Do NOT use self.active_pmap_id here — that reads self.data which is
        # None during the first _async_update_data call (HA only sets self.data
        # after a successful return). Using self.data would always return None
        # on the first update, silently skipping the UMF fetch every startup.
        active_id: str | None = None
        for _p in pmaps:
            _pmapv = (_p.get("active_pmapv_details") or {}).get("active_pmapv") or {}
            _pid = _pmapv.get("pmap_id") or _p.get("pmap_id")
            if _pid:
                active_id = _pid
                break

        if not active_id:
            _LOGGER.debug(
                "iRobot cloud: UMF fetch skipped for %s — "
                "could not determine active_pmap_id from pmaps list",
                self.blid,
            )
            return None

        for pmap in pmaps:
            # pmap structure variants for version_id resolution.
            # Only Variant B is confirmed from live debug logs (June 2026).
            # Variant A and C are unconfirmed but not disproven — kept as
            # defensive fallbacks to avoid breaking unknown robot/firmware types.
            #
            # Variant A (unconfirmed — original v2.3.0 assumption):
            #   version_id: active_pmapv_details.active_pmapv.active_pmapv_id
            #
            # Variant B (confirmed — veronoicc + Thonno, lewis 22.52.10, June 2026):
            #   version_id: active_pmapv_details.active_pmapv.last_user_pmapv_id
            #
            # Variant C (unconfirmed — inferred from ia74/roomba_rest980 CloudApi.py):
            #   version_id: pmap["active_pmapv_id"] (root level)
            #
            # All variants use active_pmapv_details.active_pmapv.pmap_id for pmap_id
            # match, except Variant C which falls back to pmap["pmap_id"] at root.
            #
            details = pmap.get("active_pmapv_details") or {}
            pmapv   = details.get("active_pmapv") or {}

            # pmap_id match — try Variant A/B first, then Variant C
            pmap_id_candidate = pmapv.get("pmap_id") or pmap.get("pmap_id")
            if pmap_id_candidate != active_id:
                continue

            # version_id — try all three variants in order
            version_id = (
                pmapv.get("active_pmapv_id")       # Variant A
                or pmapv.get("last_user_pmapv_id") # Variant B (lewis 22.52.10)
                or pmap.get("active_pmapv_id")     # Variant C (ia74 source)
            )
            if not version_id:
                _LOGGER.debug(
                    "iRobot cloud: UMF fetch skipped for %s — "
                    "could not resolve version_id (pmapv keys: %s)",
                    self.blid, list(pmapv.keys()),
                )
                return None
            try:
                umf_raw = await self.api.get_pmap_umf(
                    self.blid, active_id, version_id
                )
            except Exception as exc:  # noqa: BLE001
                _LOGGER.debug(
                    "iRobot cloud: UMF fetch failed for %s "
                    "(pmap_id=%s version_id=%s) — %s: %s",
                    self.blid, active_id, version_id,
                    type(exc).__name__, exc,
                )
                return None

            _LOGGER.debug(
                "iRobot cloud: UMF raw response keys=%s points2d=%d "
                "keepoutzones=%d observed_zones=%d for %s",
                list(umf_raw.keys()) if isinstance(umf_raw, dict) else type(umf_raw).__name__,
                len(umf_raw.get("points2d") or []) if isinstance(umf_raw, dict) else 0,
                len(umf_raw.get("keepoutzones") or []) if isinstance(umf_raw, dict) else 0,
                len(umf_raw.get("observed_zones") or []) if isinstance(umf_raw, dict) else 0,
                self.blid,
            )

            # UMF response structure confirmed from veronoicc debug log and
            # ia74/roomba_rest980 camera.py source (June 2026):
            # Container format with keys ['format_version', 'debug_file_header', 'maps']
            # where geometry (points2d, keepoutzones, observed_zones) is in maps[].
            # UMF response structure confirmed from veronoicc debug log and
            # ia74/roomba_rest980 camera.py source (June 2026):
            # Container format — geometry and region polygons are in maps[].
            # regions in maps[] contain geometry.ids referencing points2d,
            # unlike regions from get_pmaps() which only have metadata.
            maps = umf_raw.get("maps") or []
            geo: dict[str, Any] = {
                "points2d": [], "keepoutzones": [],
                "observed_zones": [], "regions": [],
                "region_suggestions": [],   # v3.2.0 ROOM-TYPE-SUGGEST
            }
            for m in maps:
                if not isinstance(m, dict):
                    continue
                geo["points2d"].extend(m.get("points2d") or [])
                geo["keepoutzones"].extend(m.get("keepoutzones") or [])
                geo["observed_zones"].extend(m.get("observed_zones") or [])
                # Regions from UMF maps contain geometry.ids — needed by UmfAligner
                # to resolve room polygons. Regions from get_pmaps() only have metadata.
                geo["regions"].extend(m.get("regions") or [])
                # v3.2.0 ROOM-TYPE-SUGGEST — iRobot's own ML room-type
                # classifier output, confirmed present in a real captured
                # pmap (PyRoomba r.json, July 2026 — see
                # MISSIONSTORE_FIELD_REGISTRY.md). Reliability across many
                # pmaps unconfirmed (only one sample seen) — used only as
                # a conservative fallback, never overriding a user-set
                # region name. See sensor.py's id_to_display_name().
                geo["region_suggestions"].extend(m.get("region_suggestions") or [])

            _LOGGER.debug(
                "iRobot cloud: UMF parsed — "
                "%d map(s) -> points2d=%d keepoutzones=%d observed_zones=%d regions=%d for %s",
                len(maps),
                len(geo["points2d"]),
                len(geo["keepoutzones"]),
                len(geo["observed_zones"]),
                len(geo["regions"]),
                self.blid,
            )

            # RESEARCH-ROOMTYPE (v3.3.0 ROOM-TYPE-VERIFY, temporary) —
            # one-time field capture of iRobot's ML room-type classifier
            # output. Same pattern as RESEARCH-MISSIONMAP: INFO-level,
            # fires only when the debug flag file exists, no extra cloud
            # call (data is already in this response). Region names are
            # NOT logged — only ids, suggested types, and scores.
            # Remove after field verification (Thonno / veronoicc).
            if geo["region_suggestions"] or maps:
                import os as _os  # noqa: PLC0415 — temporary research block
                if _os.path.exists(self.hass.config.path("roomba_plus_research_roomtype")):
                    _LOGGER.info(
                        "RESEARCH-ROOMTYPE %s: pmap=%s maps=%d "
                        "suggestions=%s",
                        self.blid,
                        active_id,
                        len(maps),
                        [
                            {
                                "region_id": s.get("region_id"),
                                "suggested_types": s.get("suggested_types"),
                            }
                            for s in geo["region_suggestions"]
                        ] or "EMPTY",
                    )

            return {
                "keepoutzones": [
                    {**z, "space": "umf"}
                    for z in geo["keepoutzones"]
                ],
                "observed_zones": [
                    {**z, "space": "umf"}
                    for z in geo["observed_zones"]
                ],
                "points2d":   geo["points2d"],
                "regions":    geo["regions"],
                "region_suggestions": geo["region_suggestions"],   # v3.2.0 ROOM-TYPE-SUGGEST
                "pmap_id":    active_id,
                "version_id": version_id,
            }
        return None
