"""Mission Store for Roomba+ — append-only mission history log.

Persists up to 365 mission records per robot, keyed by config entry ID.
Provides query, aggregation, and window-analysis methods consumed by
L1 sensors, L3 error intelligence, L6 presence analytics, and the
REST API view.

No HA dependencies at import time — fully unit-testable without stubs.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
import statistics
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from typing import Any, NamedTuple

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store
from homeassistant.util import dt as dt_util

from .const import SQFT_TO_M2

_LOGGER = logging.getLogger(__name__)

STORAGE_KEY_PREFIX = "roomba_plus_missions"
STORAGE_VERSION = 1
MAX_RECORDS = 365


class BackfillResult(NamedTuple):
    """Result of backfill_from_cloud()."""
    corrected: int  # records where timestamps were corrected (delta > 300s)
    enriched: int   # records where analytics fields were merged


# Cloud → local field merge lists for backfill_from_cloud().
# Scalar fields: copied when local value is absent (None or missing).
_CLOUD_MERGE_SCALAR: tuple[str, ...] = (
    "chrgM",     # recharge minutes — F5c source
    "dirt",      # dirt events — F5b source
    "sqft",      # raw area (area_sqft is the canonical local name)
    "runM",      # actual cleaning minutes (excl. recharge)
    "durationM", # total mission minutes
    "chrgs",     # mid-mission recharge count
    "evacs",     # bin evacuations
    "nMssn",     # lifetime mission counter at this mission
    "timeline",  # full mission event log (dict: plan + finEvents) — CR4 source
                 # Field confirmed as 'timeline' from CR3 debug (June 2026).
                 # Contains plan.upcoming (planned room order) and finEvents
                 # (room/travel/traversal/evac/charge events per room).
                 # dict, not a list — lives in _CLOUD_MERGE_SCALAR, not ARRAY.
    # Amendment 8f — confirmed useful from Thonno's 75-record dataset (June 2026)
    "dockedAtStart",  # bool  — was robot docked at mission start?
    "missionId",      # str   — cloud ULID, stable dedup key across reboots
    "pauseM",         # int   — minutes spent paused (non-charging, non-cleaning)
    "cmd",            # dict  — full start command incl. per-room twoPass params
)

# Array fields: copied when local value is absent or empty list.
_CLOUD_MERGE_ARRAY: tuple[str, ...] = (
    "wlBars",    # per-mission WiFi signal histogram (5-element) — F1 source
                 # startEndWlBars (scalar bar-strength at start/end) is a
                 # separate top-level field; not merged (redundant with wlBars).
    "pmaps_info",  # v3.3.0 MISSION-MAP — [{pmap_id, pmapv_id, ...}] of THIS
                   # mission; the key to the mission-specific UMF version
                   # whose layers carry the coverage coordinates. Field
                   # confirmed in PyRoomba sample + boutXIII field data.
)


@dataclass(frozen=True)
class DaySummary:
    """Aggregated mission stats for a single calendar day."""

    date: date
    total: int
    completed: int
    stuck: int
    area_sqft: float | None   # sum for day; None if 600-series
    result: str               # dominant: "stuck" > "error" > "completed" > "cancelled" > "none" (v3.2.1 order; error matches error_* variants)
    dirt_density: float | None = None  # F12b — median dirt events/m² for day; None without cloud


@dataclass(frozen=True)
class MissionWindow:
    """A gap between two consecutive missions — potential all-away window."""

    started_at: datetime
    ended_at: datetime
    duration_min: int
    resulted_in_clean: bool   # True if a completed mission started within this window


class MissionStore:
    """Append-only mission log — max 365 records FIFO.

    Lifecycle (must be respected by callers):
      - Instantiate in async_setup_entry.
      - Call async_load() immediately after instantiation.
      - Store in entry.runtime_data.mission_store.
      - No active listeners — no cancel/unload cleanup required.
    """

    def __init__(self) -> None:
        self._records: list[dict[str, Any]] = []
        # v2.8.0 L3-ARC — archive-computed stats dict injected at startup.
        # Provides a stable baseline for consecutive_anomalous when local
        # records are insufficient (< 20 missions).  Not persisted — computed
        # fresh from MissionArchive each time async_setup_entry runs.
        self.archive_baseline: dict | None = None
        # v3.3.0 STORE-ENCAP — lazy full-history id index for
        # append_validated(). None until first use; kept in sync by all
        # append paths afterwards. Not persisted (rebuilt on demand).
        self._record_ids: set[str] | None = None

    # ── Public read API (v3.3.0 STORE-ENCAP) ────────────────────────────────

    @property
    def records(self) -> Sequence[dict[str, Any]]:
        """Read-only view of all mission records, oldest first.

        v3.3.0 STORE-ENCAP — the canonical cross-module read access.
        Do NOT mutate the returned sequence or its dicts; use
        async_append (MQTT path) or append_validated (import path)
        so the MAX_RECORDS/dedup invariants stay in one place.
        Zero-copy by design (hot path in sensor filter_fns); the
        encapsulation guard test enforces the read-only contract.
        """
        return self._records

    # ── Persistence ───────────────────────────────────────────────────────────

    async def async_load(self, hass: HomeAssistant, entry_id: str) -> None:
        """Load persisted records from hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        data: dict | None = await store.async_load()
        if not data:
            _LOGGER.debug("MissionStore: no persisted data for %s", entry_id)
            return
        try:
            self._records = list(data.get("records", []))
            _LOGGER.debug("MissionStore: loaded %d record(s) for %s", len(self._records), entry_id)
        except (TypeError, ValueError) as exc:
            _LOGGER.warning("MissionStore: failed to load — %s; starting empty", exc)
            self._records = []

    async def async_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Persist current records to hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        await store.async_save({"records": self._records})

    # ── Write ─────────────────────────────────────────────────────────────────

    async def async_append(self, record: dict[str, Any]) -> None:
        """Append a record and trim to MAX_RECORDS FIFO.

        F4c — duplicate guard: drops records whose id matches a recent record
        with the same ended_at (= true MQTT re-delivery of the same event).

        v2.6.3 B3 — multi-recharge missions: the 980 firmware keeps the original
        mssnStrtTm across all charging segments, so Segment 2 and Segment 3 of
        a 3-segment mission would share the same record id as Segment 1 and be
        silently dropped by the original guard.  The fix: only drop when BOTH
        id AND ended_at match (true duplicate).  When only the id matches (same
        start_ts, different end = subsequent segment), assign a unique id by
        appending "_r<N>" before storing.
        """
        record_id = record.get("id")
        if record_id:
            for existing in self._records[-5:]:
                if existing.get("id") == record_id:
                    if existing.get("ended_at") == record.get("ended_at"):
                        # True MQTT re-delivery — same start AND same end
                        _LOGGER.debug(
                            "MissionStore: duplicate record %s dropped (MQTT re-delivery)",
                            record_id,
                        )
                        return
                    # Same start_ts, different end = subsequent recharge segment.
                    # Give it a unique id so it is stored alongside segment 1.
                    seg_n = sum(
                        1 for r in self._records
                        if r.get("id", "").startswith(record_id)
                    )
                    record = {**record, "id": f"{record_id}_r{seg_n}"}
                    _LOGGER.debug(
                        "MissionStore: multi-recharge segment stored as %s",
                        record["id"],
                    )
                    break
        self._records.append(record)
        if self._record_ids is not None and record.get("id"):
            self._record_ids.add(record["id"])
        self._trim()

    def append_validated(self, record: dict[str, Any]) -> bool:
        """Append with FULL-history id dedup + MAX_RECORDS trim.

        v3.3.0 STORE-ENCAP — the import path (REST mission-history
        import). Differs from async_append (the MQTT path) on purpose:
        - dedup checks the ENTIRE history, not a 5-record window
          (imports may contain records older than the window)
        - no recharge-segment "_r<N>" id splitting (imported records
          are final, not live MQTT segments)

        Returns False (and stores nothing) when the record has no
        string id or the id already exists. Does NOT save — callers
        batch a single async_save after the import loop.
        """
        record_id = record.get("id")
        if not record_id or not isinstance(record_id, str):
            return False
        if self._record_ids is None:
            self._record_ids = {
                r["id"] for r in self._records
                if isinstance(r.get("id"), str)
            }
        if record_id in self._record_ids:
            return False
        self._records.append(record)
        self._record_ids.add(record_id)
        self._trim()
        return True

    def _trim(self) -> None:
        """Enforce the MAX_RECORDS FIFO invariant — single home for it
        (v3.3.0 STORE-ENCAP; previously rebuilt ad hoc by the import
        endpoint, the documented bug source)."""
        if len(self._records) > MAX_RECORDS:
            self._records = self._records[-MAX_RECORDS:]
            # Ids may have been trimmed away — invalidate, rebuilt lazily.
            self._record_ids = None

    # ── Read ──────────────────────────────────────────────────────────────────

    def latest(self) -> dict[str, Any] | None:
        """Return the most recent record, or None."""
        return self._records[-1] if self._records else None

    def find_by_id(self, mission_id: str) -> dict[str, Any] | None:
        """v3.2.0 ANOMALY-EXPLAIN — look up a specific record by its
        `id` field (the "m_{unix_start_ts}" format used throughout this
        store) OR its `missionId` field (the cloud ULID, present on
        records enriched via backfill_from_cloud() — see
        _CLOUD_MERGE_SCALAR). v3.3.1 fix: previously only checked `id`,
        contradicting the documented contract ("the record's id field
        ... or the cloud missionId ULID — both resolve") — missionId
        never actually matched anything. Linear scan — record counts
        are bounded (MAX_RECORDS), so this is not a hot path worth
        indexing."""
        for record in self._records:
            if record.get("id") == mission_id or record.get("missionId") == mission_id:
                return record
        return None

    _ANOMALY_RECOMMENDATIONS: dict[str, str] = {
        "obstacle_or_blockage": (
            "Check for cords, rugs, or furniture the robot may have gotten "
            "stuck on or struggled to navigate around."
        ),
        "excessive_recharge": (
            "Battery may be degrading — check the battery capacity retention "
            "sensor, or the robot may be having trouble finding its dock."
        ),
        "dirt_spike": (
            "An unusually dirty area was detected — check for a spill, "
            "tracked-in debris, or a pet accident."
        ),
        "incomplete_coverage": (
            "The robot covered noticeably less area than expected for a "
            "typical mission — check whether a door was closed or a room "
            "was inaccessible."
        ),
    }

    def explain_mission(
        self,
        mission_id: str | None = None,
        record_override: dict[str, Any] | None = None,
    ) -> dict[str, Any] | None:
        """v3.2.0 ANOMALY-EXPLAIN — shared explanation-assembly logic used
        by both the explain_mission service (services.py) and its REST
        counterpart (api_views.py), so the two never drift out of sync.

        mission_id=None defaults to the most recent mission (whether
        anomalous or not — is_anomalous in the result tells the caller
        which case it is, so this doubles as a general "explain the last
        mission" call).

        record_override (v3.3.1, cloud-source Explain): when given, used
        directly as the record instead of looking one up via find_by_id()/
        latest() — mission_id is ignored in that case except as the
        result's echoed "mission_id" (read from record_override itself).
        This is how callers resolve a cloud-only synthetic id (e.g.
        "c_{ts}", which never exists in this store's _records) without
        MissionStore needing any knowledge of cloud_coordinator — the
        caller (api_views.py) does that resolution and hands over a
        plain record dict shaped for this method's field expectations
        (duration_min, area_sqft, dirt, error_code — see
        _cloud_record_to_explain_input() in api_views.py). recharge_min
        and npicks_delta are local-only telemetry and are legitimately
        absent on such records — anomaly_reason()/robot_lifted below
        already treat both as optional, so this isn't a special case.

        Returns None only when no matching mission exists at all (bad
        mission_id, or empty history) — callers translate that into
        whatever's appropriate for their transport (ServiceValidationError
        for the service, 404 for the REST view).
        """
        if record_override is not None:
            record = record_override
        elif mission_id is not None:
            record = self.find_by_id(mission_id)
        else:
            record = self.latest()
        if record is None:
            return None

        stats = self.compute_rolling_stats()
        if stats is None:
            stats = self.archive_baseline   # L3-ARC fallback, same as consecutive_anomalous

        reason = self.anomaly_reason(record, stats) if stats is not None else None
        npicks_delta = record.get("npicks_delta") or 0

        return {
            "mission_id": record.get("id"),
            "is_anomalous": reason is not None,
            "anomaly_reason": reason,
            "robot_lifted": npicks_delta > 0,
            "error_code": record.get("error_code"),
            "recommended_action": self._ANOMALY_RECOMMENDATIONS.get(reason),
        }

    # All result values that represent a stuck/failure event.
    STUCK_RESULTS: frozenset[str] = frozenset({
        "stuck", "stuck_and_resumed", "stuck_and_abandoned"
    })
    ERROR_RESULTS: frozenset[str] = frozenset({
        "error", "stuck", "stuck_and_resumed", "stuck_and_abandoned"
    })

    def query(
        self,
        days: int,
        result: str | frozenset[str] | None = None,
    ) -> list[dict[str, Any]]:
        """Return records from the last `days` days, optionally filtered by result.

        ``result`` may be a single string for exact match or a frozenset of
        strings for any-of matching.  Use ``MissionStore.STUCK_RESULTS`` to
        query all stuck variants at once.

        Records are returned sorted ascending by started_at.
        """
        result_set: frozenset[str] | None = (
            None if result is None else
            result if isinstance(result, frozenset) else
            frozenset({result})
        )
        cutoff = dt_util.now() - timedelta(days=days)
        out = []
        for r in self._records:
            started = dt_util.parse_datetime(r.get("started_at", ""))
            if started is None:
                continue
            # Make started timezone-aware for comparison if needed
            if started.tzinfo is None:
                started = started.replace(tzinfo=timezone.utc)
            if started < cutoff:
                continue
            if result_set is not None and r.get("result") not in result_set:
                continue
            out.append(r)
        return sorted(out, key=lambda r: r.get("started_at", ""))

    def query_by_error(
        self,
        error_code: int,
        days: int,
        zone: str | None = None,
    ) -> list[dict[str, Any]]:
        """Return records for a specific error code in the last `days` days.

        F8b — used by the error-recurrence Repair Issue to detect ≥3 occurrences
        of the same error code in the same zone within a lookback window.

        Args:
            error_code: The integer error code to match (cleanMissionStatus.error).
            days:       Lookback window in days.
            zone:       When set, additionally filter by the first zone name.
                        Pass None to return all records regardless of zone.
        """
        results = []
        for r in self.query(days):
            if r.get("error_code") != error_code:
                continue
            if zone is not None:
                zones = r.get("zones") or []
                if not zones or zones[0] != zone:
                    continue
            results.append(r)
        return results

    def query_by_day(self, days: int) -> dict[date, DaySummary]:
        """Group query(days) results by local calendar date.

        Returns a dict keyed by date. Days with no missions are omitted.
        """
        from collections import defaultdict
        buckets: dict[date, list[dict]] = defaultdict(list)
        for r in self.query(days):
            dt = dt_util.parse_datetime(r.get("started_at", ""))
            if dt:
                buckets[dt_util.as_local(dt).date()].append(r)

        summaries: dict[date, DaySummary] = {}
        for day, records in buckets.items():
            total = len(records)
            # F6h: stuck_and_resumed counts as completed (robot finished);
            # stuck_and_abandoned counts as stuck (mission failed).
            # F6c: blocked_timeout counts as total but not completed.
            completed = sum(
                1 for r in records
                if r.get("result") in ("completed", "stuck_and_resumed")
            )
            stuck = sum(
                1 for r in records
                if r.get("result") in ("stuck", "stuck_and_abandoned")
            )
            areas = [r["area_sqft"] for r in records if r.get("area_sqft") is not None]
            area_sqft: float | None = float(sum(areas)) if areas else None
            # Dominant result: stuck > error > completed > cancelled > none
            #
            # v3.2.1 — two fixes from card-development round 2.2:
            #   1. stuck now ranks ABOVE error.  A stuck robot needs physical
            #      intervention (wedged, cliff, lost) and is the more
            #      actionable signal for the card's day cell; a coded error
            #      often self-describes and frequently self-resolves.
            #   2. error_* variants ("error_17", "error_battery",
            #      "cancelled_by_user") reach the store via the import
            #      endpoint and rest980 migration despite the local enum
            #      convention (see B1-EXT note) — the exact string match
            #      missed them, so an error_battery-only day ranked "none".
            #      Prefix-match error_*, and count cancelled_by_user under
            #      cancelled (same fall-through class of bug).
            results = {r.get("result") for r in records}
            has_error = any(
                isinstance(res, str)
                and (res == "error" or res.startswith("error_"))
                for res in results
            )
            dominant = (
                "stuck" if results & {"stuck", "stuck_and_abandoned"} else
                "error" if has_error else
                "completed" if results & {"completed", "stuck_and_resumed"} else
                "cancelled" if results & {"cancelled", "cancelled_by_user"} else
                "none"
            )
            summaries[day] = DaySummary(
                date=day,
                total=total,
                completed=completed,
                stuck=stuck,
                area_sqft=area_sqft,
                result=dominant,
            )
        return summaries

    # ── v2.2.0 CR4 — timeline room-event extraction ───────────────────────────

    def _resolve_region_ids(
        self,
        rid_list: list[str],
        region_map: dict[str, str],
    ) -> list[str]:
        """Resolve region IDs to display names via region_map.

        Unknown IDs are returned as their raw ID string — data is never
        silently dropped. Name changes in the Smart Map are reflected
        automatically since region_map is passed at read time, not stored.
        """
        return [region_map.get(rid, rid) for rid in rid_list]

    @staticmethod
    def extract_rid(item: Any) -> str:
        """Extract a region ID from a plan.upcoming entry.

        Handles two confirmed formats:
        - String (some firmware/app versions): "23"
        - Object (lewis 22.52.10+): {"type": "rid", "rid": "23"}
          Also accepts {"region_id": "23"} as a fallback.

        Returns an empty string when neither format is recognisable so the
        caller can filter it out.
        """
        if isinstance(item, dict):
            return str(item.get("rid") or item.get("region_id") or "")
        return str(item) if item is not None else ""

    # v3.3.0 STORE-ENCAP — deprecated private alias. 18 test call sites
    # still use the old name; removal earmarked for SENSOR-SPLIT (v3.4.0)
    # when those test files are touched anyway. Production code must use
    # extract_rid (enforced by the encapsulation guard test).
    _extract_rid = extract_rid

    def latest_cleaned_rooms(
        self,
        region_map: dict[str, str],
        umf_regions: dict[str, str] | None = None,
    ) -> list[str] | None:
        """Return room names in cleaning-completion order from the most recent mission.

        CR4 — uses timeline.finEvents filtered to type='room' and status in (0, 6).
        status=0 = pass complete (normal).
        status=6 = pass complete after error recovery (lewis 22.52.10+ confirmed).
        status=1 = pass in progress — excluded.
        status=5 = interrupted by user/app — excluded.
        Each room appears once; the last qualifying event per rid is used.

        umf_regions: optional fallback for EPHEMERAL robots without coordinator.regions.
        When region_map is empty and umf_regions is provided, umf_regions is used.

        Returns None for whole-home missions (no 'room' events) or when
        the timeline field is absent (non-SMART robot or pre-merge record).
        """
        effective_map = region_map if region_map else (umf_regions or {})
        latest = self.latest()
        if latest is None:
            return None
        return self._record_room_names(latest, effective_map)

    def _record_room_names(
        self,
        rec: dict[str, Any],
        effective_map: dict[str, str],
    ) -> list[str] | None:
        """Room names cleaned in ONE record, completion order.

        v3.3.0 ROOM-SCHED foundation fix — the derivation half of
        latest_cleaned_rooms(), applicable to ANY record: live records
        never carry a stored `last_cleaned_rooms` field (they carry the
        cloud-merged `timeline`), so every reader of that field only
        ever worked for IMPORTED histories. Same bug class as the
        v3.1.1 last_mission_summary fix, one level deeper — this helper
        is the single shared derivation both room_cleaning_history()
        and room_coverage_health() now use.

        Order of sources:
        1. timeline.finEvents room events, status in (0, 6) — live path
        2. rec["last_cleaned_rooms"] — imported records keep working
        """
        timeline = rec.get("timeline")
        if isinstance(timeline, dict):
            fin_events = timeline.get("finEvents") or []
            seen: dict[str, int] = {}   # rid → index in ordered list
            ordered: list[str] = []
            for ev in fin_events:
                if not isinstance(ev, dict) or ev.get("type") != "room":
                    continue
                room = ev.get("room") or {}
                if room.get("status") not in (0, 6):   # 0=complete, 6=after-recovery
                    continue
                rid = str(room.get("rid", ""))
                if not rid:
                    continue
                if rid not in seen:
                    seen[rid] = len(ordered)
                    ordered.append(rid)
            if ordered:
                return self._resolve_region_ids(ordered, effective_map)
        imported = rec.get("last_cleaned_rooms")
        if isinstance(imported, list) and imported:
            return [str(r) for r in imported if isinstance(r, str)]
        return None

    def latest_planned_order(
        self,
        region_map: dict[str, str],
        umf_regions: dict[str, str] | None = None,
    ) -> list[str] | None:
        """Return room names in user-selected submission order.

        CR4 — uses timeline.plan.upcoming. Preserves the exact order the user
        selected rooms in the iRobot app. Returns None when absent or empty.

        umf_regions: optional fallback for EPHEMERAL robots (see latest_cleaned_rooms).
        """
        effective_map = region_map if region_map else (umf_regions or {})
        latest = self.latest()
        if latest is None:
            return None
        timeline = latest.get("timeline")
        if not isinstance(timeline, dict):
            return None
        upcoming = (timeline.get("plan") or {}).get("upcoming")
        if not upcoming:
            return None
        rids = [self._extract_rid(r) for r in upcoming]
        rids = [r for r in rids if r]   # drop empty strings from unrecognised formats
        if not rids:
            return None
        return self._resolve_region_ids(rids, effective_map)

    def latest_mission_destination(
        self,
        region_map: dict[str, str],
        umf_regions: dict[str, str] | None = None,
    ) -> str | None:
        """Return the last room in the planned order (final target of the job).

        Returns None for whole-home missions or when timeline is absent.

        umf_regions: optional fallback for EPHEMERAL robots (see latest_cleaned_rooms).
        """
        planned = self.latest_planned_order(region_map, umf_regions)
        return planned[-1] if planned else None

    def latest_room_coverage(
        self,
        region_map: dict[str, str],
        umf_regions: dict[str, str] | None = None,
    ) -> dict[str, float] | None:
        """Return per-room coverage fractions from the most recent mission.

        CR4 — uses room.totalArea / room.area from status=0 and status=6 events.
        totalArea = cumulative cleaned area across all passes (status=0/6 only).
        area = full room size (constant across events for the same rid).
        Values are clamped to [0.0, 1.0].

        Note: status=6 (completed after error recovery) events may not carry
        totalArea — such rooms are skipped from coverage but still appear in
        latest_cleaned_rooms(). This is expected behaviour for v2.2.

        umf_regions: optional fallback for EPHEMERAL robots (see latest_cleaned_rooms).

        Returns None when timeline is absent or no qualifying room events.
        """
        effective_map = region_map if region_map else (umf_regions or {})
        latest = self.latest()
        if latest is None:
            return None
        timeline = latest.get("timeline")
        if not isinstance(timeline, dict):
            return None
        fin_events = timeline.get("finEvents") or []
        coverage: dict[str, float] = {}
        for ev in fin_events:
            if ev.get("type") != "room":
                continue
            room = ev.get("room", {})
            if room.get("status") not in (0, 6):   # 0=complete, 6=complete-after-recovery
                continue
            rid = str(room.get("rid", ""))
            total_area = room.get("totalArea")
            area = room.get("area")
            if not rid or total_area is None or not area:
                continue
            try:
                fraction = min(1.0, max(0.0, float(total_area) / float(area)))
            except (ZeroDivisionError, TypeError, ValueError):
                continue
            coverage[rid] = fraction
        if not coverage:
            return None
        return {effective_map.get(rid, rid): frac for rid, frac in coverage.items()}

    def room_cleaning_history(
        self,
        region_map: dict[str, str] | None = None,
        umf_regions: dict[str, str] | None = None,
    ) -> dict[str, str]:
        """Return the most recent clean timestamp per room across all records.

        Scans records newest-first; the first hit per room name wins.
        v3.3.0 ROOM-SCHED foundation fix — room names are now DERIVED per
        record via _record_room_names() (timeline.finEvents on the live
        path, stored last_cleaned_rooms for imported records). Previously
        this read only the stored field, which no live pipeline ever
        writes — the method returned {} on every non-import installation
        (same bug class as the v3.1.1 last_mission_summary fix).

        region_map/umf_regions: same name-resolution pair as
        latest_cleaned_rooms(); without them, live-path rooms resolve to
        raw region IDs (still functional for interval math, just unnamed).

        Result: ``{"Kitchen": "2026-06-29T08:45:00", "Living Room": "2026-06-27T09:10:00"}``
        """
        effective_map = region_map if region_map else (umf_regions or {})
        result: dict[str, str] = {}
        for rec in reversed(self._records):
            ended_at = rec.get("ended_at")
            # v3.2.0 full-review fix — same defence-in-depth guard as
            # room_coverage_health: a non-string ended_at (poisoned
            # import from before the api_views.py type gate) must be
            # skipped here at the SOURCE, since this method's output
            # flows into room_coverage_health's parse_datetime calls.
            if not ended_at or not isinstance(ended_at, str):
                continue
            rooms = self._record_room_names(rec, effective_map) or []
            for room in rooms:
                if room not in result:
                    result[room] = ended_at
        return result

    def room_visit_counts(
        self,
        region_map: dict[str, str] | None = None,
        umf_regions: dict[str, str] | None = None,
    ) -> dict[str, int]:
        """v3.3.0 SMART-ORDER — number of recorded cleanings per room
        across the whole local window. Public accessor (STORE-ENCAP):
        the auto_clean_dirty_rooms service uses this for its
        min-missions trust gate on the L5 dirt index."""
        effective_map = region_map if region_map else (umf_regions or {})
        counts: dict[str, int] = {}
        for rec in self._records:
            for room in self._record_room_names(rec, effective_map) or []:
                counts[room] = counts.get(room, 0) + 1
        return counts

    def rooms_overdue_merged(
        self,
        config: dict[str, str] | None,
        now_iso: str,
        region_map: dict[str, str] | None = None,
        umf_regions: dict[str, str] | None = None,
    ) -> dict[str, dict[str, Any]]:
        """v3.3.0 ROOM-SCHED — the ONE home for the overdue rule, shared
        by sensor.*_rooms_overdue and the clean_overdue_rooms service
        (no duplicated rule set).

        Merge semantics (COVERAGE-FREQ -> ROOM-SCHED):
        - "configured": user set a frequency in the options flow ->
          expected interval from ROOM_SCHEDULE_INTERVALS, overdue at
          factor x1.0 (an explicit user expectation is a hard one).
        - "learned": no config -> self-calibrated interval and status
          from room_coverage_health() (its own x2.0 significance
          multiplier stands: the learned mean is noisy statistics, at
          x1.0 half of all rooms would permanently flag).
        - "insufficient_data": neither -> listed, never overdue.

        overdue_factor (days_since_last / expected) is included for the
        service's worst-first ordering; None without an interval.
        Rooms configured but never seen in the history are absent —
        days_since_last cannot be computed before the first clean.
        """
        from .const import ROOM_SCHEDULE_INTERVALS

        health = self.room_coverage_health(
            now_iso, region_map=region_map, umf_regions=umf_regions
        )
        config = config or {}
        result: dict[str, dict[str, Any]] = {}
        for room, info in health.items():
            days_since = info["days_since_last"]
            freq_key = config.get(room)
            if freq_key in ROOM_SCHEDULE_INTERVALS:
                expected: float | None = ROOM_SCHEDULE_INTERVALS[freq_key]
                source = "configured"
                status = "overdue" if days_since > expected else "healthy"
            elif info["expected_interval_days"] is not None:
                expected = info["expected_interval_days"]
                source = "learned"
                status = info["status"]
            else:
                expected = None
                source = "insufficient_data"
                status = "insufficient_data"
            result[room] = {
                "days_since_last": days_since,
                "expected_interval_days": (
                    round(expected, 2) if expected is not None else None
                ),
                "source": source,
                "status": status,
                "overdue_factor": (
                    round(days_since / expected, 2)
                    if expected and expected > 0 else None
                ),
            }
        return result

    def room_coverage_health(
        self,
        now_iso: str,
        days: int = 90,
        significance_multiplier: float = 2.0,
        min_intervals: int = 3,
        region_map: dict[str, str] | None = None,
        umf_regions: dict[str, str] | None = None,
    ) -> dict[str, dict[str, Any]]:
        """v3.2.0 COVERAGE-FREQ — is each room being cleaned in its OWN
        normal rhythm, self-calibrated per room rather than against a
        fixed global threshold.

        Reinterpreted from the original spec text ("GridStore EMA-decay
        curve -> recommended interval"): EMA decay is per-MISSION, not
        per-day, and converting it to a days-based recommendation would
        need an extra, somewhat arbitrary missions-per-day conversion
        step. Deriving the room's own historical cleaning cadence
        directly from its own timestamp gaps answers the same underlying
        question ("is this room being cleaned like it normally is")
        without that detour — and follows this project's established
        self-calibration philosophy (L9-BATTERY, L10, ROOM-ACCESS): a
        room is "overdue" only relative to ITS OWN typical interval, not
        an external one-size-fits-all number.

        For each room with a known last-clean timestamp (from
        room_cleaning_history()):
          - days_since_last: days since that room was last cleaned
          - expected_interval_days: mean gap between consecutive cleans
            of that specific room, from `last_cleaned_rooms` timestamps
            in the last `days` days. None when fewer than min_intervals
            gaps exist yet.
          - status: "overdue" when days_since_last exceeds the room's own
            mean + significance_multiplier * stdev (or mean * 1.5 as a
            fallback when there isn't enough variance data yet — same
            conservative-fallback spirit as L9-BATTERY's
            _ESTCAP_FALLBACK_MIN_RATE); "healthy" otherwise;
            "insufficient_data" when expected_interval_days is None.

        Returns {} when no room has ever been cleaned (no last_cleaned_rooms
        data at all — 600-series or a robot with no cloud enrichment yet).
        """
        cutoff = dt_util.now() - timedelta(days=days)
        effective_map = region_map if region_map else (umf_regions or {})
        visits_by_room: dict[str, list[str]] = {}
        for rec in self._records:
            ended_at = rec.get("ended_at")
            # v3.3.0 ROOM-SCHED foundation fix — derive, don't read the
            # never-written stored field (see room_cleaning_history).
            rooms: list[str] = self._record_room_names(rec, effective_map) or []
            # v3.2.0 full-review fix — defence in depth alongside the
            # import-gate type validation in api_views.py: a store that
            # was ALREADY poisoned with a non-string timestamp (imported
            # before that gate existed) must degrade to skipping the bad
            # record, not crash this method on every cloud-refresh cycle.
            if not ended_at or not isinstance(ended_at, str) or not rooms:
                continue
            ended_dt = dt_util.parse_datetime(ended_at)
            if ended_dt is None:
                continue
            if ended_dt.tzinfo is None:
                ended_dt = ended_dt.replace(tzinfo=timezone.utc)
            if ended_dt < cutoff:
                continue
            for room in rooms:
                visits_by_room.setdefault(room, []).append(ended_at)

        now_dt = dt_util.parse_datetime(now_iso)
        result: dict[str, dict[str, Any]] = {}

        for room, last_clean_iso in self.room_cleaning_history(region_map, umf_regions).items():
            last_dt = dt_util.parse_datetime(last_clean_iso)
            if now_dt is None or last_dt is None:
                continue
            if last_dt.tzinfo is None:
                last_dt = last_dt.replace(tzinfo=timezone.utc)
            days_since_last = (now_dt - last_dt).total_seconds() / 86400.0

            timestamps = sorted(visits_by_room.get(room, []))
            intervals: list[float] = []
            for i in range(len(timestamps) - 1):
                t1 = dt_util.parse_datetime(timestamps[i])
                t2 = dt_util.parse_datetime(timestamps[i + 1])
                if t1 is None or t2 is None:
                    continue
                gap_days = (t2 - t1).total_seconds() / 86400.0
                if gap_days > 0:
                    intervals.append(gap_days)

            if len(intervals) < min_intervals:
                result[room] = {
                    "days_since_last": round(days_since_last, 1),
                    "expected_interval_days": None,
                    "status": "insufficient_data",
                }
                continue

            mean_interval = statistics.mean(intervals)
            stdev_interval = (
                statistics.stdev(intervals) if len(intervals) >= 2 else 0.0
            )
            threshold = (
                mean_interval + significance_multiplier * stdev_interval
                if stdev_interval > 0
                else mean_interval * 1.5
            )
            status = "overdue" if days_since_last > threshold else "healthy"
            result[room] = {
                "days_since_last": round(days_since_last, 1),
                "expected_interval_days": round(mean_interval, 1),
                "status": status,
            }

        return result

    def presence_windows(self, days: int) -> list[MissionWindow]:
        """Return gaps between missions as potential 'all-away' windows.

        Each window spans from the end of one mission to the start of the next.
        resulted_in_clean=True when a completed mission started within the window.
        Used by L6 analytics sensors.
        """
        records = self.query(days)
        if len(records) < 2:
            return []

        windows: list[MissionWindow] = []
        completed_starts: set[str] = {
            r["started_at"] for r in records
            if r.get("result") in ("completed", "stuck_and_resumed")
        }

        for i in range(len(records) - 1):
            prev_end_str = records[i].get("ended_at", "")
            next_start_str = records[i + 1].get("started_at", "")
            prev_end = dt_util.parse_datetime(prev_end_str)
            next_start = dt_util.parse_datetime(next_start_str)
            if prev_end is None or next_start is None:
                continue
            # Make timezone-aware if needed
            if prev_end.tzinfo is None:
                prev_end = prev_end.replace(tzinfo=timezone.utc)
            if next_start.tzinfo is None:
                next_start = next_start.replace(tzinfo=timezone.utc)
            if next_start <= prev_end:
                continue
            duration_min = int((next_start - prev_end).total_seconds() / 60)
            resulted = next_start_str in completed_starts
            windows.append(MissionWindow(
                started_at=prev_end,
                ended_at=next_start,
                duration_min=duration_min,
                resulted_in_clean=resulted,
            ))
        return windows

    def clean_streak(self) -> int:
        """Return consecutive days ending today with at least one completed mission."""
        today = dt_util.now().date()
        completed_dates: set[date] = set()
        for r in self._records:
            if r.get("result") in ("completed", "stuck_and_resumed"):
                dt = dt_util.parse_datetime(r.get("started_at", ""))
                if dt:
                    completed_dates.add(dt_util.as_local(dt).date())
        streak = 0
        day = today
        while day in completed_dates:
            streak += 1
            day -= timedelta(days=1)
        return streak

    def p75_area(self, days: int) -> float | None:
        """Return the 75th-percentile area_sqft across records in the last `days` days.

        F5f — self-calibrating home coverage baseline.  After 10+ missions this
        stabilises as a reliable proxy for a full-clean area, filtering out
        partial cleans (low end) and zero-area failures.

        Returns None when fewer than 5 positive-area records exist (insufficient
        history to establish a stable baseline). Threshold lowered from 10 to 5
        so the sensor activates within a week of first install.
        """
        areas = [
            r["area_sqft"]
            for r in self.query(days)
            if r.get("area_sqft") is not None and r["area_sqft"] > 0
        ]
        if len(areas) < 5:
            return None
        areas.sort()
        return areas[int(len(areas) * 0.75)]

    def wear_data(self, days: int) -> list[dict[str, Any]]:
        """Return daily bbrun.hr snapshots for the last `days` days.

        Returns one entry per calendar day — the highest recorded bbrun_hr
        value for that day — sorted ascending by date. Used by L4 wear
        intelligence to compute daily wear rates without needing consecutive-
        record arithmetic in the sensor layer.

        Returns an empty list when fewer than 2 days of data exist (not enough
        to compute a meaningful rate).
        """
        buckets: dict[date, int] = {}
        for r in self.query(days):
            dt = dt_util.parse_datetime(r.get("started_at", ""))
            if dt and r.get("bbrun_hr") is not None:
                day = dt_util.as_local(dt).date()
                if day not in buckets or r["bbrun_hr"] > buckets[day]:
                    buckets[day] = r["bbrun_hr"]
        return sorted(
            [{"date": d.isoformat(), "bbrun_hr": hr} for d, hr in buckets.items()],
            key=lambda x: x["date"],
        )

    def wear_rate_since_reset(
        self,
        reset_hr: int,
        reset_at: str | None,
        current_hr: int,
    ) -> float | None:
        """Return average bbrun hours consumed per day since the last part reset.

        Returns None when:
        - reset_at is unknown (reset never recorded or store was empty)
        - current_hr has not advanced beyond reset_hr (robot not yet used)
        - fewer than 3 days have elapsed since reset (insufficient baseline)
        - reset_at cannot be parsed

        Never returns a negative value.
        """
        if reset_at is None or current_hr <= reset_hr:
            return None
        try:
            reset_dt = dt_util.parse_datetime(reset_at)
        except (ValueError, TypeError):
            return None
        if reset_dt is None:
            return None
        if reset_dt.tzinfo is None:
            reset_dt = reset_dt.replace(tzinfo=timezone.utc)
        days_elapsed = (dt_util.utcnow() - reset_dt).total_seconds() / 86400
        if days_elapsed < 3:
            return None
        rate = (current_hr - reset_hr) / days_elapsed
        return round(max(0.0, rate), 2)

    @staticmethod
    def _merge_cloud_fields(local: dict, cloud: dict) -> bool:
        """Copy missing analytics fields from a cloud record into a local record.

        Only copies when the local field is absent or None — never overwrites.

        B1 — error 224 result correction: when the cloud record reveals
        pauseId=224 and the local result is 'stuck', correct the result to
        'error'. Error 224 is not a physical stuck: the robot aborts in under
        a second and returns to dock (runM=0, sqft=0). The MQTT mission end
        packet may not carry the error code reliably on lewis firmware.

        B1-EXT (v2.10.2) — generalised result correction for two further
        cases where the local MQTT classification is demonstrably wrong once
        the cloud record arrives:

          done=='bat' (battery error) with local 'completed'/'stuck_and_resumed'
            → local result corrected to 'error'; error_code backfilled from
            pauseId if absent. The robot ran until the battery died — never a
            successful completion. Confirmed in the field: a real archive had
            completed:3 / stuck:0 for a day that contained an error_battery
            mission, because done=='bat' was never corrected locally.

          done_raw=='usrEnd' (user cancellation) with local 'completed'/
          'stuck_and_resumed'
            → local result corrected to 'cancelled'. 'stuck_and_resumed' means
            "stuck, self-recovered, finished" — but if the user then cancelled
            before the mission actually finished, that reading is wrong. The
            stuck event itself is preserved in nstuck_delta and self_recovered;
            only the final result changes. 'stuck_and_abandoned' is deliberately
            not touched: the robot stopped on its own, independently of any
            user action.

        Both B1-EXT corrections use generic 'error'/'cancelled' (not granular
        'error_battery'/'cancelled_by_user') — those granular values only exist
        in the cloud-side vocabulary and are not in the local result enum; using
        them here would create undocumented result strings that query_by_day(),
        compute_rolling_stats(), and the card's result renderer don't know about.

        Returns True if any field was written.
        """
        wrote = False

        # B1 — error 224 result correction (before generic scalar merge).
        pause_id = int(cloud.get("pauseId", 0) or 0)
        if pause_id == 224 and local.get("result") == "stuck":
            local["result"] = "error"
            if local.get("error_code") is None:
                local["error_code"] = 224
            wrote = True

        # B1-EXT — battery error / user cancellation result correction.
        done = (cloud.get("done") or "").strip()
        done_raw = (cloud.get("done_raw") or "").strip()
        local_result = local.get("result")

        if done == "bat" and local_result in ("completed", "stuck_and_resumed"):
            local["result"] = "error"
            if local.get("error_code") is None and pause_id > 0:
                local["error_code"] = pause_id
            wrote = True

        elif done_raw == "usrEnd" and local_result in ("completed", "stuck_and_resumed"):
            local["result"] = "cancelled"
            wrote = True

        for field in _CLOUD_MERGE_SCALAR:
            if local.get(field) is None and cloud.get(field) is not None:
                local[field] = cloud[field]
                wrote = True
        for field in _CLOUD_MERGE_ARRAY:
            if not local.get(field) and cloud.get(field):
                local[field] = cloud[field]
                wrote = True
        return wrote

    @staticmethod
    def _backfill_area_sqft(local: dict) -> bool:
        """Set local["area_sqft"] from local["sqft"] when the canonical
        field is still absent but the raw cloud field is present.

        "sqft" is the raw cloud field name, kept as-is via
        _CLOUD_MERGE_SCALAR; "area_sqft" is the canonical local name read
        by RobotProfileStore.update_mission_stats() and
        compute_rolling_stats(). The two must be kept in sync at every
        call site that merges cloud fields — see backfill_from_cloud()
        and merge_latest_from_cloud() for why this is a separate step
        rather than folded into _merge_cloud_fields()/_CLOUD_MERGE_SCALAR
        (the field NAME differs, "sqft" → "area_sqft", which that
        generic same-name copy loop cannot express).

        Returns True if area_sqft was written.
        """
        if local.get("area_sqft") is None and local.get("sqft") is not None:
            local["area_sqft"] = local["sqft"]
            return True
        return False

    # ── L3 — Mission anomaly detection ────────────────────────────────────────

    def compute_rolling_stats(self, days: int = 30) -> dict | None:
        """Compute rolling mean/std for duration_min and area_sqft.

        L3 — Returns None when fewer than 20 missions are available (insufficient
        history to establish a stable baseline for anomaly detection).

        Returns a dict with keys:
          duration_mean, duration_std,
          area_mean, area_std,
          recharge_mean,
          dirt_p75            (75th-percentile dirt_events from cloud-merged records)
        """
        records = self.query(days)
        if len(records) < 20:
            return None

        durations = [r["duration_min"] for r in records if r.get("duration_min") is not None]
        areas = [r["area_sqft"] for r in records
                 if r.get("area_sqft") is not None and r["area_sqft"] > 0]
        recharges = [r["recharge_min"] for r in records
                     if r.get("recharge_min") is not None]
        dirts = [r["dirt"] for r in records if r.get("dirt") is not None]

        if len(durations) < 20:
            return None

        dur_mean = statistics.mean(durations)
        dur_std  = statistics.stdev(durations) if len(durations) > 1 else 0.0
        area_mean = statistics.mean(areas) if areas else None
        area_std  = statistics.stdev(areas) if len(areas) > 1 else 0.0
        rch_mean  = statistics.mean(recharges) if recharges else 0.0

        # 75th-percentile dirt events
        dirt_p75: float | None = None
        if dirts:
            dirts.sort()
            dirt_p75 = dirts[int(len(dirts) * 0.75)]

        return {
            "duration_mean": dur_mean,
            "duration_std":  dur_std,
            "area_mean":     area_mean,
            "area_std":      area_std,
            "recharge_mean": rch_mean,
            "dirt_p75":      dirt_p75,
        }

    @staticmethod
    def compute_archive_stats(derived_records: list[dict]) -> dict | None:
        """Compute anomaly-detection baseline from ARC1 archive derived records.

        L3-ARC (v2.8.0) — identical contract to compute_rolling_stats() but
        consumes MissionArchive.all_derived_oldest_first() rather than local
        MissionStore records.  Used as a fallback baseline when the local store
        has < 20 missions.

        Field mapping from archive derived → stats dict:
          duration_min  → duration stats        (same field name)
          sqft          → area stats            (archive uses sqft, store uses area_sqft)
          dirt          → dirt percentile       (same field name)
          recharge_mean → 0.0                  (recharge_count not in minutes; skipped)

        Returns None when fewer than 20 completed-mission records are available.
        """
        completed = [
            r for r in derived_records
            if r.get("result") in ("completed", "cancelled_by_user")
        ]
        if len(completed) < 20:
            return None

        durations = []
        for r in completed:
            if r.get("duration_min") is None:
                continue
            try:
                durations.append(float(r["duration_min"]))
            except (TypeError, ValueError):
                continue
        areas = []
        for r in completed:
            if r.get("sqft") is None:
                continue
            try:
                _sqft = float(r["sqft"])
            except (TypeError, ValueError):
                continue
            if _sqft > 0:
                areas.append(_sqft)
        dirts = []
        for r in completed:
            if r.get("dirt") is None:
                continue
            try:
                dirts.append(float(r["dirt"]))
            except (TypeError, ValueError):
                continue

        if len(durations) < 20:
            return None

        dur_mean = statistics.mean(durations)
        dur_std  = statistics.stdev(durations) if len(durations) > 1 else 0.0
        area_mean = statistics.mean(areas) if areas else None
        area_std  = statistics.stdev(areas) if len(areas) > 1 else 0.0

        dirt_p75: float | None = None
        if dirts:
            dirts_sorted = sorted(dirts)
            dirt_p75 = dirts_sorted[int(len(dirts_sorted) * 0.75)]

        return {
            "duration_mean": dur_mean,
            "duration_std":  dur_std,
            "area_mean":     area_mean,
            "area_std":      area_std,
            "recharge_mean": 0.0,   # not available in ARC1 derived records
            "dirt_p75":      dirt_p75,
        }

    def anomaly_reason(
        self,
        record: dict,
        stats: dict,
        profile: Any = None,
    ) -> str | None:
        """v3.2.0 ANOMALY-EXPLAIN — same four conditions as is_anomalous()
        (which now delegates here), but returns WHICH one triggered instead
        of a bare bool. Checked in this fixed priority order when more than
        one would technically apply (rare in practice, since each is an
        early return on the same record — a mission that's both slow+low-
        coverage AND has an extreme dirt spike is an unusual combination):

          1. "obstacle_or_blockage" — slow AND low coverage
          2. "excessive_recharge"   — unusually long mid-mission recharge
          3. "dirt_spike"           — extreme dirt event
          4. "incomplete_coverage"  — pre-20-mission fallback vs robot profile

        Returns None when the record isn't anomalous by any of these.

        Deliberately does NOT cover robot_lifted or error_code — those are
        independent facts about a mission (see async_handle_explain_mission
        in services.py), not additional anomaly_reason categories. A
        mission can be robot_lifted and/or have an error_code regardless
        of whether any of the four reasons above also applies, so folding
        them into this priority chain would misrepresent them as
        competing explanations rather than orthogonal ones.
        """
        dur   = record.get("duration_min")
        area  = record.get("area_sqft")
        rch   = record.get("recharge_min")
        dirt  = record.get("dirt")

        # 1 — struggling: slow AND low coverage
        if (
            dur is not None
            and stats["duration_std"] > 0
            and dur > stats["duration_mean"] + 2 * stats["duration_std"]
            and area is not None
            and stats["area_mean"] is not None
            and stats["area_std"] > 0
            and area < stats["area_mean"] - stats["area_std"]
        ):
            return "obstacle_or_blockage"

        # 2 — excessive recharge
        if rch is not None and rch > stats["recharge_mean"] + 120:
            return "excessive_recharge"

        # 3 — extreme dirt spike
        if (
            dirt is not None
            and stats["dirt_p75"] is not None
            and stats["dirt_p75"] > 0
            and dirt > stats["dirt_p75"] * 2.5
        ):
            return "dirt_spike"

        # 4 — pre-20-mission fallback via robot profile. Only engaged when
        # no area statistics are available (stats["area_mean"] is None),
        # which happens when either fewer than 20 missions exist in the
        # window, or no mission in the window has area_sqft data
        # (600-series). With a full statistical baseline, this check is
        # intentionally skipped to avoid flagging legitimate partial room
        # cleans (e.g. single-room scheduled clean) as anomalous.
        if profile is not None and area is not None and stats["area_mean"] is None:
            typical = getattr(profile, "typical_coverage_sqft", None)
            if typical is not None and typical > 0:
                typical_m2 = typical * SQFT_TO_M2
                if area * SQFT_TO_M2 < typical_m2 * 0.4:
                    return "incomplete_coverage"

        return None

    def is_anomalous(
        self,
        record: dict,
        stats: dict,
        profile: Any = None,
    ) -> bool:
        """Return True when a record is statistically anomalous.

        L3 conditions (any one triggers) — see anomaly_reason() for the
        full detail and the specific reason each one maps to; this is now
        a thin wrapper so the two never drift out of sync with each other.
        """
        return self.anomaly_reason(record, stats, profile) is not None

    @property
    def consecutive_anomalous(self) -> int:
        """Count of consecutive most-recent missions that are anomalous.

        L3 — evaluated lazily when accessed; always reads fresh from _records.
        Falls back to archive_baseline (L3-ARC v2.8.0) when local stats are
        unavailable (< 20 local missions).
        Returns 0 when neither local stats nor archive baseline are available.
        """
        stats = self.compute_rolling_stats()
        if stats is None:
            stats = self.archive_baseline   # L3-ARC fallback
        if stats is None:
            return 0
        count = 0
        for record in reversed(self._records):
            if self.is_anomalous(record, stats):
                count += 1
            else:
                break
        return count

    def backfill_from_cloud(
        self,
        cloud_records: list[dict],
        tolerance_sec: int = 120,
    ) -> BackfillResult:
        """Correct local MissionStore records using cloud /missionhistory timestamps.

        The 980/900-series firmware resets mssnStrtTm to 0 in the mission-end
        MQTT message. When callbacks.py cannot capture a valid start timestamp,
        started_at falls back to wall-clock at recording time, making
        duration_min ≈ 0 and the record id incorrect.

        Matches each local record against cloud records by end timestamp
        (±tolerance_sec), then corrects:
          - started_at  — from cloud startTime
          - ended_at    — from cloud timestamp
          - duration_min — recomputed from corrected timestamps
          - id          — regenerated from corrected started_at
          - area_sqft   — from cloud sqft when local value is None

        Analytics fields (dirt, chrgM, wlBars, etc.) are merged into every
        matched record regardless of whether a timestamp correction is needed.

        Matching uses ended_at (local) vs timestamp (cloud) because ended_at
        is always reliably recorded at wall-clock time.

        Args:
            cloud_records: raw cloud records, newest-first from API.
            tolerance_sec: max seconds between local ended_at and cloud
                           timestamp to count as the same mission. Default 120 s
                           covers MQTT delivery lag and clock skew.

        Returns:
            BackfillResult(corrected, enriched) — counts of timestamp
            corrections and analytics field merges respectively.
        """
        if not cloud_records or not self._records:
            return BackfillResult(corrected=0, enriched=0)

        # Build index of cloud records keyed by end timestamp for O(1) lookup.
        cloud_by_end: dict[int, dict] = {}
        for cr in cloud_records:
            ts = cr.get("timestamp")
            if ts is not None:
                cloud_by_end.setdefault(int(ts), cr)

        corrected = 0
        enriched = 0
        for local in self._records:
            ended_str = local.get("ended_at", "")
            if not ended_str:
                continue
            try:
                ended_dt = datetime.fromisoformat(ended_str)
            except (ValueError, TypeError):
                continue
            if ended_dt.tzinfo is None:
                ended_dt = ended_dt.replace(tzinfo=timezone.utc)
            local_end_ts = int(ended_dt.timestamp())

            # Find nearest cloud record within tolerance
            best_cr: dict | None = None
            best_delta = tolerance_sec + 1
            for cloud_ts, cr in cloud_by_end.items():
                delta = abs(cloud_ts - local_end_ts)
                if delta <= tolerance_sec and delta < best_delta:
                    best_delta = delta
                    best_cr = cr

            if best_cr is None:
                continue

            cloud_start = best_cr.get("startTime")
            cloud_end   = best_cr.get("timestamp")
            if not cloud_start or not cloud_end:
                continue

            new_started = datetime.fromtimestamp(
                int(cloud_start), tz=timezone.utc
            )
            new_ended = datetime.fromtimestamp(
                int(cloud_end), tz=timezone.utc
            )

            # Only correct if timestamps differ meaningfully (>5 min)
            old_started_str = local.get("started_at", "")
            try:
                old_started = datetime.fromisoformat(old_started_str)
                if old_started.tzinfo is None:
                    old_started = old_started.replace(tzinfo=timezone.utc)
                delta_start = abs((new_started - old_started).total_seconds())
            except (ValueError, TypeError):
                delta_start = float("inf")

            # Always merge analytics fields regardless of timestamp delta.
            merge_wrote = self._merge_cloud_fields(local, best_cr)

            # area_sqft is the canonical local name; "sqft" above is the
            # raw cloud field, just merged (or already present locally).
            # This MUST run independently of the timestamp-correction
            # branch below: area_sqft has nothing to do with whether
            # started_at/ended_at needed correcting. Previously this lived
            # after the `delta_start < 300: continue`, so it only ever
            # fired on the rare mission that ALSO had bad timestamps —
            # leaving area_sqft permanently None on every mission whose
            # local timestamps were already accurate (confirmed in the
            # field: 24/24 local records, area_sqft never once populated
            # despite "sqft" correctly carrying real cloud values).
            area_wrote = self._backfill_area_sqft(local)

            if merge_wrote or area_wrote:
                enriched += 1

            # Only correct timestamps when they differ meaningfully (> 5 min).
            if delta_start < 300:
                continue

            new_duration = max(0, round(
                (new_ended - new_started).total_seconds() / 60
            ))
            new_id = f"m_{int(new_started.timestamp())}"

            local["started_at"]   = new_started.isoformat()
            local["ended_at"]     = new_ended.isoformat()
            local["duration_min"] = new_duration
            local["id"]           = new_id

            corrected += 1
            _LOGGER.debug(
                "MissionStore backfill: corrected %s → started_at=%s "
                "duration=%dmin (was %s, delta=%.0fs)",
                new_id, new_started.isoformat(),
                new_duration, old_started_str, delta_start,
            )

        if corrected or enriched:
            _LOGGER.info(
                "MissionStore backfill: corrected=%d timestamp(s), enriched=%d record(s)",
                corrected, enriched,
            )
        return BackfillResult(corrected=corrected, enriched=enriched)

    def merge_latest_from_cloud(
        self,
        cloud_records: list[dict],
        tolerance_sec: int = 120,
    ) -> bool:
        """Merge cloud analytics fields into the most recent local record.

        Called after the post-mission cloud refresh (F4b). Targets only
        the last record — the mission that just ended is newest in both stores.
        Uses the same ±tolerance_sec end-timestamp matching as backfill_from_cloud.

        Returns True if any field was written to the record.
        """
        if not self._records or not cloud_records:
            return False

        local = self._records[-1]
        ended_str = local.get("ended_at", "")
        if not ended_str:
            return False

        try:
            ended_dt = datetime.fromisoformat(ended_str)
        except (ValueError, TypeError):
            return False

        if ended_dt.tzinfo is None:
            ended_dt = ended_dt.replace(tzinfo=timezone.utc)

        local_end_ts = int(ended_dt.timestamp())

        best_cr: dict | None = None
        best_delta = tolerance_sec + 1
        for cr in cloud_records:
            ts = cr.get("timestamp")
            if ts is None:
                continue
            delta = abs(int(ts) - local_end_ts)
            if delta <= tolerance_sec and delta < best_delta:
                best_delta = delta
                best_cr = cr

        if best_cr is None:
            return False

        merge_wrote = self._merge_cloud_fields(local, best_cr)
        area_wrote = self._backfill_area_sqft(local)
        return merge_wrote or area_wrote

    async def async_backfill_statistics(
        self,
        hass: HomeAssistant,
        entry_id: str,
        robot_name: str,
    ) -> None:
        """Inject historical mission data into HA Long-Term Statistics.

        F7j -- backfills three external statistic series from MissionStore records,
        making a full year of history immediately available in the HA Statistics
        graph card.  async_add_external_statistics() is idempotent -- duplicate
        start timestamps are silently ignored, so this is safe to call on every
        startup and after every new record.

        Series:
          roomba_plus:{entry_id}_area_cleaned_m2    -- daily sum (m², has_sum)
          roomba_plus:{entry_id}_mission_duration_min -- daily sum (min, has_sum)
          roomba_plus:{entry_id}_missions_completed  -- daily count (missions, has_sum)

        Gate: area series requires cloud records with area_sqft.  Duration and
        completion count work for all robots from local records.
        """
        try:
            from homeassistant.components.recorder.statistics import (
                async_add_external_statistics,
            )
            from homeassistant.components.recorder.models import (
                StatisticData,
                StatisticMetaData,
            )
            # mean_type required from HA 2026.11 — pass as integer (0 = NONE)
            # to avoid import dependency on StatisticsMeanType which may not
            # exist in older HA versions. StatisticMetaData is a TypedDict so
            # it accepts any value without type checking.
            _mean_type_none = 0
        except ImportError:
            _LOGGER.debug(
                "MissionStore: recorder not available -- skipping statistics backfill"
            )
            return

        import inspect as _inspect

        async def _import_stats(meta, stats):
            """Call async_add_external_statistics, handling both sync and async variants."""
            result = async_add_external_statistics(hass, meta, stats)
            if _inspect.isawaitable(result):
                await result

        def _make_meta(name, statistic_id, unit):
            return StatisticMetaData(
                has_mean=False,
                has_sum=True,
                mean_type=_mean_type_none,  # 0 = NONE (no mean), required from HA 2026.11
                name=name,
                source=source,
                statistic_id=statistic_id,
                unit_class=None,            # required from HA 2025.11 — None = no unit conversion
                unit_of_measurement=unit,
            )

        if not self._records:
            return

        # Group records by hour-truncated start timestamp (LTS granularity)
        area_stats: list[StatisticData] = []
        duration_stats: list[StatisticData] = []
        completion_stats: list[StatisticData] = []

        for r in self._records:
            started_str = r.get("started_at", "")
            if not started_str:
                continue
            try:
                started_dt = dt_util.parse_datetime(started_str)
                if started_dt is None:
                    continue
                if started_dt.tzinfo is None:
                    started_dt = started_dt.replace(tzinfo=timezone.utc)
                # Truncate to hour for LTS
                bucket = started_dt.replace(minute=0, second=0, microsecond=0)
            except (ValueError, TypeError):
                continue

            area_sqft = r.get("area_sqft")
            duration_min = r.get("duration_min") or 0
            is_completed = r.get("result") in ("completed", "stuck_and_resumed")

            if area_sqft is not None:
                area_m2 = round(float(area_sqft) * SQFT_TO_M2, 2)
                area_stats.append(StatisticData(start=bucket, sum=area_m2))

            duration_stats.append(StatisticData(start=bucket, sum=float(duration_min)))
            completion_stats.append(StatisticData(start=bucket, sum=1.0 if is_completed else 0.0))

        source = "roomba_plus"

        # HA validates statistic_id strictly: domain:object_id where object_id
        # must be lowercase letters, digits and underscores only.
        # Entry IDs are ULIDs (uppercase) — convert to lowercase.
        safe_entry_id = entry_id.lower()

        if area_stats:
            await _import_stats(
                _make_meta(f"{robot_name} \u2014 Area cleaned", f"{source}:{safe_entry_id}_area_cleaned_m2", "m\u00b2"),
                area_stats,
            )

        if duration_stats:
            await _import_stats(
                _make_meta(f"{robot_name} \u2014 Mission duration", f"{source}:{safe_entry_id}_mission_duration_min", "min"),
                duration_stats,
            )

        if completion_stats:
            await _import_stats(
                _make_meta(f"{robot_name} \u2014 Missions completed", f"{source}:{safe_entry_id}_missions_completed", "missions"),
                completion_stats,
            )

        _LOGGER.debug(
            "MissionStore: statistics backfill complete for %s "
            "(%d area, %d duration, %d completion points)",
            entry_id,
            len(area_stats),
            len(duration_stats),
            len(completion_stats),
        )
