"""MissionTimerStore — persists mission run-time across HA restarts.

MP1 (v2.6.0) — a purely transient counter is lost on HA restart mid-mission,
producing misleading 0 % progress. This store persists the current mission_id
and accumulated run_sec to hass.storage so the progress sensor can resume
from the correct value after a restart.

v2.7.1 (MP-PERSIST) — extended schema: also persists total_estimated_sec
(prevents progress ratio jump after restart), planned_rooms + current_room_idx
(prevents current_room/next_room freeze on lewis firmware that doesn't re-send
plan events after MQTT reconnect), recharge_positions (for ⚡ markers),
and snapshot_ts (staleness gate: if now - snapshot_ts > 7200 s the timer is
stale and is discarded rather than resumed).

Lifecycle:
  - Instantiated in async_setup_entry for SMART + cloud robots.
  - Call async_load() on setup to resume any in-progress mission.
  - Call set_mission_plan() at mission start to write total_estimated_sec
    and planned_rooms.
  - Call on_phase_run() on every phase=="run" MQTT message to accumulate.
  - Call advance_room() when a traversal event changes the current room.
  - Call on_recharge() when a recharge event is detected.
  - Call clear() when mission_id changes or mission ends.
  - async_save() is called automatically after mutations.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
import time
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store

_LOGGER = logging.getLogger(__name__)


def _safe_float(val: Any) -> float | None:
    """Convert val to float, returning None on TypeError/ValueError.

    v2.8.0 bug-hunt: room_estimates_sec entries originate from the cloud TE1
    API (cloud_coordinator.regions[*].time_estimates). A malformed or
    unexpectedly-typed cloud value (e.g. a string) must not crash
    expected_room_sec or any downstream confidence-check comparison.
    """
    if val is None:
        return None
    try:
        return float(val)
    except (TypeError, ValueError):
        return None


STORAGE_VERSION = 1
_DELAY_SAVE_SEC = 15.0  # v3.3.0 DELAY-SAVE — debounce window
_STORAGE_KEY_PREFIX = "roomba_plus_mission_timer"
_STALE_THRESHOLD_SEC = 7200  # 2 hours — if snapshot is older, timer is stale


class MissionTimerStore:
    """Persist elapsed run-only seconds and mission plan for the active mission.

    Fields stored (v2.7.1):
        mission_id: str | None        — current mission identifier (blid + start_ts)
        run_sec: float                — accumulated run-only seconds
        total_estimated_sec: float|None — estimated total cleaning time (denominator)
        planned_rooms: list[str]      — room names in planned order
        current_room_idx: int         — last known position in planned_rooms
        recharge_positions: list[int] — indices in planned_rooms where recharges occurred
        snapshot_ts: float            — wall-clock time of last write (staleness gate)
    """

    def __init__(self) -> None:
        self.mission_id: str | None = None
        self.run_sec: float = 0.0
        # v3.3.0 DELAY-SAVE — cached Store handle; async_delay_save
        # debounces per Store instance (see _get_ha_store).
        self._ha_store: Store | None = None
        self.total_estimated_sec: float | None = None
        self.planned_rooms: list[str] = []
        self.current_room_idx: int = 0
        self.recharge_positions: list[int] = []
        self.snapshot_ts: float = 0.0
        self._last_phase_ts: float = 0.0
        # v2.8.0 AUTO-ADVANCE-ROOM — run_sec value when current_room_idx last
        # changed.  Used to compute time_in_current_room_sec for the confidence
        # check (elapsed time in room vs. expected per-room duration).
        self.room_entered_run_sec: float = 0.0
        # v2.8.0 AUTO-ADVANCE-ROOM (live wiring) — per-room time estimates in
        # planned_rooms order, from cloud TE1 data (sensor.py _room_estimates).
        # Entry is None where no GOOD_CONFIDENCE estimate exists (e.g. Auto
        # pass mode, or new/uncalibrated room) — falls back to uniform split.
        self.room_estimates_sec: list[float | None] = []
        # v2.9.0 — wall-clock Unix timestamp of mission start, set once when
        # a new mission_id is first detected in on_phase_run(). Deliberately
        # SEPARATE from run_sec: total mission duration (now - this) is
        # always correct by construction (plain wall-clock subtraction, no
        # phase-tracking or gap-clamping involved) — used to show a smoothly
        # ticking "total elapsed" alongside the chunkier, gap-clamped
        # "effective cleaning time" (run_sec), instead of one value trying
        # to be both smooth AND accurate and occasionally visibly
        # overshooting-then-correcting when those two goals conflict (see
        # the Thonno field report this was introduced to resolve).
        self.mission_started_wall_ts: float = 0.0
        # v2.9.0 — live mirror of callbacks.py's F4e recharge_min_accumulator
        # (mid-mission hmMidMsn recharge minutes, robot-reported via rechrgM).
        # Previously only ever written ONCE at mission end into the
        # MissionStore record — never readable live, never persisted across
        # an HA restart mid-mission. Mirrored here on every update so
        # mission_progress can show (mission_duration_min - recharge_min) =
        # effective mission duration WITHOUT any time-based gap clamp or
        # heuristic: charging time is something the robot tells us directly,
        # not something we infer from MQTT silence.
        self.recharge_min: float = 0.0

    # ── Persistence ───────────────────────────────────────────────────────────

    async def async_load(self, hass: HomeAssistant, entry_id: str) -> None:
        """Load persisted timer from hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{_STORAGE_KEY_PREFIX}_{entry_id}")
        data: dict | None = await store.async_load()
        if not data:
            return
        try:
            snapshot_ts = float(data.get("snapshot_ts", 0))
            # Staleness gate: discard if snapshot is older than 2 hours.
            if snapshot_ts and (time.time() - snapshot_ts) > _STALE_THRESHOLD_SEC:
                _LOGGER.debug(
                    "MissionTimerStore: stale snapshot (%.0f s old) — discarding",
                    time.time() - snapshot_ts,
                )
                return
            self.mission_id           = data.get("mission_id")
            self.run_sec              = float(data.get("run_sec", 0))
            self.total_estimated_sec  = data.get("total_estimated_sec")
            self.planned_rooms        = data.get("planned_rooms") or []
            self.current_room_idx     = int(data.get("current_room_idx", 0))
            self.recharge_positions   = data.get("recharge_positions") or []
            self.room_entered_run_sec = float(data.get("room_entered_run_sec", 0))
            self.room_estimates_sec  = data.get("room_estimates_sec") or []
            self.mission_started_wall_ts = float(data.get("mission_started_wall_ts", 0))
            self.recharge_min          = float(data.get("recharge_min", 0))
            self.snapshot_ts          = snapshot_ts
            _LOGGER.debug(
                "MissionTimerStore: resumed mission=%s run_sec=%.0f rooms=%s idx=%d",
                self.mission_id, self.run_sec,
                self.planned_rooms, self.current_room_idx,
            )
        except (TypeError, ValueError) as exc:
            _LOGGER.warning("MissionTimerStore: load failed — %s", exc)

    def _payload(self) -> dict:
        """Serialise current timer state (single home for the shape —
        used by both the immediate and the delayed save path)."""
        return {
            "mission_id":          self.mission_id,
            "run_sec":             self.run_sec,
            "total_estimated_sec": self.total_estimated_sec,
            "planned_rooms":       self.planned_rooms,
            "current_room_idx":    self.current_room_idx,
            "recharge_positions":  self.recharge_positions,
            "room_entered_run_sec": self.room_entered_run_sec,
            "room_estimates_sec":  self.room_estimates_sec,
            "mission_started_wall_ts": self.mission_started_wall_ts,
            "recharge_min":        self.recharge_min,
            "snapshot_ts":         time.time(),
        }

    async def async_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Persist current timer state immediately (load/migration paths)."""
        store = self._get_ha_store(hass, entry_id)
        await store.async_save(self._payload())

    def _get_ha_store(self, hass: HomeAssistant, entry_id: str) -> Store:
        """Cached Store handle. v3.3.0 DELAY-SAVE — async_delay_save
        debounces PER Store instance; the previous new-Store-per-save
        pattern would have defeated the debounce entirely."""
        if self._ha_store is None:
            self._ha_store = Store(
                hass, STORAGE_VERSION, f"{_STORAGE_KEY_PREFIX}_{entry_id}"
            )
        return self._ha_store

    def schedule_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Thread-safe DEBOUNCED save (safe to call from paho-MQTT thread).

        v3.3.0 DELAY-SAVE — this is the write-amplification fix from the
        v3.2.0 tech-debt review: on_phase_run fires on every phase=run
        MQTT message (every few seconds for the whole mission) and
        previously wrote to disk each time. Now batched via HA's
        Store.async_delay_save(15 s); HA flushes pending writes on stop
        automatically. Deliberate trade-off (documented in the version
        plan): up to 15 s of run_sec lost on a hard crash — the previous
        MP1 decision, now resolved.

        v3.3.0 STORE-ENCAP — public: callbacks.py needs it for the
        recharge-position persist and previously called the private name."""
        hass.loop.call_soon_threadsafe(
            self._delay_save_on_loop, hass, entry_id
        )

    def _delay_save_on_loop(self, hass: HomeAssistant, entry_id: str) -> None:
        """Loop-side half of schedule_save — Store.async_delay_save must
        run on the event loop."""
        self._get_ha_store(hass, entry_id).async_delay_save(
            self._payload, _DELAY_SAVE_SEC
        )

    # v3.3.0 STORE-ENCAP — deprecated private alias for the 12 internal
    # call sites in this module and existing tests; production consumers
    # must use schedule_save (enforced by the encapsulation guard test).
    _schedule_save = schedule_save

    # ── Public API ────────────────────────────────────────────────────────────

    @property
    def last_phase_ts(self) -> float:
        """Monotonic timestamp of the last phase=run message, 0.0 when
        none seen. v3.3.0 STORE-ENCAP — read-only for sensor.py's
        live-delta computation."""
        return self._last_phase_ts

    def set_mission_plan(
        self,
        mission_id: str,
        planned_rooms: list[str],
        total_estimated_sec: float | None,
        hass: HomeAssistant,
        entry_id: str,
        room_estimates_sec: list[float | None] | None = None,
    ) -> None:
        """Called at mission start with the planned room sequence and time estimate.

        MP-PERSIST: persisting these values means that after an HA restart,
        current_room/next_room remain correct and progress ratio stays stable.

        room_estimates_sec (v2.8.0 AUTO-ADVANCE-ROOM): optional per-room time
        estimates in the same order as planned_rooms, from cloud TE1 data.
        When provided, expected_room_sec uses the specific room's estimate
        instead of a uniform total_estimated_sec / room_count split.
        """
        if self.mission_id != mission_id:
            self.mission_id          = mission_id
            self.run_sec             = 0.0
            self.current_room_idx    = 0
            self.recharge_positions  = []
            self._last_phase_ts      = 0.0
            self.room_entered_run_sec = 0.0
        self.planned_rooms       = planned_rooms
        self.total_estimated_sec = total_estimated_sec
        self.room_estimates_sec  = room_estimates_sec or []
        self._schedule_save(hass, entry_id)

    def update_estimates(
        self,
        total_estimated_sec: float | None,
        room_estimates_sec: list[float | None] | None,
        hass: HomeAssistant,
        entry_id: str,
    ) -> None:
        """Refresh ONLY the time-estimate fields for the current mission.

        v2.9.0 (E) — RETRY for missing estimates. set_mission_plan() ran
        exactly once, at the first phase=="run" message of a mission. If
        cloud TE1 data (cloud_coordinator.regions) simply hadn't synced yet
        at that exact moment — a real, confirmed risk (see the v2.9.0
        _get_planned_room_order PARTIAL resolution fix) — total_estimated_sec
        stayed None/uniform-fallback for the WHOLE mission with no chance to
        recover, even though the real per-room data might have become
        available moments later.

        Deliberately does NOT touch mission_id/run_sec/current_room_idx/
        planned_rooms/recharge_positions — only the two estimate fields.
        Safe to call repeatedly; the caller (callbacks.py) only invokes this
        when total_estimated_sec is still None, so a successful refresh is
        a one-time event per mission in practice.
        """
        self.total_estimated_sec = total_estimated_sec
        self.room_estimates_sec  = room_estimates_sec or []
        self._schedule_save(hass, entry_id)

    def on_recharge(self, hass: HomeAssistant, entry_id: str) -> None:
        """Called when a recharge event is detected mid-mission.

        Records the current room index so the traversal display can insert
        a ⚡ marker at the right position.
        """
        if self.current_room_idx not in self.recharge_positions:
            self.recharge_positions.append(self.current_room_idx)
        self._schedule_save(hass, entry_id)

    def on_phase_run(self, mission_id: str, hass: HomeAssistant, entry_id: str) -> None:
        """Called each time phase=="run" is observed in MQTT.

        Accumulates elapsed wall-clock delta since the previous phase=="run"
        message. Ignores inter-message gaps > 120 s (e.g. recharges, pauses,
        HA restarts) to avoid double-counting non-cleaning time.

        Saves asynchronously via asyncio.run_coroutine_threadsafe (thread-safe;
        called from paho-MQTT thread via callbacks.py) to avoid blocking
        the MQTT callback loop.

        v2.9.0 — added debug logging to both branches. Reported by Thonno
        (i7+, lewis 22.52.10): progress/elapsed-time resets to 0 during a
        genuine inter-room transition within a SINGLE clean_room mission
        (confirmed from his debug capture that callbacks.py's END-DEBOUNCE
        mission-end confirmation never fires during the affected window —
        ruling out that code path entirely). This function resets run_sec
        whenever self.mission_id != mission_id and was completely silent,
        making it impossible to confirm or rule out as the actual cause.
        mission_id is computed in callbacks.py as f"{blid}_{mission_start_ts}"
        — if mission_start_ts is read from a momentarily-stale or re-derived
        value during the transition, this comparison could spuriously see
        "a new mission" mid-mission and zero the counter.
        """
        now = time.monotonic()
        if self.mission_id != mission_id:
            _LOGGER.debug(
                "MissionTimerStore: on_phase_run sees NEW mission_id "
                "(old=%s new=%s) — resetting run_sec (was %.0f)",
                self.mission_id, mission_id, self.run_sec,
            )
            # New mission — reset counter (plan set separately via set_mission_plan)
            self.mission_id      = mission_id
            self.run_sec         = 0.0
            self._last_phase_ts  = now
            # v2.9.0 — wall-clock anchor for mission_duration_min, and reset
            # the live recharge_min mirror for the new mission.
            self.mission_started_wall_ts = time.time()
            self.recharge_min    = 0.0
            self._schedule_save(hass, entry_id)
            return

        if self._last_phase_ts > 0:
            delta = now - self._last_phase_ts
            # Clamp: ignore gaps > 120 s (recharge, pause, restart)
            if 0 < delta < 120:
                self.run_sec += delta
                self._schedule_save(hass, entry_id)
            else:
                _LOGGER.debug(
                    "MissionTimerStore: on_phase_run gap=%.1fs outside "
                    "0-120s clamp — NOT accumulated into run_sec=%.0f",
                    delta, self.run_sec,
                )
        self._last_phase_ts = now

    def on_phase_other(
        self,
        hass: HomeAssistant | None = None,
        entry_id: str | None = None,
    ) -> None:
        """Flush pending live delta into run_sec then reset the phase timestamp.

        v2.7.5 (MP-TRANSITION-FIX): previously discarded the delta accumulated
        since the last phase=run message.  Lewis firmware sends a non-run
        cleanMissionStatus at every inter-room boundary, so each room transition
        caused elapsed_run_min and progress to jump backwards to the bare
        run_sec value, then recover once phase=run resumed in the next room.

        The flush uses the same 120 s cap as on_phase_run to exclude genuine
        long pauses (recharges, stuck events) where the gap is intentionally
        not counted as run time.

        hass and entry_id are optional so callers that cannot provide them
        (e.g. tests) still work; without them the flushed value is persisted
        on the next on_phase_run call instead.
        """
        now = time.monotonic()
        if self._last_phase_ts > 0:
            delta = now - self._last_phase_ts
            if 0 < delta < 120:
                self.run_sec += delta
                if hass is not None and entry_id is not None:
                    self._schedule_save(hass, entry_id)
        self._last_phase_ts = 0.0

    def advance_room(self, hass: HomeAssistant, entry_id: str) -> bool:
        """Advance current_room_idx by one and persist.

        ADVANCE-ROOM-V2 (v2.8.0) — Manual override for lewis firmware robots
        when the room progress sensor gets stuck. Called from the
        roomba_plus.advance_room service with non-run-phase guard.

        Returns True when advanced, False when already at last room or no
        active mission (guards enforced in the service handler, not here).
        """
        if not self.planned_rooms:
            return False
        if self.current_room_idx >= len(self.planned_rooms) - 1:
            return False  # already at last room
        self.current_room_idx += 1
        self.room_entered_run_sec = self.run_sec
        self._schedule_save(hass, entry_id)
        _LOGGER.debug(
            "MissionTimerStore: advance_room → idx=%d (%s)",
            self.current_room_idx,
            self.planned_rooms[self.current_room_idx]
            if self.current_room_idx < len(self.planned_rooms)
            else "?",
        )
        return True

    def clear(self, hass: HomeAssistant, entry_id: str) -> None:
        """Reset the timer at mission end. Saves asynchronously."""
        self.mission_id          = None
        self.run_sec             = 0.0
        self.total_estimated_sec = None
        self.planned_rooms       = []
        self.current_room_idx    = 0
        self.recharge_positions  = []
        self.room_entered_run_sec = 0.0
        self.room_estimates_sec  = []
        self.mission_started_wall_ts = 0.0
        self.recharge_min        = 0.0
        self.snapshot_ts         = 0.0
        self._last_phase_ts      = 0.0
        self._schedule_save(hass, entry_id)

    # ── Derived properties (for sensor.py) ────────────────────────────────────

    @property
    def elapsed_run_min(self) -> float | None:
        """Elapsed run time in minutes (float, 1 decimal precision).

        MP-ELAPSED: was int division causing 12 sec → 0 min after restart.
        Now returns float so 12 s shows as 0.2 min.
        """
        if not self.mission_id:
            return None
        return round(self.run_sec / 60, 1)

    @property
    def mission_duration_min(self) -> float | None:
        """v2.9.0 — Gesamtdauer: pure wall-clock minutes since mission start.

        Deliberately independent of run_sec/phase-tracking — just
        time.time() - mission_started_wall_ts. Always correct by
        construction, never affected by the gap-clamp/discontinuity issues
        that elapsed_run_min and the percentage sensor have historically had
        (see Thonno's v2.8.6 field reports). Ticks smoothly via the
        mission_progress sensor's existing 30s periodic refresh.
        """
        if not self.mission_id or self.mission_started_wall_ts <= 0:
            return None
        return round(max(0.0, time.time() - self.mission_started_wall_ts) / 60, 1)

    @property
    def effective_elapsed_min(self) -> float | None:
        """v2.9.0 — Effektive Mission-Dauer: mission_duration_min minus
        robot-confirmed recharge_min. Replaces the old gap-clamped run_sec
        as the basis for mission_progress's percentage/elapsed_run_min/
        estimated_remaining_min attributes.

        No time-based clamp or heuristic — recharge_min comes directly from
        the robot's own hmMidMsn/rechrgM reporting (see callbacks.py F4e),
        so genuine non-charging gaps (navigation, room
        localisation/"Reading room in progress" — confirmed by Thonno's
        field observation to NOT be a charge/dock/pause/error state) are
        correctly included as effective mission time instead of being
        silently excluded by a fixed-duration guess.
        """
        duration = self.mission_duration_min
        if duration is None:
            return None
        return max(0.0, round(duration - self.recharge_min, 1))

    @property
    def current_room(self) -> str | None:
        """Current room from restored plan (MP-ROOMS: survives HA restart)."""
        if not self.planned_rooms:
            return None
        idx = min(self.current_room_idx, len(self.planned_rooms) - 1)
        return self.planned_rooms[idx]

    @property
    def next_room(self) -> str | None:
        """Next room from restored plan (MP-ROOMS: survives HA restart)."""
        if not self.planned_rooms:
            return None
        next_idx = self.current_room_idx + 1
        if next_idx >= len(self.planned_rooms):
            return None
        return self.planned_rooms[next_idx]

    @property
    def time_in_current_room_sec(self) -> float:
        """Elapsed run-seconds since the robot entered the current room.

        AUTO-ADVANCE-ROOM (v2.8.0) — used as a confidence signal: if this
        value is close to expected_room_sec, the robot has likely finished
        the room and a non-run transient phase is a genuine room transition
        rather than a pause/error/recharge.
        """
        return max(0.0, self.run_sec - self.room_entered_run_sec)

    @property
    def expected_room_sec(self) -> float | None:
        """Expected duration for the current room.

        AUTO-ADVANCE-ROOM (v2.8.0) — prefers the real per-room cloud TE1
        estimate (room_estimates_sec[current_room_idx]) when available, since
        it reflects that specific room's size and configured pass mode.

        Falls back to a uniform split (total_estimated_sec / room count) when
        no per-room estimate exists for the current room (e.g. Auto pass mode,
        or a newly-added room with no cloud confidence data yet) — a coarser
        heuristic, since large rooms legitimately take longer than average.

        Returns None when neither source is available.
        """
        if (
            self.room_estimates_sec
            and 0 <= self.current_room_idx < len(self.room_estimates_sec)
            and self.room_estimates_sec[self.current_room_idx] is not None
        ):
            _safe = _safe_float(self.room_estimates_sec[self.current_room_idx])
            if _safe is not None and _safe > 0:
                return _safe
            # Malformed/non-numeric/non-positive cloud value — fall through
            # to the uniform-split heuristic below rather than propagating
            # a bad type into the confidence-check comparison.
        if not self.total_estimated_sec or not self.planned_rooms:
            return None
        _total = _safe_float(self.total_estimated_sec)
        if _total is None or _total <= 0:
            return None
        return _total / len(self.planned_rooms)
