"""Data models for the Roomba+ integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any

from homeassistant.config_entries import ConfigEntry

if TYPE_CHECKING:
    from roombapy import Roomba
    from roombapy_prime import PrimeRobot
    from roombapy_prime.models import RobotSerialInfo
    from .blocking_manager import BlockingManager
    from .cloud_coordinator import IrobotCloudCoordinator
    from .const import RobotProfile
    from .geometry_store import GeometryStore
    from .grid_store import GridStore                # v2.2.0 F9
    from .room_seg_store import RoomSegStore          # ROOM-SEG
    from .umf_aligner import UmfAligner              # v2.3.0 F8
    from .maintenance_store import MaintenanceStore
    from .mission_store import MissionStore          # v1.8.0 L1
    from .map_renderer import MapRenderer
    from .presence_manager import PresenceManager    # v1.8.0 L6
    from .dirt_threshold_manager import DirtThresholdManager  # v2.4 F11
    from .outline_store import OutlineStore                    # v2.4 F-EPHEMERAL
    from .mission_trajectory_store import MissionTrajectoryStore  # v3.2.1
    from .freeze_snapshot_store import FreezeSnapshotStore        # v3.2.1
    from .robot_profile_store import RobotProfileStore        # v2.6 L4
    from .mission_timer_store import MissionTimerStore        # v2.6 MP1
    from .prime_coordinator import (  # V4/Prime
        PrimeCoordinator,
        PrimePartsCoordinator,
        PrimeStatusCoordinator,
    )


class MapCapability(Enum):
    """Map rendering capability level of a robot.

    NONE:      600-series bump-and-run — no pose data, no map.
    EPHEMERAL: 900-series VSLAM — pose data available, map is per-mission only,
               no persistent pmaps. RoomSegStore accumulates rooms/doors
               across missions (watershed segmentation on GridStore).
    SMART:     i/s/j/m-series — pose data + persistent pmaps/regions.
               Cloud coordinator is created when credentials are available.
    """

    NONE = "none"
    EPHEMERAL = "ephemeral"
    SMART = "smart"


class ConnectionType(Enum):
    """How this config entry talks to its robot.

    NEW (V4/Prime prep, July 2026). Orthogonal to MapCapability, which
    describes map/room richness independent of transport. See
    ROOMBA_PLUS_VERSION_PLAN_v4_onwards.md for the full architecture
    context.

    UPDATE: now referenced by RoombaData (below) -- roomba is Optional
    for exactly this reason (a CLOUD_ONLY entry has no local Roomba
    object at all). CLOUD_ONLY entries take an entirely separate setup/
    unload path (_async_setup_entry_prime() in __init__.py) rather than
    threading through the existing 4-phase LOCAL_PUSH pipeline, which
    has deep assumptions about a real, disconnectable local roomba
    object at many points beyond just RoombaData itself.

    LOCAL_PUSH: existing — roombapy, local MQTT (blid+password+IP).
    CLOUD_ONLY: NEW — roombapy-prime, V4/Prime. No local channel exists.
    """

    LOCAL_PUSH = "local_push"
    CLOUD_ONLY = "cloud_only"


@dataclass
class RoombaData:
    """Runtime data stored in config_entry.runtime_data.

    WHAT BELONGS HERE. Ephemeral per-entry state: anything that should
    start fresh when Home Assistant restarts. Anything that must
    SURVIVE a restart belongs in a Store instead (MissionStore,
    MaintenanceStore, RobotProfileStore and the rest), which persists
    to hass.storage.

    That rule was previously written on two fields that nothing used,
    and would have been deleted along with them. It is the only thing
    that makes a container this size decidable, so it lives here now.

    NOT EVERY FIELD APPLIES TO EVERY ROBOT. A Prime (CLOUD_ONLY) entry
    leaves the Classic health-tracking fields at their defaults and
    vice versa, because callbacks.py, repairs.py and sensor_cloud.py
    are Classic-only paths today. Read a default value as "this path
    never ran", not as "the robot reported nothing" -- the two look
    identical from here and mean very different things.
    """

    blid: str
    # NEW (V4/Prime): Optional, not required -- a CLOUD_ONLY entry has no
    # local Roomba object at all. Moved ahead of `blid` in declaration
    # order for exactly this reason (dataclass fields without a default
    # can't follow one that has a default; blid has none and applies to
    # both connection types, roomba now has a default and doesn't apply
    # to both).
    roomba: Roomba | None = None
    # NEW (V4/Prime): defaults to LOCAL_PUSH so every existing entry
    # (which predates this field entirely) is treated exactly as before.
    connection_type: ConnectionType = ConnectionType.LOCAL_PUSH
    # NEW (V4/Prime): populated only for CLOUD_ONLY entries, by
    # _async_setup_entry_prime() in __init__.py.
    prime_robot: "PrimeRobot | None" = None
    #: Saved favourites as [{id, name}], read once at setup. Exposed as
    #: a vacuum attribute so automations and the map card can use them
    #: without an entity each.
    prime_favorites: list[dict[str, Any]] = field(default_factory=list)
    #: Live positions from the Prime map stream, as (x_mm, y_mm, deg).
    #:
    #: Held here rather than on an entity because the two halves live in
    #: different places: the stream is watched by PrimeMapImage, which
    #: shows iRobot's own rendered PNG and has no renderer, while the
    #: trail belongs on PrimeRoomsImage, which draws its own map.
    #:
    #: Bounded, because a long mission would otherwise grow without
    #: limit -- a tester's single run produced 904 points.
    prime_positions: list[tuple[float, float, float]] = field(default_factory=list)
    prime_coordinator: "PrimeCoordinator | None" = None
    prime_status_coordinator: "PrimeStatusCoordinator | None" = None
    #: Consumable parts (filter, brushes, pads, dirt bag). The only
    #: POLLING coordinator here -- parts come from REST, nothing pushes
    #: them. See its own docstring for why it polls rarely.
    prime_parts_coordinator: "PrimePartsCoordinator | None" = None
    # NEW: household_id for THIS robot, resolved once via
    # PrimeRobot.get_household_id() during _async_setup_entry_prime() --
    # needed for get_schedules()/PrimeScheduleCalendar (calendar.py).
    # None if it couldn't be resolved (account/response shape edge case,
    # or genuinely no household found) -- calendar.py's own CLOUD_ONLY
    # branch treats that as "schedule data unavailable", not an error.
    prime_household_id: str | None = None
    # NEW: model/serial/firmware-adjacent data for a correct DeviceInfo (see
    # IRobotEntity.__init__'s own docstring for the bug this fixes -- every
    # Prime entity's device page previously showed no model/serial at all).
    # Best-effort, same reasoning as prime_household_id above.
    prime_serial_info: "RobotSerialInfo | None" = None
    map_capability: MapCapability = MapCapability.NONE
    renderer: MapRenderer | None = None
    geometry_store: GeometryStore | None = None
    maintenance_store: MaintenanceStore | None = None
    # Optional cloud coordinator — None when no credentials or non-SMART robot
    cloud_coordinator: IrobotCloudCoordinator | None = None
    # v3.3.0 MISSION-MAP — in-memory TTL cache for per-mission coverage
    # payloads: {record_id: (fetched_epoch, payload)}. Deliberately NOT a
    # persistent store: cloud coverage data is retrievable without
    # degradation (boutXIII field data); persistence would duplicate a
    # reliable source. See MISSION-MAP-ARCHIVE backlog candidate for the
    # opt-in freeze path.
    mission_map_cache: dict = field(default_factory=dict)
    # Optional blocking manager — None when CONF_BLOCKING_SENSORS not configured
    blocking_manager: BlockingManager | None = None
    # NEW (this session): live-map decode statistics, populated by
    # PrimeMapImage and read by diagnostics. Lives here rather than on
    # the entity so diagnostics can reach it without locating the
    # entity instance -- see PrimeMapImage.__init__ for why it's
    # tracked at all.
    live_map_stats: dict[str, Any] | None = None  # v1.7.0 L5
    # v1.8.0 — Mission log, presence scheduling, and error state
    mission_store: MissionStore | None = None
    presence_manager: PresenceManager | None = None
    last_error_code: int | None = None      # persisted via MissionStore on load
    last_error_at: str | None = None        # ISO datetime string
    last_error_zone: str | None = None      # zone name at last error time

    # Latest sensor values cached so repair check functions can read them
    # without importing sensor.py (avoids circular imports).
    #
    # FOUR SIBLINGS REMOVED (this session): consecutive_declining_speed,
    # consecutive_battery_warn, dirt_density_rising and
    # recharge_fraction_value were left behind when v3.5.0 removed the
    # F6a/F6b Repair Issues they fed. Two were never written at all;
    # two were recomputed on every cloud update -- including a median
    # over ten mission records, twice over, for a consumer that had not
    # existed for two minor versions.
    cleaning_speed_trend_value: str | None = None   # "improving"|"stable"|"declining"|"unknown"
    battery_retention_value: float | None = None

    # F6f — battery contact/bus-communication anomaly detection. A real
    # contact problem can both (a) cause an implausible instantaneous
    # jump in batPct (the BMS link drops and recovers, not the chemistry
    # changing) and (b) manifest as the per-charge-cycle peak declining
    # over successive cycles (intermittent contact reduces effective
    # charge transferred each cycle). Both feed the same repair issue —
    # see repairs.py::async_check_battery_contact_issue.
    # THESE SIX ARE ONE STATE MACHINE, not six independent values.
    # async_check_battery_contact_issue() is their only reader AND their
    # only writer, and the invariants between them live nowhere else:
    #
    #   - current_charge_cycle_peak belongs to the cycle IN PROGRESS and
    #     is cleared when that cycle ends
    #   - charge_cycle_peaks only ever gains an entry at that moment,
    #     and stays bounded to _CHARGE_PEAK_HISTORY_LEN
    #   - was_charging is the edge detector the other two depend on --
    #     set it without the rest and a cycle is silently lost or
    #     counted twice
    #   - last_batpct_value and last_batpct_at are a pair; a value with
    #     a stale timestamp yields a nonsense rate
    #
    # Writing any of them from anywhere else would break those
    # invariants with no error and no obvious symptom -- the counters
    # would simply drift, and a battery-contact problem would be
    # detected late or not at all.
    #
    # DELIBERATELY NOT extracted into its own object yet. The obvious
    # argument for extracting -- protecting the invariants from other
    # modules -- does not apply while exactly one function touches
    # them. And repairs.py is expected to gain a Prime path, which will
    # NOT have the same inputs (Prime exposes no equivalent of
    # bbchg.smberr). Designing the shared shape now would mean
    # inventing an interface for a caller that does not exist yet,
    # against a requirement already known to differ. Better done when
    # the second case is real.
    last_batpct_value: float | None = None
    last_batpct_at: float | None = None   # time.monotonic() of last_batpct_value
    consecutive_battery_contact_anomaly: int = 0
    current_charge_cycle_peak: float | None = None
    charge_cycle_peaks: list = field(default_factory=list)   # bounded, most-recent-last
    was_charging: bool = False   # edge-detect charge-cycle start/end

    # v2.2.0 — GridStore for occupancy heatmap and stuck-cell analysis (F9)
    grid_store: GridStore | None = None
    room_seg_store: RoomSegStore | None = None
    # v2.3.0 — UMF spatial fusion aligner (SMART + EPHEMERAL when Q7 confirmed)
    umf_aligner: UmfAligner | None = None
    # v2.4.0 — Demand-based cleaning trigger (F11, SMART + cloud only)
    dirt_threshold_manager: "DirtThresholdManager | None" = None
    # v2.4.0 — Room outline accumulator (F-EPHEMERAL, 900-series only)
    outline_store: "OutlineStore | None" = None
    # v3.2.1 — bounded last-N-missions trajectory history (F-EPHEMERAL,
    # 900-series only). Data-collection scaffolding: MapRenderer resets
    # its own path every mission by design, so this is the only place a
    # "last few missions" view or future curvature-based structural
    # signal could read multi-mission path data from.
    trajectory_store: "MissionTrajectoryStore | None" = None
    # v3.2.1 — periodic immutable RoomSeg+Outline backup (F-EPHEMERAL,
    # 900-series only), insurance against the firmware-3.20.7-class
    # pose-delivery cutoff risk (see RoomSeg v2 design doc Abschnitt 0).
    freeze_snapshot_store: "FreezeSnapshotStore | None" = None
    # v2.5.0 — Manufacturer reference profile for self-calibrating features (RF0)
    robot_profile: "RobotProfile | None" = None
    # v2.6.0 — Centralised learned state store (L4)
    robot_profile_store: "RobotProfileStore | None" = None
    # v2.6.0 MS1 — Timestamp set when DirtThresholdManager fires a start command.
    # callbacks.py checks this within 30 s to stamp initiator="demand" on the record.
    demand_triggered_ts: float | None = None
    # v2.6.0 MP1 — Persistent mission run-timer (SMART + cloud only)
    mission_timer_store: "MissionTimerStore | None" = None
    # v2.8.0 ARC1 — CloudMissionArchive (cloud + any map_capability)
    mission_archive: "MissionArchive | None" = None  # noqa: F821 — TYPE_CHECKING forward reference, pyflakes/ruff scope limitation
    # v2.2.0 — user-assigned floor name for household REST endpoint (F10a)
    floor_label: str = ""

    # v2.8.3 — MQTT-watchdog: wall-clock timestamp of the last received MQTT
    # message.  Written by the paho-MQTT thread in callbacks.py; read by the
    # RoombaMqttStale binary sensor on its 60-second tick.  Python's GIL makes
    # float reads/writes atomic so no explicit locking is needed.
    # 0.0 = no message received yet (watchdog must not fire until first message).
    last_mqtt_message_ts: float = 0.0

    # v3.2.1 — MQTT-watchdog resume grace: wall-clock timestamp of the last
    # observed phase transition INTO "run" from any non-run phase (fresh
    # start, resume after recharge, stuck recovery).  Written by
    # make_mqtt_stamp_callback in callbacks.py; read by RoombaMqttStale.is_on
    # to grant the same undock grace a fresh start already gets via
    # mssnStrtTm — which a resume cannot use, because mssnStrtTm keeps the
    # original mission start (field-confirmed: 2h20 old at resume, grace
    # long expired → false "Problem" blip at every Zwischenladung resume).
    # 0.0 = no run transition observed yet (e.g. HA restarted mid-mission;
    # the mssnStrtTm grace path still covers that case).
    last_run_transition_ts: float = 0.0

    # v2.8.3 — FW-SENSOR: firmware version tracking.
    # last_firmware_version: most recent non-None softwareVer seen from MQTT.
    # firmware_updated_at: wall-clock timestamp when softwareVer last changed
    #   (None until a change is detected; stays set for 24 h to keep the
    #   firmware_updated binary sensor ON).
    last_firmware_version: str | None = None
    firmware_updated_at: float | None = None

    def roomba_reported_state(self) -> dict[str, Any]:
        """Return the reported state dict from master_state.

        ``or {}`` coerces an explicit null (``{"state": null}``) from a sparse
        MQTT frame to an empty dict; a dict default would only guard a missing
        key, not a present-but-null value.

        NEW (V4/Prime): self.roomba is None for CLOUD_ONLY entries -- returns
        {} rather than crashing. Honest, not fabricated: there is currently
        no master_state-shaped translation for V4/Prime data at all (see
        ConnectionType's docstring) -- any code path that ends up calling
        this for a CLOUD_ONLY entry should get "no data available", not a
        guess.
        """
        if self.roomba is None:
            return {}
        return (self.roomba.master_state.get("state") or {}).get("reported") or {}

    @property
    def has_cloud(self) -> bool:
        """True when the cloud coordinator is active and has fetched data."""
        return (
            self.cloud_coordinator is not None
            and self.cloud_coordinator.data is not None
        )


# Typed config entry — gives full IDE type safety throughout the integration
type RoombaConfigEntry = ConfigEntry[RoombaData]
