"""RobotProfileStore — centralised learned state for Roomba+ self-calibration.

Persistent home for all machine-learned model state that accumulates across HA
restarts. Separates learned data from raw data stores and exposes a reset()
action so users can wipe learned patterns (e.g. after moving house) without
losing mission history.

Lifecycle:
  - Instantiated once in async_setup_entry.
  - Store in entry.runtime_data.robot_profile_store.
  - Call async_load() before reading any values.
  - Call async_save() after any write operation.
  - async_reset() wipes all learned fields and saves immediately.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
import math
import statistics
import time
from datetime import timezone
from dataclasses import dataclass, field
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store
from homeassistant.util import dt as dt_util

_LOGGER = logging.getLogger(__name__)

STORAGE_KEY_PREFIX = "roomba_plus_robot_profile"
STORAGE_VERSION = 1

# v3.3.0 CROSS-CORR — external-sensor correlation.
_CORR_MIN_SAMPLES = 30          # Pearson only meaningful from here (spec)
_CORR_MAX_SAMPLES = 120         # bounded history per entity
_CORR_PAIR_TOLERANCE_SEC = 3 * 3600  # snapshot ↔ record pairing window

# v3.3.0 DIRT-VEL — minimum gap between two cleanings of the same room
# before a velocity sample is taken. Guards against division blow-up when
# a room is cleaned twice within hours (demand clean after scheduled run).
_DIRT_VEL_MIN_GAP_DAYS = 0.25

# EMA decay factor for per-room dirtiness index (L5).
# α = 0.2 gives a slow-decay signal: new missions have 20 % weight,
# history retains 80 %. Stable after ~10 missions per room.
_ROOM_DIRT_EMA_ALPHA = 0.2

# Minimum number of missions before coverage_baseline is established (L6).
_COVERAGE_BASELINE_MIN_MISSIONS = 20

# v3.1.0 L9-MAP — minimum missions before reloc_baseline is established.
# Lower than coverage's 20: reLc is a simpler, more direct signal (each
# relocalisation is an unambiguous navigation event, unlike coverage ratio
# which is influenced by furniture rearrangement, cleaning mode, etc.) so
# fewer observations are needed for a stable personal baseline.
_RELOC_BASELINE_MIN_MISSIONS = 15
# v3.5.0 Repairs redesign — reloc_alert_triggered()'s fixed 3.0x multiplier
# is gone: reLc is zero-inflated (many robots show reLc=0 for their entire
# history, e.g. Thonno's i7+), and a fixed multiplier against a near-zero
# baseline either never fires or hair-triggers on the very first nonzero
# reading. Replaced by reloc_percentile_rank() — ranks the current window
# against this robot's OWN historical distribution (see _RELOC_HISTORY_LEN
# below), no fixed threshold anywhere. This is also why the check moved
# from a Repair Issue to a plain sensor attribute: percentile rank is
# information for the user to threshold themselves, not a judgment call
# this integration should make on their behalf.
# Recent-window size for the trigger check, mirrors DRIFT-AUTO's pattern.
_RELOC_WINDOW = 10
# Bounded longer-run history for reloc_percentile_rank()'s reference
# distribution. ~2-3 months of missions at typical usage — long enough for
# a meaningful percentile, bounded so storage never grows unbounded.
_RELOC_HISTORY_LEN = 60

# v3.1.0 L9-BATTERY — minimum estCap observations before the noise-floor
# (standard deviation) baseline is trusted. Field data (Thonno's i7+, 8
# observations over 70 missions) showed estCap oscillating ±10-15mAh with
# no clear monotonic trend — a near-new battery's measurement noise, not
# degradation. 10 is intentionally low (vs reloc's 15) since estCap updates
# once per mission and a slow-changing signal needs fewer samples to
# characterise its noise floor than a sparse event-count signal does.
_ESTCAP_NOISE_MIN_SAMPLES = 10

# v3.2.1 DOCK-ANCHOR — dock_theta_baseline: learned reference heading for
# "what theta does the firmware report when genuinely docked". Needed
# because, unlike dock POSITION (0,0 by definition, never needs learning),
# dock THETA depends on the dock's physical orientation in the room, which
# nothing tells us in advance — only observing enough undisturbed
# (non-buffered) dockings can. See Dock_Anchor_Korrektur_Plan.md for the
# full rationale (why v2/rotation correction cannot start from an
# unvalidated first observation without risking a systematic, confidently
# wrong rotation baked into every future mission).
#
# Deliberately NOT the same pattern as coverage_baseline/reloc_baseline
# (pure mission-count thresholds, no variance check): those are left
# untouched (already productive, no evidence they fire too early/late).
# dock_theta_baseline adds a stdev gate on top of a small count floor,
# because the physical reasoning here specifically predicts fast, tight
# convergence (mechanically forced alignment via the charging contacts —
# unlike coverage_ratio's genuine furniture/mode-driven variability, or
# reloc's genuine navigation-behaviour drift) — a pure low count floor
# risks mistaking a few coincidentally-similar early readings for
# established convergence (the same trap as an early, too-small sample
# looking deceptively consistent).
_DOCK_THETA_MIN_SAMPLES = 5
# Circular standard deviation threshold, in degrees. Tunable — deliberately
# left as a round, conservative starting guess pending real field
# validation (see design doc); not derived from any dataset yet.
_DOCK_THETA_STDEV_THRESHOLD_DEG = 5.0

# A degradation_rate must exceed the learned noise floor by this multiple
# before _estimated_battery_eol trusts it enough to extrapolate from.
# Conservative: with only oscillating, non-degrading field data so far,
# erring toward "insufficient evidence, return None" is safer than
# projecting a wild EOL date off measurement noise (the bug this fixes —
# see comment in _estimated_battery_eol).
_ESTCAP_NOISE_SIGNIFICANCE_MULTIPLIER = 2.0
# Sanity cap: an extrapolated remaining-cycle count beyond this is treated
# as "noise produced an absurd projection" rather than a genuine multi-decade
# estimate, regardless of whether it technically passed the significance
# check. ~10000 cycles at roughly 1 charge/day is ~27 years — well beyond
# any plausible robot/battery service life, so a result this large is a
# signal the math broke down, not useful information for the user.
_ESTCAP_REMAINING_CYCLES_SANITY_CAP = 10_000
# Fallback significance threshold used when this robot's own noise floor
# isn't learned yet (degradation_rate_is_significant()). Chosen well above
# the noise observed in field data (Thonno's i7+: degradation_rate ranged
# roughly 0.0001-0.0003 %/cycle from pure measurement jitter) but well
# below a genuine degradation case (e.g. 90% retention over 300 cycles =
# 0.033 %/cycle) — conservative enough to filter obvious noise while still
# letting clear degradation surface immediately rather than waiting through
# the full _ESTCAP_NOISE_MIN_SAMPLES learning period.
_ESTCAP_FALLBACK_MIN_RATE = 0.01

# v3.2.0 L10 — minimum days in the REFERENCE period (the portion of
# history strictly before the current comparison window) before that
# period's mean/stdev is trusted for trend classification. Structurally
# different population from estcap's 10 samples-per-mission: health_score
# itself already requires >=20 missions in a 30-day window to be non-None
# at all (see compute_health_score's own calibration gate), and is
# snapshotted at most once per calendar day — so by the time any history
# exists, substantial mission data already backs it. 14 chosen to match
# the Repair Issue's own 14-day persistence trigger, but derived
# independently: enough days for a first reasonable spread estimate
# without an unnecessarily long wait.
_HEALTH_SCORE_BASELINE_MIN_DAYS = 14
# How many of the most recent days' scores form the "current" window
# compared against the lifetime baseline.
_HEALTH_SCORE_RECENT_WINDOW_DAYS = 14
# v3.2.0 bug-hunt fix — how many of the most recent days are excluded
# from the REFERENCE set, deliberately larger than
# _HEALTH_SCORE_RECENT_WINDOW_DAYS. The original design excluded exactly
# _HEALTH_SCORE_RECENT_WINDOW_DAYS (14) from the reference — which meant
# a decline lasting LONGER than 14 days started bleeding its own older
# days back into the "reference" set used to judge it, inflating that
# reference's mean/stdev and masking the very decline it was supposed to
# detect (reproduced directly: a 25-day decline from 90->60 was
# classified "stable" with declining_days=0 under the old exclusion
# width). A wider exclusion (30) creates a quarantine gap between the
# recent window (last 14 days) and the reference window (everything
# before day -30) — days -30..-14 count toward neither, so a decline
# that started anywhere in that gap can't contaminate the reference
# mean/stdev. Doesn't eliminate the underlying issue (a decline lasting
# longer than this buffer would eventually contaminate it too), just
# raises the threshold well past the 14-day point the Repair Issue
# actually triggers at.
_HEALTH_SCORE_REFERENCE_EXCLUSION_DAYS = 30
# Same significance-multiplier philosophy as L9-BATTERY's noise floor:
# only classify improving/declining when the recent-window mean deviates
# from this robot's own learned baseline by more than this multiple of its
# own learned stdev — otherwise it's ordinary day-to-day score noise, not
# a genuine trend. No field data yet to calibrate against, so this starts
# at the same conservative 2.0 used for L9-BATTERY.
_HEALTH_SCORE_SIGNIFICANCE_MULTIPLIER = 2.0
# Fallback absolute-point threshold used only while the baseline isn't
# ready yet (same "insufficient evidence, don't overclaim" spirit as
# _ESTCAP_FALLBACK_MIN_RATE) — high enough that only an unambiguous swing
# would classify as a trend before real personal calibration exists.
_HEALTH_SCORE_FALLBACK_MIN_DEVIATION = 10.0
# Rolling history retention window.
_HEALTH_SCORE_HISTORY_MAX_DAYS = 90


@dataclass
class RobotProfileStore:
    """Centralised store for all self-calibrated learned robot state.

    Fields
    ------
    Maintenance (migrated from L2 in MaintenanceStore — mirrors are kept
    there for backward compat; this store is the canonical source for
    RobotProfileStore consumers):
        learned_filter_hours    — median filter replacement interval, hours
        learned_brush_hours     — median brush replacement interval, hours

    Dirt patterns (L1 data, mirrored from DirtThresholdManager):
        baseline_by_weekday     — {0-6: median dirt density} for weekday-aware baseline

    Per-room dirtiness index (L5):
        room_dirt_index         — {rid: EMA of passCount/m²} per room

    Mission statistics (L3 anomaly baseline):
        mission_duration_mean   — rolling mean of mission duration_min
        mission_duration_std    — rolling std of mission duration_min
        mission_area_mean       — rolling mean of area_sqft

    Coverage baseline (L6):
        coverage_baseline       — personal edge_coverage_ratio baseline
        coverage_mission_count  — number of missions used in baseline
    """

    # Maintenance (read-only mirrors — written by MaintenanceStore)
    learned_filter_hours: float | None = None
    learned_brush_hours: float | None = None

    # Dirt patterns (0=Mon … 6=Sun → median dirt density)
    baseline_by_weekday: dict[int, float] = field(default_factory=dict)

    # Per-room dirtiness index: rid → EMA(passCount / area_m2)
    room_dirt_index: dict[str, float] = field(default_factory=dict)
    # v3.3.0 DIRT-VEL — per-room dirt ACCUMULATION VELOCITY:
    # observed density of a cleaning divided by days since the previous
    # cleaning of that room, EMA-smoothed. Units: (passCount/m²) per day.
    # High velocity → room re-dirties fast → ROOM-SCHED daily suggestion.
    room_dirt_velocity: dict[str, float] = field(default_factory=dict)
    # v3.3.0 DIRT-VEL — wall-clock ts of the last index update per room.
    room_dirt_last_ts: dict[str, float] = field(default_factory=dict)
    # v3.3.0 CROSS-CORR — one pending mission-start snapshot
    # ({"ts": epoch, "values": {entity_id: float}}); persisted so an HA
    # restart mid-mission does not lose the pair. Only one mission runs
    # at a time, so a single slot suffices.
    correlation_pending: dict[str, Any] | None = None
    # v3.3.0 CROSS-CORR — paired samples per external entity:
    # {entity_id: [[sensor_value_at_start, mission_dirt], ...]}
    correlation_samples: dict[str, list[list[float]]] = field(default_factory=dict)

    # Mission statistics (for L3 anomaly baseline, consolidated here for L8)
    mission_duration_mean: float | None = None
    mission_duration_std: float | None = None
    mission_area_mean: float | None = None

    # Navigation efficiency baseline (L6)
    coverage_baseline: float | None = None
    coverage_mission_count: int = 0

    # v3.1.0 L9-MAP — self-calibrating relocalisation-rate baseline.
    # reloc_baseline: personal running-mean of reLc per mission.
    # reloc_mission_count: observations used in the baseline (separate
    # counter from coverage_mission_count — not every mission necessarily
    # has mssnNavStats present, e.g. 600/900-series robots lack it entirely).
    # recent_relocs: bounded window of the most recent reLc values, used to
    # detect a CURRENT elevated rate vs. the established personal baseline.
    # reloc_history: v3.5.0 — bounded longer-run history of per-mission reLc
    # values, used for reloc_percentile_rank() (see below). Separate from
    # recent_relocs (the short "current" window) — this is the reference
    # distribution the current window gets ranked against.
    reloc_baseline: float | None = None
    reloc_mission_count: int = 0
    recent_relocs: list[int] = field(default_factory=list)
    reloc_history: list[int] = field(default_factory=list)

    # v3.1.0 L9-BATTERY — self-calibrating estCap noise-floor baseline.
    # Welford's online algorithm for numerically stable running mean/variance
    # (avoids the precision loss of naive sum-of-squares accumulation, which
    # matters here since estCap values are in the thousands and the noise
    # being measured is single-digit-to-low-double-digit mAh).
    estcap_noise_mean: float | None = None
    estcap_noise_m2: float = 0.0   # Welford's running sum of squared deviations
    estcap_noise_count: int = 0

    # v3.2.1 DOCK-ANCHOR — dock_theta_baseline via circular statistics
    # (running sum of unit vectors, NOT a linear Welford mean/M2 — theta
    # wraps around at 360°/0°, where a naive linear mean would be wrong,
    # e.g. mean of 359° and 1° must be 0°, not 180°). See
    # _DOCK_THETA_MIN_SAMPLES docstring for the full rationale.
    dock_theta_sin_sum: float = 0.0
    dock_theta_cos_sum: float = 0.0
    dock_theta_count: int = 0
    # Last observed converted-mAh estCap value, used to compute the delta fed
    # into update_estcap_noise(). Separate from baseline_estcap (the install-time
    # reference in MaintenanceStore) — this tracks reading-to-reading, not
    # reading-to-baseline.
    last_estcap_mah: float | None = None

    # v3.2.0 L10 — 90-day rolling health_score history for trend
    # classification. history: [{"date": "YYYY-MM-DD", "score": float}],
    # newest last, trimmed to _HEALTH_SCORE_HISTORY_MAX_DAYS. No separate
    # running-mean/variance fields — health_score_trend() computes its
    # reference-period mean/stdev on demand from a strictly-older slice of
    # this history (see _reference_scores()), deliberately NOT a
    # continuously-updating lifetime baseline. A lifetime baseline would
    # absorb an ongoing decline into itself and inflate its own variance
    # estimate by mixing pre- and post-decline values, both of which mask
    # the exact trend this is meant to detect.
    health_score_history: list[dict[str, Any]] = field(default_factory=list)

    # v2.9.0 (J) — STALENESS TRACKING for total_cleaned_area (bbrun.sqft /
    # runtimeStats.sqft, the robot's own onboard lifetime area counter).
    # Field-confirmed (980 9-series + aftermarket NiMH battery): this value
    # can remain frozen for weeks at a time while the robot keeps actively
    # cleaning and every OTHER bbrun.* counter (nPanics, nStuck, nEvacs,
    # etc.) keeps incrementing normally — the firmware appears to simply
    # stop pushing sqft/hr/min updates after some point, rather than
    # reporting a wrong VALUE. We cannot make the robot send fresher data,
    # but we can detect and surface "this number hasn't changed in N days"
    # so it isn't mistaken for an accurate live reading.
    lifetime_sqft_last_value: float | None = None
    lifetime_sqft_last_changed_at: str | None = None

    # ── Persistence ───────────────────────────────────────────────────────────

    async def async_load(self, hass: HomeAssistant, entry_id: str) -> None:
        """Load persisted learned state from hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        data: dict | None = await store.async_load()
        if not data:
            _LOGGER.debug("RobotProfileStore: no persisted data for %s", entry_id)
            return
        try:
            lf = data.get("learned_filter_hours")
            self.learned_filter_hours = float(lf) if lf is not None else None
            lb = data.get("learned_brush_hours")
            self.learned_brush_hours = float(lb) if lb is not None else None

            # Weekday baselines — keys stored as strings in JSON, convert to int.
            # `or {}` coerces an explicit null (or a wrong type that isn't a
            # mapping) so .items() can't raise AttributeError on a corrupted
            # persisted store; a dict default only guards a *missing* key.
            raw_wdb = data.get("baseline_by_weekday") or {}
            if not isinstance(raw_wdb, dict):
                raw_wdb = {}
            self.baseline_by_weekday = {int(k): float(v) for k, v in raw_wdb.items()}

            # Per-room dirt index
            raw_rdi = data.get("room_dirt_index") or {}
            if not isinstance(raw_rdi, dict):
                raw_rdi = {}
            self.room_dirt_index = {str(k): float(v) for k, v in raw_rdi.items()}
            # v3.3.0 DIRT-VEL — both fields optional: dumps predating the
            # feature simply lack them (additive, no PAYLOAD bump needed).
            raw_vel = data.get("room_dirt_velocity") or {}
            self.room_dirt_velocity = {str(k): float(v) for k, v in raw_vel.items()}
            raw_ts = data.get("room_dirt_last_ts") or {}
            self.room_dirt_last_ts = {str(k): float(v) for k, v in raw_ts.items()}
            # v3.3.0 CROSS-CORR — additive fields, old dumps lack them
            pend = data.get("correlation_pending")
            self.correlation_pending = pend if isinstance(pend, dict) else None
            raw_corr = data.get("correlation_samples") or {}
            self.correlation_samples = {
                str(k): [[float(a), float(b)] for a, b in v]
                for k, v in raw_corr.items()
                if isinstance(v, list)
            }

            # Mission statistics
            dm = data.get("mission_duration_mean")
            self.mission_duration_mean = float(dm) if dm is not None else None
            ds = data.get("mission_duration_std")
            self.mission_duration_std = float(ds) if ds is not None else None
            am = data.get("mission_area_mean")
            self.mission_area_mean = float(am) if am is not None else None

            # Coverage baseline
            cb = data.get("coverage_baseline")
            self.coverage_baseline = float(cb) if cb is not None else None
            self.coverage_mission_count = int(data.get("coverage_mission_count", 0))

            # v3.1.0 L9-MAP — reloc baseline
            rb = data.get("reloc_baseline")
            self.reloc_baseline = float(rb) if rb is not None else None
            self.reloc_mission_count = int(data.get("reloc_mission_count", 0))
            raw_relocs = data.get("recent_relocs", [])
            self.recent_relocs = [int(v) for v in raw_relocs][-_RELOC_WINDOW:]
            raw_history = data.get("reloc_history", [])
            self.reloc_history = [int(v) for v in raw_history][-_RELOC_HISTORY_LEN:]

            # v3.1.0 L9-BATTERY — estCap noise-floor baseline
            enm = data.get("estcap_noise_mean")
            self.estcap_noise_mean = float(enm) if enm is not None else None
            self.estcap_noise_m2 = float(data.get("estcap_noise_m2", 0.0))
            self.estcap_noise_count = int(data.get("estcap_noise_count", 0))
            # v3.2.1 DOCK-ANCHOR — additive fields, same no-version-bump
            # precedent used throughout this codebase: a payload saved
            # before this existed simply has no such keys.
            self.dock_theta_sin_sum = float(data.get("dock_theta_sin_sum", 0.0))
            self.dock_theta_cos_sum = float(data.get("dock_theta_cos_sum", 0.0))
            self.dock_theta_count = int(data.get("dock_theta_count", 0))
            lec = data.get("last_estcap_mah")
            self.last_estcap_mah = float(lec) if lec is not None else None

            # v3.2.0 L10 — health score history
            raw_history = data.get("health_score_history", [])
            self.health_score_history = [
                {"date": str(entry.get("date")), "score": float(entry.get("score"))}
                for entry in raw_history
                if entry.get("date") is not None and entry.get("score") is not None
            ][-_HEALTH_SCORE_HISTORY_MAX_DAYS:]

            # v2.9.0 (J) — sqft staleness tracking
            lsv = data.get("lifetime_sqft_last_value")
            self.lifetime_sqft_last_value = float(lsv) if lsv is not None else None
            self.lifetime_sqft_last_changed_at = data.get("lifetime_sqft_last_changed_at")

            _LOGGER.debug(
                "RobotProfileStore: loaded — rooms=%d coverage_baseline=%s",
                len(self.room_dirt_index),
                f"{self.coverage_baseline:.3f}" if self.coverage_baseline else "None",
            )
        except (TypeError, ValueError, KeyError, AttributeError) as exc:
            _LOGGER.warning("RobotProfileStore: failed to load data: %s", exc)

    async def async_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Persist all learned state to hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        await store.async_save({
            "learned_filter_hours": self.learned_filter_hours,
            "learned_brush_hours": self.learned_brush_hours,
            "baseline_by_weekday": {str(k): v for k, v in self.baseline_by_weekday.items()},
            "room_dirt_index": self.room_dirt_index,
            "room_dirt_velocity": self.room_dirt_velocity,
            "room_dirt_last_ts": self.room_dirt_last_ts,
            "correlation_pending": self.correlation_pending,
            "correlation_samples": self.correlation_samples,
            "mission_duration_mean": self.mission_duration_mean,
            "mission_duration_std": self.mission_duration_std,
            "mission_area_mean": self.mission_area_mean,
            "coverage_baseline": self.coverage_baseline,
            "coverage_mission_count": self.coverage_mission_count,
            "reloc_baseline": self.reloc_baseline,
            "reloc_mission_count": self.reloc_mission_count,
            "recent_relocs": self.recent_relocs,
            "reloc_history": self.reloc_history,
            "estcap_noise_mean": self.estcap_noise_mean,
            "estcap_noise_m2": self.estcap_noise_m2,
            "estcap_noise_count": self.estcap_noise_count,
            "dock_theta_sin_sum": self.dock_theta_sin_sum,
            "dock_theta_cos_sum": self.dock_theta_cos_sum,
            "dock_theta_count": self.dock_theta_count,
            "last_estcap_mah": self.last_estcap_mah,
            "health_score_history": self.health_score_history,
            "lifetime_sqft_last_value": self.lifetime_sqft_last_value,
            "lifetime_sqft_last_changed_at": self.lifetime_sqft_last_changed_at,
        })

    async def async_reset(self, hass: HomeAssistant, entry_id: str) -> None:
        """Wipe all learned state and persist immediately.

        Called when the user invokes the reset_robot_profile service — e.g.
        after moving house, getting a new robot, or replacing the battery pack.
        Mission history (MissionStore) is unaffected.
        """
        self.learned_filter_hours = None
        self.learned_brush_hours = None
        self.baseline_by_weekday = {}
        self.room_dirt_index = {}
        self.room_dirt_velocity = {}
        self.room_dirt_last_ts = {}
        self.correlation_pending = None
        self.correlation_samples = {}
        self.mission_duration_mean = None
        self.mission_duration_std = None
        self.mission_area_mean = None
        self.coverage_baseline = None
        self.coverage_mission_count = 0
        self.reloc_baseline = None
        self.reloc_mission_count = 0
        self.recent_relocs = []
        self.reloc_history = []
        self.estcap_noise_mean = None
        self.estcap_noise_m2 = 0.0
        self.estcap_noise_count = 0
        self.dock_theta_sin_sum = 0.0
        self.dock_theta_cos_sum = 0.0
        self.dock_theta_count = 0
        self.last_estcap_mah = None
        self.health_score_history = []
        self.lifetime_sqft_last_value = None
        self.lifetime_sqft_last_changed_at = None
        await self.async_save(hass, entry_id)
        _LOGGER.info("RobotProfileStore: reset for entry %s", entry_id)

    # ── Public update API ─────────────────────────────────────────────────────

    def update_from_maintenance_store(
        self,
        learned_filter: float | None,
        learned_brush: float | None,
    ) -> None:
        """Mirror learned maintenance intervals from MaintenanceStore.

        Called after each reset_filter / reset_brush event so this store
        reflects the canonical values for diagnostics and L8 health score.
        """
        self.learned_filter_hours = learned_filter
        self.learned_brush_hours = learned_brush

    def update_room_dirt_index(
        self,
        rid: str,
        pass_count: int,
        area_m2: float,
    ) -> None:
        """Update per-room dirtiness EMA from a completed pass.

        L5 — called after each mission for every room event with status=0 or 6.
        Skips rooms where area_m2 is zero to avoid division errors.

        Args:
            rid: iRobot region ID string.
            pass_count: number of passes the robot made in this room this mission.
            area_m2: room area in square metres from UMF or local accumulation.
        """
        if area_m2 <= 0:
            return
        current_density = pass_count / area_m2

        # v3.3.0 DIRT-VEL — accumulation velocity BEFORE the EMA update:
        # the density observed at this cleaning is the dirt that built up
        # since the PREVIOUS cleaning of this room; divided by the days
        # in between it becomes a per-day accumulation rate. EMA-smoothed
        # with the same alpha as the index for consistent responsiveness.
        now_ts = time.time()
        prev_ts = self.room_dirt_last_ts.get(rid)
        if prev_ts is not None:
            days = (now_ts - prev_ts) / 86400.0
            if days >= _DIRT_VEL_MIN_GAP_DAYS:
                velocity = current_density / days
                old_vel = self.room_dirt_velocity.get(rid)
                if old_vel is None:
                    self.room_dirt_velocity[rid] = velocity
                else:
                    self.room_dirt_velocity[rid] = (
                        _ROOM_DIRT_EMA_ALPHA * velocity
                        + (1 - _ROOM_DIRT_EMA_ALPHA) * old_vel
                    )
        self.room_dirt_last_ts[rid] = now_ts

        if rid in self.room_dirt_index:
            # EMA update: new = α × current + (1-α) × old
            old = self.room_dirt_index[rid]
            self.room_dirt_index[rid] = (
                _ROOM_DIRT_EMA_ALPHA * current_density
                + (1 - _ROOM_DIRT_EMA_ALPHA) * old
            )
        else:
            # First observation — seed with current value
            self.room_dirt_index[rid] = current_density
        _LOGGER.debug(
            "RobotProfileStore: room %s dirt index → %.3f",
            rid, self.room_dirt_index[rid],
        )

    def update_coverage_baseline(self, ratio: float) -> None:
        """Update navigation efficiency baseline with a new mission ratio.

        L6 — called after each mission when edge_coverage_ratio is available.
        Baseline is established after _COVERAGE_BASELINE_MIN_MISSIONS observations
        using a simple running mean (stable signal; EMA would over-weight outliers
        in the initial window before convergence).
        """
        self.coverage_mission_count += 1
        if self.coverage_baseline is None:
            self.coverage_baseline = ratio
        else:
            # Running mean: new_mean = old_mean + (x - old_mean) / n
            n = self.coverage_mission_count
            self.coverage_baseline = self.coverage_baseline + (ratio - self.coverage_baseline) / n
        _LOGGER.debug(
            "RobotProfileStore: coverage baseline → %.3f (n=%d)",
            self.coverage_baseline, self.coverage_mission_count,
        )

    def update_reloc_baseline(self, relocs: int) -> None:
        """v3.1.0 L9-MAP — update the personal relocalisation-rate baseline
        with a new mission's reLc count, push it into the recent window,
        and append it to the longer-run history used by
        reloc_percentile_rank().

        Mirrors update_coverage_baseline()'s running-mean approach (same
        reasoning: stable signal, EMA would over-weight early outliers).
        Called once per completed cleaning mission where mssnNavStats.reLc
        was present in the end-of-mission MQTT payload — gated the same way
        as MissionStore records (had_cleaning_phase), so a robot that never
        actually cleaned won't pollute the baseline with a meaningless
        zero-relocalisation "mission".
        """
        self.reloc_mission_count += 1
        if self.reloc_baseline is None:
            self.reloc_baseline = float(relocs)
        else:
            n = self.reloc_mission_count
            self.reloc_baseline = self.reloc_baseline + (relocs - self.reloc_baseline) / n

        self.recent_relocs.append(relocs)
        self.recent_relocs = self.recent_relocs[-_RELOC_WINDOW:]

        self.reloc_history.append(relocs)
        self.reloc_history = self.reloc_history[-_RELOC_HISTORY_LEN:]

        _LOGGER.debug(
            "RobotProfileStore: reloc baseline → %.3f (n=%d), window=%s",
            self.reloc_baseline, self.reloc_mission_count, self.recent_relocs,
        )

    @property
    def reloc_baseline_ready(self) -> bool:
        """True once enough missions have contributed to reloc_baseline to
        trust it for display."""
        return (
            self.reloc_baseline is not None
            and self.reloc_mission_count >= _RELOC_BASELINE_MIN_MISSIONS
        )

    def reloc_percentile_rank(self) -> float | None:
        """v3.5.0 — where the current recent-window mean sits within this
        robot's OWN historical reLc distribution, as a 0-100 percentile.

        Self-calibrating with no fixed threshold anywhere (replaces the old
        reloc_alert_triggered()'s fixed 3.0x multiplier, which either never
        fired or hair-triggered depending on how close the personal baseline
        sat to zero — reLc is zero-inflated, so a fixed multiplier against
        a near-zero baseline was never a stable comparison). Ties are
        handled via mean-rank ((count strictly below + half the ties) /
        total): on a robot whose history is mostly zero, a current reading
        of 0 lands around the 50th percentile — a typical reading — rather
        than misleadingly showing as either extreme.

        Returns None until enough history has accumulated
        (_RELOC_BASELINE_MIN_MISSIONS missions) to make a percentile rank
        meaningful. This is deliberately just a number, not a verdict — the
        integration doesn't decide what counts as "elevated" for you;
        automate on this value with whatever threshold matters to you.

        Known limitation, worth being upfront about: this is a rank
        statistic, so it reflects whether the current window is unusual
        for this robot, not by how much. Two differently-sized sustained
        increases that produce the same window shape (e.g. the same
        _RELOC_WINDOW-length run of uniform values against the same older
        baseline) can rank identically — rank statistics discard magnitude
        by design. If per-mission raw reLc values ever need to be compared
        by size rather than rank, reloc_history itself is available
        directly for that; this method intentionally answers "is this
        typical for this robot" rather than "how far off is this".
        """
        if len(self.reloc_history) < _RELOC_BASELINE_MIN_MISSIONS or not self.recent_relocs:
            return None
        current = sum(self.recent_relocs) / len(self.recent_relocs)
        less = sum(1 for v in self.reloc_history if v < current)
        equal = sum(1 for v in self.reloc_history if v == current)
        total = len(self.reloc_history)
        return round((less + 0.5 * equal) / total * 100, 1)

    def update_estcap_noise(self, estcap_delta: float) -> None:
        """v3.1.0 L9-BATTERY — feed one estCap-vs-previous-reading delta into
        the running noise-floor baseline using Welford's online algorithm.

        Called with the per-mission CHANGE in estCap (current - previous),
        not the raw estCap value itself — the baseline characterises how
        much estCap normally jitters between consecutive readings on this
        specific robot, which is what determines whether a later sustained
        decline is real degradation or just more of the same noise.
        """
        self.estcap_noise_count += 1
        delta = estcap_delta - (self.estcap_noise_mean or 0.0)
        if self.estcap_noise_mean is None:
            self.estcap_noise_mean = estcap_delta
        else:
            self.estcap_noise_mean += delta / self.estcap_noise_count
        delta2 = estcap_delta - self.estcap_noise_mean
        self.estcap_noise_m2 += delta * delta2

    @property
    def estcap_noise_stdev(self) -> float | None:
        """Sample standard deviation of estCap deltas, or None if not enough
        observations yet (Welford's M2/(n-1) is undefined for n<2)."""
        if self.estcap_noise_count < 2:
            return None
        return (self.estcap_noise_m2 / (self.estcap_noise_count - 1)) ** 0.5

    @property
    def estcap_noise_ready(self) -> bool:
        """True once enough delta observations exist to trust the noise floor."""
        return self.estcap_noise_count >= _ESTCAP_NOISE_MIN_SAMPLES

    def update_dock_theta_baseline(self, theta_deg: float) -> None:
        """Feed one CLEAN (non-buffered, undisturbed) dock-contact theta
        reading into the circular running baseline.

        Only ever call this for dockings NOT preceded by a stuck-event
        buffering phase — a disturbed docking's theta is exactly the
        unreliable reading this baseline must not be contaminated by.

        Uses running sums of sin/cos (a standard circular-statistics
        technique) rather than Welford's linear mean/variance: theta is
        an angle, and averaging raw degree values directly breaks at the
        0°/360° wraparound.
        """
        rad = math.radians(theta_deg)
        self.dock_theta_sin_sum += math.sin(rad)
        self.dock_theta_cos_sum += math.cos(rad)
        self.dock_theta_count += 1
        _LOGGER.debug(
            "RobotProfileStore: dock_theta_baseline -> %.1f° (n=%d, stdev=%s)",
            self.dock_theta_baseline or 0.0, self.dock_theta_count,
            f"{self.dock_theta_circular_stdev_deg:.2f}"
            if self.dock_theta_circular_stdev_deg is not None else "n/a",
        )

    @property
    def dock_theta_baseline(self) -> float | None:
        """Circular mean heading at dock contact, in degrees [0, 360),
        or None with zero observations so far."""
        if self.dock_theta_count == 0:
            return None
        mean_rad = math.atan2(
            self.dock_theta_sin_sum / self.dock_theta_count,
            self.dock_theta_cos_sum / self.dock_theta_count,
        )
        return math.degrees(mean_rad) % 360.0

    @property
    def dock_theta_resultant_length(self) -> float | None:
        """Mean resultant vector length R ∈ [0, 1] — 1.0 means every
        observation had (near-)identical theta, 0.0 means uniformly
        scattered with no consistent heading at all. None with zero
        observations."""
        if self.dock_theta_count == 0:
            return None
        n = self.dock_theta_count
        return (
            (self.dock_theta_sin_sum / n) ** 2 + (self.dock_theta_cos_sum / n) ** 2
        ) ** 0.5

    @property
    def dock_theta_circular_stdev_deg(self) -> float | None:
        """Circular standard deviation in degrees (Mardia's definition:
        sqrt(-2 ln R)). None if R is at or near 0 (undefined — maximally
        scattered; a small epsilon guards against floating-point residue
        from summed sin/cos never landing at EXACTLY 0.0 even for
        perfectly cancelling angles) or with zero observations."""
        r = self.dock_theta_resultant_length
        if r is None or r <= 1e-9:
            return None
        return math.degrees((-2.0 * math.log(r)) ** 0.5)

    @property
    def dock_theta_baseline_ready(self) -> bool:
        """True once enough CLEAN dock observations exist AND they're
        tight enough (circular stdev under threshold) to trust the
        baseline for v2 rotation correction. Both conditions required —
        see _DOCK_THETA_MIN_SAMPLES docstring for why a count-only gate
        isn't enough here."""
        if self.dock_theta_count < _DOCK_THETA_MIN_SAMPLES:
            return False
        stdev = self.dock_theta_circular_stdev_deg
        return stdev is not None and stdev <= _DOCK_THETA_STDEV_THRESHOLD_DEG

    def record_estcap_observation(self, current_estcap_mah: float) -> None:
        """v3.1.0 L9-BATTERY — record one estCap reading, computing the delta
        against the previous reading and feeding it into the noise-floor
        baseline. Call once per mission/charge-cycle when estCap is available.

        The first call only seeds last_estcap_mah (no delta exists yet to
        feed the baseline with).
        """
        if self.last_estcap_mah is not None:
            self.update_estcap_noise(current_estcap_mah - self.last_estcap_mah)
        self.last_estcap_mah = current_estcap_mah

    def degradation_rate_is_significant(self, degradation_rate: float, cycles: int) -> bool:
        """v3.1.0 L9-BATTERY — True when degradation_rate is large enough to
        be trusted as genuine capacity loss rather than reading-to-reading
        jitter.

        Two paths:
        - Noise baseline ready: compare against this robot's own learned
          noise floor (the precise, self-calibrated check).
        - Noise baseline not yet ready: fall back to a conservative absolute
          threshold (_ESTCAP_FALLBACK_MIN_RATE) so a robot with obvious,
          large degradation isn't forced to wait through the full learning
          period before estimated_battery_eol can say anything at all — only
          truly small, noise-plausible rates are withheld in this case.
        """
        if not self.estcap_noise_ready:
            return degradation_rate >= _ESTCAP_FALLBACK_MIN_RATE
        stdev = self.estcap_noise_stdev
        if stdev is None or stdev <= 0:
            return degradation_rate >= _ESTCAP_FALLBACK_MIN_RATE
        observed_total_drop = degradation_rate * max(cycles, 1)
        expected_noise_drift = stdev * (max(cycles, 1) ** 0.5)
        return observed_total_drop > expected_noise_drift * _ESTCAP_NOISE_SIGNIFICANCE_MULTIPLIER

    @staticmethod
    def cap_remaining_cycles(remaining_cycles: float) -> float | None:
        """v3.1.0 L9-BATTERY — sanity cap: a projection beyond
        _ESTCAP_REMAINING_CYCLES_SANITY_CAP is treated as a sign the
        extrapolation broke down (e.g. from a degradation_rate that barely
        cleared the significance check but is still tiny), not as a genuine
        multi-decade estimate. Returns None in that case.
        """
        if remaining_cycles > _ESTCAP_REMAINING_CYCLES_SANITY_CAP:
            return None
        return remaining_cycles

    def record_health_score(self, score: float, today_iso: str) -> None:
        """v3.2.0 L10 — record today's L8 health score into the rolling
        90-day history.

        Idempotent per calendar day: if today_iso already matches the most
        recent history entry's date, that entry's score is updated in place
        rather than appended again (a robot's cloud coordinator can refresh
        more than once per day; only the day's last-known score should
        count once toward the history). Call once per health-score
        computation with a non-None score — the caller (RoombaHealthScoreSensor)
        already skips calling this when the calibration gate isn't met.
        """
        if self.health_score_history and self.health_score_history[-1]["date"] == today_iso:
            self.health_score_history[-1]["score"] = score
            return

        self.health_score_history.append({"date": today_iso, "score": score})
        self.health_score_history = self.health_score_history[-_HEALTH_SCORE_HISTORY_MAX_DAYS:]

        _LOGGER.debug(
            "RobotProfileStore: health_score recorded %.1f for %s (n=%d)",
            score, today_iso, len(self.health_score_history),
        )

    def _reference_scores(self) -> list[float]:
        """The older portion of history, excluding the current comparison
        window AND a quarantine buffer beyond it — deliberately NOT the
        full lifetime history, and deliberately NOT just the
        _HEALTH_SCORE_RECENT_WINDOW_DAYS-sized slice either.

        This is the key correction from an earlier version of this design:
        a lifetime running mean/stdev absorbs an ongoing decline into
        itself (the "baseline" drifts down right along with the thing it's
        supposed to be measuring against), and mixing pre- and post-decline
        values into one variance estimate inflates the noise floor to the
        point a genuine sustained drop no longer clears the significance
        threshold. Keeping the reference window strictly older than the
        recent window avoids that FOR DECLINES SHORTER THAN THE EXCLUSION
        WIDTH — but a decline lasting longer than the original 14-day
        exclusion width bled its own older days back into the reference
        set once enough time passed, silently reproducing the exact
        problem this correction exists to prevent (confirmed directly: a
        25-day 90->60 decline was misclassified "stable"). Excluding
        _HEALTH_SCORE_REFERENCE_EXCLUSION_DAYS (30, wider than the 14-day
        recent window) instead pushes that failure point well past where
        the Repair Issue's own 14-day trigger would already have fired.
        """
        return [
            e["score"]
            for e in self.health_score_history[:-_HEALTH_SCORE_REFERENCE_EXCLUSION_DAYS]
        ]

    @property
    def health_score_stdev(self) -> float | None:
        """Sample standard deviation of the reference (pre-recent-window)
        scores, or None if there aren't enough of them yet."""
        reference = self._reference_scores()
        if len(reference) < 2:
            return None
        return statistics.stdev(reference)

    @property
    def health_score_baseline(self) -> float | None:
        """Mean of the reference (pre-recent-window) scores, or None if
        there isn't a reference period yet. Public counterpart to
        _reference_scores() for callers (e.g. the trend sensor's
        diagnostic attributes) that want the number without reaching into
        the private helper."""
        reference = self._reference_scores()
        if not reference:
            return None
        return statistics.mean(reference)

    @property
    def health_score_baseline_ready(self) -> bool:
        """True once enough reference-period days exist (strictly before
        the current comparison window) to trust a personal baseline for
        trend classification — not just enough days in total."""
        return len(self._reference_scores()) >= _HEALTH_SCORE_BASELINE_MIN_DAYS

    def health_score_trend(self) -> str | None:
        """v3.2.0 L10 — classify the recent trend as 'improving', 'stable',
        or 'declining' relative to this robot's own learned baseline.

        Compares the mean of the most recent _HEALTH_SCORE_RECENT_WINDOW_DAYS
        days against the mean of the reference period before it, judging
        significance against this robot's own learned stdev from that same
        reference period — same self-calibration philosophy as L9-BATTERY's
        degradation_rate_is_significant(), rather than a fixed
        point-difference threshold that would be too strict for a
        naturally noisy robot and too lenient for a stable one.

        Returns None when there isn't enough reference-period history yet
        to say anything (fewer than _HEALTH_SCORE_BASELINE_MIN_DAYS days
        before the current window).
        """
        if not self.health_score_baseline_ready:
            return None

        recent = self.health_score_history[-_HEALTH_SCORE_RECENT_WINDOW_DAYS:]
        reference = self._reference_scores()
        if not recent or not reference:
            return None

        recent_mean = sum(e["score"] for e in recent) / len(recent)
        reference_mean = statistics.mean(reference)
        deviation = recent_mean - reference_mean

        stdev = self.health_score_stdev
        if stdev is None or stdev <= 0:
            threshold = _HEALTH_SCORE_FALLBACK_MIN_DEVIATION
        else:
            threshold = stdev * _HEALTH_SCORE_SIGNIFICANCE_MULTIPLIER

        if deviation < -threshold:
            return "declining"
        if deviation > threshold:
            return "improving"
        return "stable"

    def health_score_declining_days(self) -> int:
        """v3.2.0 L10 — how many of the most recent history entries fall
        below (reference mean - significance threshold), scanning backward
        from the newest entry until the first one that doesn't. Used by the
        Repair Issue's 14-day persistence trigger — a simple debounce count
        layered on top of the self-calibrated significance test above, same
        pattern as async_check_performance_degradation's fixed
        "3 consecutive updates" trigger.
        """
        if not self.health_score_baseline_ready:
            return 0

        reference = self._reference_scores()
        stdev = self.health_score_stdev
        threshold = (
            stdev * _HEALTH_SCORE_SIGNIFICANCE_MULTIPLIER
            if stdev is not None and stdev > 0
            else _HEALTH_SCORE_FALLBACK_MIN_DEVIATION
        )
        cutoff = statistics.mean(reference) - threshold

        count = 0
        for entry in reversed(self.health_score_history):
            if entry["score"] < cutoff:
                count += 1
            else:
                break
        return count

    @staticmethod
    def room_accessibility_scores(
        coverage_by_room: dict[str, float],
        stuck_by_room: dict[str, int],
        time_per_area_by_room: dict[str, float],
    ) -> dict[str, dict[str, Any]]:
        """v3.2.0 ROOM-ACCESS — combine three signals into a 0-100
        accessibility score per room:

          - coverage_by_room: {rid: fraction 0-1} from GridStore.coverage_by_polygon()
          - stuck_by_room: {rid: count} from GridStore.stuck_by_polygon()
          - time_per_area_by_room: {rid: seconds/m2} from
            MissionArchive.time_per_room(), aggregated across missions and
            divided by ROOM-SIZE's room_areas_m2

        Stuck rate and time-per-area are judged against THIS ROBOT's OWN
        average across its OWN rooms — same self-calibration philosophy as
        L9-BATTERY/L10 (a room only counts as a problem relative to how
        this robot's other rooms behave, not a fixed one-size-fits-all
        bar; a robot that's generally slow or generally prone to minor
        stuck events everywhere shouldn't have every single room flagged
        just because it's slower than some external absolute reference).
        Coverage doesn't need this treatment — 100% covered is a
        meaningful absolute target regardless of robot.

        Returns {rid: {"score": float, "limiting_factor": str | None}}.
        limiting_factor is one of "obstacle_density" (stuck sub-score
        lowest), "narrow_passages" (time-efficiency sub-score lowest), or
        "coverage_gap" (coverage sub-score lowest) — None only if a room
        has no signals at all (shouldn't normally happen if it appears in
        coverage_by_room, since that's the primary per-room signal every
        room should have).
        """
        all_rids = set(coverage_by_room) | set(stuck_by_room) | set(time_per_area_by_room)
        if not all_rids:
            return {}

        stuck_values = [v for v in stuck_by_room.values() if v is not None]
        stuck_mean = sum(stuck_values) / len(stuck_values) if stuck_values else 0.0

        time_values = [v for v in time_per_area_by_room.values() if v is not None and v > 0]
        time_mean = sum(time_values) / len(time_values) if time_values else 0.0

        results: dict[str, dict[str, Any]] = {}
        for rid in all_rids:
            components: list[tuple[str, float]] = []

            coverage_val = coverage_by_room.get(rid)
            if coverage_val is not None:
                coverage_score = max(0.0, min(100.0, coverage_val * 100.0))
                components.append(("coverage_gap", coverage_score))

            stuck_val = stuck_by_room.get(rid)
            if stuck_val is not None:
                if stuck_mean <= 0:
                    stuck_score = 100.0
                else:
                    ratio = stuck_val / stuck_mean
                    # At the robot's own average ratio=1.0 -> 100pts;
                    # 3x the average -> 0pts; linear between.
                    stuck_score = max(0.0, min(100.0, 100.0 - (ratio - 1.0) * 50.0))
                components.append(("obstacle_density", stuck_score))

            time_val = time_per_area_by_room.get(rid)
            if time_val is not None and time_val > 0 and time_mean > 0:
                ratio = time_val / time_mean
                time_score = max(0.0, min(100.0, 100.0 - (ratio - 1.0) * 50.0))
                components.append(("narrow_passages", time_score))

            if not components:
                results[rid] = {"score": None, "limiting_factor": None}
                continue

            overall = sum(s for _, s in components) / len(components)
            limiting_name, _ = min(components, key=lambda c: c[1])
            results[rid] = {
                "score": round(overall, 1),
                "limiting_factor": limiting_name,
            }
        return results

    def update_lifetime_sqft_tracking(self, current_sqft: float) -> bool:
        """Compare the current lifetime sqft reading against the last seen
        value; update the "last changed" timestamp only when it actually
        differs.

        v2.9.0 (J) — STALENESS TRACKING. Returns True when the timestamp was
        updated (caller should persist), False when the value is unchanged
        from last time (timestamp deliberately left untouched — that's the
        whole point: an old, never-refreshed timestamp is the signal that
        the firmware has stopped pushing this field).

        First-ever observation (lifetime_sqft_last_value is None) always
        counts as a "change" so a fresh install gets an initial timestamp
        immediately, rather than waiting for a second differing reading.
        """
        if (
            self.lifetime_sqft_last_value is not None
            and current_sqft == self.lifetime_sqft_last_value
        ):
            return False
        self.lifetime_sqft_last_value = current_sqft
        self.lifetime_sqft_last_changed_at = dt_util.now().isoformat()
        return True

    @property
    def lifetime_sqft_days_unchanged(self) -> float | None:
        """Days since the lifetime sqft reading last actually changed.

        None when no observation has been recorded yet. A large value here
        (while the robot has clearly run missions in the meantime) means
        the firmware has stopped refreshing this specific field — see
        update_lifetime_sqft_tracking() docstring.
        """
        if self.lifetime_sqft_last_changed_at is None:
            return None
        try:
            last = dt_util.parse_datetime(self.lifetime_sqft_last_changed_at)
        except (TypeError, ValueError):
            return None
        if last is None:
            return None
        return (dt_util.now() - last).total_seconds() / 86400

    @property
    def coverage_baseline_ready(self) -> bool:
        """True when enough missions have been observed for a stable baseline."""
        return (
            self.coverage_baseline is not None
            and self.coverage_mission_count >= _COVERAGE_BASELINE_MIN_MISSIONS
        )

    def update_mission_stats(
        self,
        records: list[dict[str, Any]],
    ) -> bool:
        """Recompute mission duration/area statistics from recent records.

        L3/L8 — called after each mission from the callback chain (see
        _async_update_robot_profile_store in __init__.py).
        Uses the last 30 days of records passed in by the caller (avoids
        direct MissionStore dependency — cleaner separation of concerns).

        Args:
            records: list of MissionStore record dicts from query(days=30).

        Returns:
            True if mission_duration_mean and/or mission_area_mean was
            (re)computed this call — mirrors update_lifetime_sqft_tracking's
            bool-return convention so the caller's `changed` tracking stays
            consistent across all L-series update_* methods.
        """
        durations = [
            r["duration_min"]
            for r in records
            if isinstance(r.get("duration_min"), int) and r["duration_min"] > 0
        ]
        areas = [
            r["area_sqft"]
            for r in records
            if isinstance(r.get("area_sqft"), (int, float)) and r["area_sqft"] > 0
        ]
        wrote = False
        if len(durations) >= 5:
            self.mission_duration_mean = statistics.mean(durations)
            self.mission_duration_std = (
                statistics.stdev(durations) if len(durations) >= 2 else 0.0
            )
            wrote = True
        if len(areas) >= 5:
            self.mission_area_mean = statistics.mean(areas)
            wrote = True
        return wrote

    def dirt_accumulation_rate(self) -> dict[str, float]:
        """Per-room dirt accumulation velocity in (passCount/m²)/day.

        v3.3.0 DIRT-VEL — consumer helper for the by_room_velocity
        sensor attribute and the ROOM-SCHED daily-cleaning suggestion.
        Returns only rooms with at least one velocity sample (i.e. two
        cleanings spaced >= the minimum gap apart).
        """
        return {rid: round(v, 4) for rid, v in self.room_dirt_velocity.items()}

    def record_correlation_snapshot(
        self, values: dict[str, float], ts: float
    ) -> None:
        """v3.3.0 CROSS-CORR — store the mission-start snapshot of the
        configured external sensors. Overwrites any stale pending
        snapshot (a mission that never produced an enriched record)."""
        clean = {
            str(k): float(v) for k, v in values.items()
            if isinstance(v, (int, float))
        }
        self.correlation_pending = {"ts": float(ts), "values": clean} if clean else None

    def finalize_correlation(
        self, record_started_iso: str | None, dirt: float | None
    ) -> bool:
        """Pair the pending snapshot with the mission's (cloud-enriched)
        dirt count. Returns True when samples were appended.

        Tolerance window: the record's started_at must lie within
        _CORR_PAIR_TOLERANCE_SEC of the snapshot — protects against
        pairing an old orphaned snapshot with an unrelated mission.
        The pending slot clears on ANY finalize attempt with a valid
        record timestamp inside the window (paired) — and stays put
        otherwise, awaiting its own record."""
        if self.correlation_pending is None or dirt is None:
            return False
        if not record_started_iso or not isinstance(record_started_iso, str):
            return False
        started = dt_util.parse_datetime(record_started_iso)
        if started is None:
            return False
        if started.tzinfo is None:
            started = started.replace(tzinfo=timezone.utc)
        delta = abs(started.timestamp() - float(self.correlation_pending["ts"]))
        if delta > _CORR_PAIR_TOLERANCE_SEC:
            return False
        changed = False
        for eid, value in (self.correlation_pending.get("values") or {}).items():
            samples = self.correlation_samples.setdefault(eid, [])
            samples.append([float(value), float(dirt)])
            if len(samples) > _CORR_MAX_SAMPLES:
                del samples[: len(samples) - _CORR_MAX_SAMPLES]
            changed = True
        self.correlation_pending = None
        return changed

    def correlation_results(self) -> dict[str, dict[str, Any]]:
        """Pearson r per configured entity, only from
        _CORR_MIN_SAMPLES (30) onwards — below that the estimate is
        noise, per spec. Zero-variance series (constant sensor) are
        skipped instead of raising. Fully local computation."""
        out: dict[str, dict[str, Any]] = {}
        for eid, samples in self.correlation_samples.items():
            n = len(samples)
            if n < _CORR_MIN_SAMPLES:
                out[eid] = {"r": None, "n": n}
                continue
            xs = [s[0] for s in samples]
            ys = [s[1] for s in samples]
            try:
                r = statistics.correlation(xs, ys)
            except statistics.StatisticsError:
                out[eid] = {"r": None, "n": n}
                continue
            out[eid] = {"r": round(r, 3), "n": n}
        return out

    def suggested_cleaning_interval_days(self) -> dict[str, float]:
        """v3.3.0 ROOM-SCHED (self-calibration) — recommended cleaning
        interval per room, fully self-calibrated:

            suggested = target_density / velocity

        target_density is the HOUSEHOLD MEDIAN of the per-room dirt
        indices — "the dirt level at which this household typically
        cleans" — so both inputs come from the household's own data
        (L9/L10/ROOM-ACCESS philosophy, no arbitrary absolutes).

        Deliberately a RECOMMENDATION only: it never overrides the
        configured or learned interval in the overdue rule. A
        self-adjusting threshold would silently follow a worsening
        habit — the DRIFT-AUTO lifetime-sum lesson in green.

        Clamped to 1–14 days against outliers; requires >= 2 indexed
        rooms (median needs context) and a velocity sample.
        """
        if len(self.room_dirt_index) < 2 or not self.room_dirt_velocity:
            return {}
        target = statistics.median(self.room_dirt_index.values())
        if target <= 0:
            return {}
        out: dict[str, float] = {}
        for rid, vel in self.room_dirt_velocity.items():
            if vel <= 0:
                continue
            out[rid] = round(min(14.0, max(1.0, target / vel)), 1)
        return out

    def room_dirt_relative(self) -> dict[str, float]:
        """Return per-room dirtiness relative to the household average.

        L5 consumer helper — 1.0 = average; > 1.5 = notably dirty room.
        Returns empty dict when fewer than 2 rooms have been indexed.
        """
        if len(self.room_dirt_index) < 2:
            return {}
        avg = statistics.mean(self.room_dirt_index.values())
        if avg <= 0:
            return {}
        return {rid: val / avg for rid, val in self.room_dirt_index.items()}

    # ── L8 (v2.7.0) — Composite robot health score ────────────────────────────

    def compute_health_score(
        self,
        battery_retention_pct: float | None,
        nav_efficiency_ratio: float | None,
        cleaning_speed_trend: str | None,
        consecutive_anomalous: int,
        stuck_rate_30d: float | None,
    ) -> tuple[float | None, dict[str, Any]]:
        """L8 — weighted composite health score 0–100.

        Weights:
          Battery retention    25%  — measures physical degradation
          Nav efficiency       20%  — measures spatial coverage quality
          Cleaning speed trend 20%  — measures throughput trend
          Anomaly rate         20%  — measures mission consistency
          Stuck rate           15%  — measures obstacle avoidance

        Returns (None, {}) when fewer than 3 signals are available
        (insufficient data to form a meaningful score). Each missing signal
        is skipped and the remaining weights are renormalised.

        v3.1.0 PLAIN-STATUS: also returns a breakdown dict identifying which
        available signal scored lowest (weakest_signal), so callers can
        surface a plain-language explanation without re-deriving the
        per-signal scores themselves. weakest_signal is None when the
        overall score is None, or when every available signal scored >= 60
        (nothing notably weak — "good condition" case).
        """
        components: list[tuple[str, float, float]] = []   # (name, score, weight)

        # 1. Battery retention (25%): 50% retention → 0 pts, 100% → 100 pts
        if battery_retention_pct is not None:
            s = max(0.0, min(100.0, (float(battery_retention_pct) - 50.0) * 2.0))
            components.append(("battery_retention", s, 0.25))

        # 2. Navigation efficiency (20%): current/baseline ratio
        #    ratio ≥ 1.0 → 100; ratio ≤ 0.5 → 0 (linear between)
        if self.coverage_baseline_ready and nav_efficiency_ratio is not None:
            s = max(0.0, min(100.0, (float(nav_efficiency_ratio) - 0.5) * 200.0))
            components.append(("nav_efficiency", s, 0.20))

        # 3. Cleaning speed trend (20%)
        _trend_pts = {"improving": 100.0, "stable": 80.0, "declining": 40.0}
        if cleaning_speed_trend in _trend_pts:
            components.append(("cleaning_speed_trend", _trend_pts[cleaning_speed_trend], 0.20))

        # 4. Mission anomaly rate (20%): consecutive anomalous missions
        #    0 → 100, 1 → 70, 2 → 40, 3+ → 10
        _anomaly_pts = {0: 100.0, 1: 70.0, 2: 40.0}
        anomaly_score = _anomaly_pts.get(consecutive_anomalous, 10.0)
        components.append(("anomaly_rate", anomaly_score, 0.20))  # always available

        # 5. Stuck rate (15%): rate < 5% → 100; rate ≥ 30% → 0 (linear)
        if stuck_rate_30d is not None:
            s = max(0.0, min(100.0, (0.30 - float(stuck_rate_30d)) / 0.25 * 100.0))
            components.append(("stuck_rate", s, 0.15))

        if len(components) < 3:
            return None, {}

        total_weight = sum(w for _, _, w in components)
        if total_weight == 0:
            return None, {}

        score = sum(s * w for _, s, w in components) / total_weight
        score = round(min(100.0, max(0.0, score)), 1)

        # v3.1.0 PLAIN-STATUS — identify the weakest available signal.
        # Only flagged when it scored below 60 (clearly weak, not just
        # "not perfect") — otherwise weakest_signal is None ("good condition").
        weakest_name, weakest_score = min(
            ((name, s) for name, s, _ in components), key=lambda t: t[1]
        )
        breakdown: dict[str, Any] = {
            "battery_retention_pct": battery_retention_pct,
            "nav_efficiency_ratio": nav_efficiency_ratio,
            "cleaning_speed_trend": cleaning_speed_trend,
            "consecutive_anomalous": consecutive_anomalous,
            "stuck_rate_30d": stuck_rate_30d,
            "weakest_signal": weakest_name if weakest_score < 60.0 else None,
        }
        return score, breakdown
