"""Service (action) handlers for the Roomba+ integration.

Registers and implements all domain services:
  - roomba_plus.clean_room   — room-targeted clean for SMART robots
  - roomba_plus.smart_start  — blocking-sensor-aware start
  - roomba_plus.reset_filter / reset_brush / reset_battery / reset_pad

Helper functions _resolve_pmapv_id and _resolve_rooms are kept here
alongside the handlers that use them.

Extracted from __init__.py (v2.0 refactor).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import json
import logging
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

import voluptuous as vol
from homeassistant.util import dt as dt_util

from homeassistant.core import HomeAssistant, ServiceCall, SupportsResponse
from homeassistant.exceptions import HomeAssistantError, ServiceValidationError
from homeassistant.helpers import config_validation as cv
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.storage import Store

from .const import (
    ATTR_ORDERED,
    ATTR_OVERRIDE_BLOCKING,
    ATTR_ROOM_NAME,
    ATTR_ROOM_PASSES,
    ATTR_ROOMS,
    ATTR_TWO_PASS,
    DOMAIN,
    EVENT_MAINTENANCE_RESET,
    SERVICE_CLEAN_ROOM,
    SERVICE_CLEAN_OVERDUE_ROOMS,
    SERVICE_AUTO_CLEAN_DIRTY_ROOMS,
    CONF_ROOM_SCHEDULE,
    SERVICE_CLEAN_SEQUENCE,
    SERVICE_EXPLAIN_MISSION,
    SERVICE_RESET_BATTERY,
    SERVICE_RESET_BRUSH,
    SERVICE_RESET_FILTER,
    SERVICE_RESET_PAD,
    SERVICE_SMART_START,
    SERVICE_CREATE_BACKUP,
    SERVICE_RESTORE_BACKUP,
)
# _resolve_rooms and _resolve_pmapv_id moved to room_cleaning.py with
# the Classic send path they belong to. They were left behind here for
# one round as dead copies -- the same pattern that cost this project
# two minor versions elsewhere, so they are gone rather than kept "just
# in case".
from .room_cleaning import async_get_room_cleaning_backend
from .models import ConnectionType, RoombaConfigEntry, RoombaData

if TYPE_CHECKING:
    pass

_LOGGER = logging.getLogger(__name__)


# ── Helpers ───────────────────────────────────────────────────────────────────

# v3.5.0 FULL-BACKUP — every per-robot Store this integration persists.
# (runtime_data attribute name, HA Store storage-key prefix). All nine
# stores share STORAGE_VERSION/_HA_STORE_VERSION == 1 today (verified
# against each module directly) — hardcoded here rather than imported
# per-module to keep this list a single, auditable source of truth
# independent of any one store's internal naming (STORAGE_VERSION vs.
# _HA_STORE_VERSION vary by module, the value doesn't).
_BACKUP_STORE_VERSION = 1
#: mission_timer_store is DELIBERATELY ABSENT.
#:
#: It holds the state of the mission running right now -- elapsed
#: seconds, which room, when the phase last changed. Restoring that from
#: a backup would reinstate a mission that finished weeks ago, and the
#: robot would disagree within seconds.
#:
#: Everything else here is history or user-entered data, which is what a
#: backup is for.
_BACKUP_STORES: tuple[tuple[str, str], ...] = (
    ("mission_store", "roomba_plus_missions"),
    ("geometry_store", "roomba_plus_geometry"),
    ("grid_store", "roomba_plus_grid"),
    ("room_seg_store", "roomba_plus_roomseg"),
    ("outline_store", "roomba_plus_outline"),
    ("robot_profile_store", "roomba_plus_robot_profile"),
    ("maintenance_store", "roomba_plus_maintenance"),
    ("trajectory_store", "roomba_plus_trajectories"),
    ("freeze_snapshot_store", "roomba_plus_freeze"),
)






# ── Signal helper ─────────────────────────────────────────────────────────────

def _async_signal_entities(
    hass: HomeAssistant,
    entry_id: str,
    keys: list[str],
) -> None:
    """Force-refresh sensor/binary_sensor entities after non-MQTT state changes.

    Called after maintenance resets to immediately reflect the new baseline
    in timestamp sensors and L4 wear sensors, without waiting for the next
    MQTT push from the robot.
    """
    ent_reg = er.async_get(hass)
    entry = hass.config_entries.async_get_entry(entry_id)
    if entry is None:
        return
    data: RoombaData = entry.runtime_data
    robot_uid = f"roomba_plus_{data.blid}"
    for key in keys:
        for platform in ("sensor", "binary_sensor"):
            entity_id = ent_reg.async_get_entity_id(
                platform, DOMAIN, f"{robot_uid}_{key}"
            )
            if entity_id:
                current = hass.states.get(entity_id)
                if current:
                    hass.states.async_set(
                        entity_id,
                        current.state,
                        current.attributes,
                        force_update=True,
                    )
                break


def _fire_maintenance_reset_event(
    hass: HomeAssistant,
    config_entry: "RoombaConfigEntry",
    component: str,
    hours: int | None,
) -> None:
    """v2.9.0 LOGBOOK — fire roomba_plus_maintenance_reset.

    Shared by BOTH call paths that perform a maintenance reset: the
    roomba_plus.reset_* services (this module, below) and the Filter/Brush/
    Battery reset buttons (button.py — imports this helper, same pattern
    as button.py's existing import of _resolve_pmapv_id from here). One
    event regardless of which path the user took, so the Logbook entry
    appears consistently either way.

    hours is None for the calendar-based inspect resets (wheel/contact/bin
    cleaning) — those have no hr-counter baseline to report.
    """
    hass.bus.async_fire(
        EVENT_MAINTENANCE_RESET,
        {
            "entry_id": config_entry.entry_id,
            "name": config_entry.title,
            "component": component,
            "hours": hours,
        },
    )


# ── Service handlers ──────────────────────────────────────────────────────────

async def _async_clean_rooms_via_backend(
    backend: Any,
    entity_id: str,
    room_names: list[str],
    ordered: bool,
    per_room_two_pass: list[bool | None],
    call: ServiceCall,
) -> None:
    """Room cleaning through a RoomCleaningBackend.

    BOTH GENERATIONS now, though Prime came first. The Classic path was
    moved into ClassicRoomCleaning afterwards, verbatim -- its 141-line
    resolution step, the cross-map conflict rules and the readiness
    check all came across intact, which took four rounds of existing
    tests to confirm.

    Name matching is shared, though -- match_room_names() carries the
    slug fallback that lets "kuche" find "Küche". Two different matching
    rules across generations would be a confusing bug to report and a
    worse one to find.
    """
    from .room_cleaning import match_room_names  # noqa: PLC0415

    available = await backend.available_rooms()
    if not available:
        raise ServiceValidationError(
            f"{entity_id} has no named rooms yet. Finish a mapping run and name "
            "the rooms in the iRobot app first.",
            translation_domain=DOMAIN,
            translation_key="no_rooms_configured",
        )

    room_ids, unknown = match_room_names(available, room_names)
    if not room_ids and not unknown:
        # An empty request: room_passes=[] satisfies the "exactly one
        # of" argument checks and then resolves to nothing. Without this
        # the call would reach the backend with no regions, which sends
        # a command that cleans nowhere.
        raise ServiceValidationError(
            "No rooms to clean — provide at least one room name.",
            translation_domain=DOMAIN,
            translation_key="no_rooms_resolved",
        )
    if unknown:
        raise ServiceValidationError(
            f"Unknown room(s) for {entity_id}: {', '.join(unknown)}. "
            f"Known rooms: {', '.join(sorted(available))}.",
            translation_domain=DOMAIN,
            translation_key="unknown_rooms",
            translation_placeholders={
                "entity_id": entity_id,
                "rooms": ", ".join(unknown),
                "known": ", ".join(sorted(available)),
            },
        )

    caller_two_pass: bool | None = call.data.get(ATTR_TWO_PASS)
    def _two_pass_for(index: int) -> bool | None:
        """Per-room value, else the caller-level one, else None.

        None means "leave the robot's own setting alone" and the backend
        fills it in -- the same three-step precedence the Classic path
        uses.

        Written out rather than using `or`, which was the first draft
        and was wrong: `False or True` is True, so a user asking for one
        room WITHOUT a second pass while the call defaults to two passes
        would have had their explicit choice silently overridden. This
        project has hit "absent treated as false" more than once; here
        it is the reverse, and just as wrong.
        """
        if index < len(per_room_two_pass) and per_room_two_pass[index] is not None:
            return per_room_two_pass[index]
        return caller_two_pass

    two_pass = [_two_pass_for(i) for i in range(len(room_ids))]

    _LOGGER.info(
        "clean_room: %s → rooms=%s (via %s)",
        entity_id, room_ids, type(backend).__name__,
    )
    await backend.clean_rooms(room_ids, ordered=ordered, two_pass=two_pass)


async def async_handle_clean_room(call: ServiceCall) -> None:
    """Handle the roomba_plus.clean_room service call.

    Resolves room names → region_ids, looks up the fresh user_pmapv_id from
    live MQTT state, and fires a region-targeted start command.

    Only works for MapCapability.SMART robots (i7 / s9 / j-series).
    """
    hass = call.hass
    entity_ids: list[str] = call.data["entity_id"]

    # CLEAN-ROOM-PER-ROOM-PASSES (v2.9.0): exactly one of room_name / room_passes.
    raw_room_name = call.data.get(ATTR_ROOM_NAME)
    raw_room_passes: list[dict] | None = call.data.get(ATTR_ROOM_PASSES)

    if raw_room_name is not None and raw_room_passes is not None:
        raise ServiceValidationError(
            "Provide either room_name or room_passes, not both.",
            translation_domain=DOMAIN,
            translation_key="room_name_and_room_passes_conflict",
        )
    if raw_room_name is None and raw_room_passes is None:
        raise ServiceValidationError(
            "Provide either room_name or room_passes.",
            translation_domain=DOMAIN,
            translation_key="room_name_or_room_passes_required",
        )

    if raw_room_passes is not None:
        room_names: list[str] = [r["name"] for r in raw_room_passes]
        # Per-room override, aligned by index with room_names/resolved order.
        # None where the caller didn't specify two_pass for that particular room.
        per_room_two_pass: list[bool | None] = [
            r.get(ATTR_TWO_PASS) for r in raw_room_passes
        ]
    else:
        room_names = (
            [raw_room_name] if isinstance(raw_room_name, str) else raw_room_name
        )
        per_room_two_pass = [None] * len(room_names)

    ordered: bool = call.data[ATTR_ORDERED]

    ent_reg = er.async_get(hass)

    for entity_id in entity_ids:
        entry = ent_reg.async_get(entity_id)
        if entry is None:
            raise ServiceValidationError(
                f"Entity {entity_id} not found",
                translation_domain=DOMAIN,
                translation_key="entity_not_found",
                translation_placeholders={"entity_id": entity_id},
            )

        config_entry: RoombaConfigEntry | None = hass.config_entries.async_get_entry(
            entry.config_entry_id
        )
        if config_entry is None:
            raise ServiceValidationError(
                f"No config entry for {entity_id}",
                translation_domain=DOMAIN,
                translation_key="config_entry_not_found",
                translation_placeholders={"entity_id": entity_id},
            )

        # ASKS THE BACKEND, not a capability flag (this session).
        #
        # This used to gate on map_capability == SMART, which is a
        # Classic-shaped question: has_smart_map() looks for a "pmaps"
        # key and Prime robots report "p2maps", so every Prime robot was
        # refused room cleaning even after the transport was confirmed
        # working on real hardware.
        #
        # "Is there a backend" answers what is actually being asked --
        # can this robot clean a named room -- for both generations, and
        # needs no flag to be read correctly at each call site.
        backend = async_get_room_cleaning_backend(config_entry, hass)
        if backend is None:
            raise ServiceValidationError(
                f"{entity_id} does not support room cleaning. Classic robots need a "
                "finalized Smart Map (i7, s9, j-series or Braava jet m6) with cloud "
                "credentials configured; Prime robots need a saved map. Check that "
                "the map is saved in the iRobot app.",
                translation_domain=DOMAIN,
                translation_key="not_smart_map",
            )

        # ONE PATH FOR BOTH GENERATIONS (this session).
        #
        # There used to be a Prime branch here and ~120 lines of Classic
        # send logic below it. The Classic half now lives in
        # ClassicRoomCleaning, moved verbatim rather than rewritten --
        # an earlier draft copied it and silently lost the cross-map
        # conflict rules, the map-updating check, cloud enrichment of
        # zone data, and a distinct error message.
        #
        # What made the move possible was noticing that Classic needs
        # exactly one thing beyond a region id -- that region's pmap_id
        # -- and it already sits next to every region in the room list.
        # Recorded there once, the send path needs no room names, and
        # both generations fit an id-based interface.
        await _async_clean_rooms_via_backend(
            backend, entity_id, room_names, ordered, per_room_two_pass, call
        )


async def async_handle_smart_start(call: ServiceCall) -> None:
    """Handle roomba_plus.smart_start with blocking-sensor gate."""
    hass = call.hass
    entity_ids: list[str] = call.data.get("entity_id", [])
    if isinstance(entity_ids, str):
        entity_ids = [entity_ids]
    rooms: list[str] | None = call.data.get(ATTR_ROOMS)
    override: bool = call.data.get(ATTR_OVERRIDE_BLOCKING, False)

    ent_reg = er.async_get(hass)

    for eid in entity_ids:
        entry_reg = ent_reg.async_get(eid)
        if entry_reg is None:
            raise ServiceValidationError(
                f"Entity {eid} not found",
                translation_domain=DOMAIN,
                translation_key="entity_not_found",
            )
        config_entry = hass.config_entries.async_get_entry(entry_reg.config_entry_id)
        if config_entry is None:
            raise ServiceValidationError(
                f"No config entry for {eid}",
                translation_domain=DOMAIN,
                translation_key="config_entry_not_found",
                translation_placeholders={"entity_id": eid},
            )

        data: RoombaData = config_entry.runtime_data
        # ONE CHECK FOR BOTH GENERATIONS (this session), replacing two.
        #
        # There used to be a Prime-specific refusal here whose stated
        # reason was that region commands "have had zero effect in two
        # live field tests". That was true when written and is not any
        # more: region cleaning is confirmed working on real Prime
        # hardware, from a saved favorite and from scratch. The blocker
        # turned out to be a missing `initiator` field plus two wrong
        # wire keys, not the transport.
        #
        # A refusal justified by a finding is only as good as the
        # finding. Leaving it in place would have kept Prime users from
        # a feature that works, for a reason nobody would have thought
        # to re-check.
        if rooms and async_get_room_cleaning_backend(config_entry) is None:
            raise ServiceValidationError(
                f"{eid} does not support room targeting. Classic robots need a "
                "finalized Smart Map (i7, s9, j-series or Braava jet m6); Prime "
                "robots need a saved map.",
                translation_domain=DOMAIN,
                translation_key="not_smart_map",
            )
        if data.blocking_manager is not None:
            await data.blocking_manager.check_and_start(rooms, override)
        elif rooms:
            await hass.services.async_call(
                DOMAIN,
                SERVICE_CLEAN_ROOM,
                {"entity_id": eid, ATTR_ROOM_NAME: rooms},
                blocking=True,
            )
        elif data.connection_type == ConnectionType.CLOUD_ONLY:
            # REAL CRASH FIXED (this session): this branch (no
            # blocking_manager configured at all -- CONF_BLOCKING_SENSORS
            # empty/unset) used to unconditionally call data.roomba.start,
            # which is None for every Prime entry -- an AttributeError on
            # any Prime user calling roomba_plus.smart_start with no
            # blocking sensors configured, regardless of rooms/override.
            # send_simple_command("start") is the same confirmed-working
            # path the vacuum entity's own start action already uses.
            await data.prime_robot.send_simple_command("start")
        else:
            await hass.async_add_executor_job(data.roomba.start)


async def async_handle_clean_overdue_rooms(call: ServiceCall) -> None:
    """v3.3.0 ROOM-SCHED — roomba_plus.clean_overdue_rooms.

    Determines overdue rooms via the SAME merge rule as the
    rooms_overdue sensor (MissionStore.rooms_overdue_merged — one shared
    rule set), sorts worst-first by overdue_factor, and delegates the
    actual start to roomba_plus.clean_room (reusing its full pmap/
    resolution/notReady logic instead of duplicating it — the same
    delegation pattern smart_start uses).

    - SMART only: EPHEMERAL raises — the hardware cannot room-target
      (`pmap_id=None` on every EPHEMERAL mission, v3.2.1 ZoneSelect
      lesson).
    - Nothing overdue: deliberate NO-OP with an INFO log, not an error —
      automations may fire this daily without guards.
    - max_rooms (optional): cap, worst-first.
    """
    hass = call.hass
    entity_ids: list[str] = call.data.get("entity_id", [])
    if isinstance(entity_ids, str):
        entity_ids = [entity_ids]
    max_rooms: int | None = call.data.get("max_rooms")

    ent_reg = er.async_get(hass)
    for eid in entity_ids:
        entry_reg = ent_reg.async_get(eid)
        if entry_reg is None:
            raise ServiceValidationError(
                f"Entity {eid} not found",
                translation_domain=DOMAIN,
                translation_key="entity_not_found",
            )
        config_entry = hass.config_entries.async_get_entry(entry_reg.config_entry_id)
        if config_entry is None:
            raise ServiceValidationError(
                f"No config entry for {eid}",
                translation_domain=DOMAIN,
                translation_key="config_entry_not_found",
                translation_placeholders={"entity_id": eid},
            )
        data: RoombaData = config_entry.runtime_data
        # Same backend question clean_room asks, for the same reason:
        # map_capability is a Classic concept and every Prime robot
        # fails it regardless of what it can actually do.
        #
        # This service delegates the actual start to clean_room, so
        # without changing it here a Prime robot would be refused one
        # step before reaching a path that works.
        if async_get_room_cleaning_backend(config_entry) is None:
            raise ServiceValidationError(
                f"{eid} does not support room targeting. Classic robots need a "
                "finalized Smart Map -- EPHEMERAL-tier robots (900-series) cannot "
                "clean individual rooms; Prime robots need a saved map.",
                translation_domain=DOMAIN,
                translation_key="not_smart_map",
            )
        ms = data.mission_store
        if ms is None:
            continue

        # Bug-hunt round 4 (seam check) — SAME name resolution as the
        # rooms_overdue sensor, incl. the UMF fallback: otherwise a
        # degraded cloud-regions window makes the sensor report overdue
        # rooms the service cannot resolve. Lazy import — no cycle
        # (sensor never imports services).
        from .sensor import _region_maps_for
        region_map, umf_regions = _region_maps_for(data)
        config = config_entry.options.get(CONF_ROOM_SCHEDULE) or {}
        merged = ms.rooms_overdue_merged(
            config, dt_util.now().isoformat(),
            region_map=region_map, umf_regions=umf_regions,
        )
        overdue = sorted(
            (n for n, i in merged.items() if i["status"] == "overdue"),
            key=lambda n: merged[n]["overdue_factor"] or 0,
            reverse=True,
        )
        if max_rooms:
            overdue = overdue[: int(max_rooms)]
        if not overdue:
            _LOGGER.info(
                "clean_overdue_rooms: nothing overdue for %s — no-op", eid
            )
            continue
        overdue = _route_optimize_order(data, overdue, region_map)
        _LOGGER.info(
            "clean_overdue_rooms: starting %s for %s "
            "(overdue-selected, route-ordered)",
            overdue, eid,
        )
        await hass.services.async_call(
            DOMAIN,
            SERVICE_CLEAN_ROOM,
            {"entity_id": eid, ATTR_ROOM_NAME: overdue},
            blocking=True,
        )


def _route_optimize_order(
    data: "RoombaData",
    room_names: list[str],
    region_map: dict[str, str],
) -> list[str]:
    """v3.3.0 SMART-ORDER routing — reorder the SELECTED rooms by travel
    path: greedy nearest-neighbour over the UMF room centroids, starting
    at the dock (pose origin (0,0) mapped via pose_to_umf). iRobot works
    the submitted region list IN ORDER, so a dirt-/overdue-sorted list
    can mean criss-crossing the home.

    Deliberate split of concerns: dirt/overdue decide WHICH rooms (and
    the max_rooms cap — the dirtiest room must never lose to the cap
    just for being far away); geometry only decides the ORDER of the
    already-selected set. Greedy NN is practically optimal at the
    typical 2–6 rooms; a real TSP would be overengineering.

    Fallbacks (input order returned unchanged): aligner missing or not
    aligned, dock not mappable, fewer than 3 rooms with centroids.
    Rooms without a centroid keep their relative order at the end.
    """
    if len(room_names) < 2:
        return room_names
    aligner = getattr(data, "umf_aligner", None)
    if aligner is None or not getattr(aligner, "aligned", False):
        return room_names
    try:
        centroids_by_rid = aligner.room_centroids_umf()
        dock = aligner.pose_to_umf(0.0, 0.0)
    except Exception:  # noqa: BLE001 — routing is a bonus, never a blocker
        return room_names
    if not centroids_by_rid or dock is None:
        return room_names

    name_to_rid = {name: rid for rid, name in region_map.items()}
    positioned = [
        (n, centroids_by_rid[name_to_rid[n]])
        for n in room_names
        if name_to_rid.get(n) in centroids_by_rid
    ]
    unpositioned = [n for n in room_names if n not in {p[0] for p in positioned}]
    if len(positioned) < 2:
        return room_names

    ordered: list[str] = []
    cx, cy = dock
    remaining = positioned[:]
    while remaining:
        i = min(
            range(len(remaining)),
            key=lambda k: (remaining[k][1][0] - cx) ** 2
            + (remaining[k][1][1] - cy) ** 2,
        )
        name, (cx, cy) = remaining.pop(i)
        ordered.append(name)
    return ordered + unpositioned


_SMART_ORDER_MIN_MISSIONS = 10  # v3.3.0 SMART-ORDER — index trust gate


async def async_handle_auto_clean_dirty_rooms(call: ServiceCall) -> None:
    """v3.3.0 SMART-ORDER — roomba_plus.auto_clean_dirty_rooms.

    Targeted clean of the household's dirty rooms, sorted DESCENDING by
    the L5 per-room dirt index (EMA of passCount/m²). A room qualifies
    when:
    - it has >= _SMART_ORDER_MIN_MISSIONS recorded cleanings (the EMA is
      not trustworthy on thin data), AND
    - its relative dirt (room_dirt_relative) is >= 1.0 — at or above
      the household average. Below-average rooms are not "dirty rooms".

    No qualifying room -> WHOLE-HOUSE clean as the fallback (per spec):
    thin data means "clean normally", not "refuse".
    SMART-only like clean_overdue_rooms: on EPHEMERAL the dirt index has
    no per-room data source and targeting is impossible — raising is
    more honest than silently degrading to a plain start.
    Delegates targeted starts to clean_room (shared pmap/resolution
    logic, same pattern as smart_start/clean_overdue_rooms).
    """
    hass = call.hass
    entity_ids: list[str] = call.data.get("entity_id", [])
    if isinstance(entity_ids, str):
        entity_ids = [entity_ids]
    max_rooms: int | None = call.data.get("max_rooms")

    ent_reg = er.async_get(hass)
    for eid in entity_ids:
        entry_reg = ent_reg.async_get(eid)
        if entry_reg is None:
            raise ServiceValidationError(
                f"Entity {eid} not found",
                translation_domain=DOMAIN,
                translation_key="entity_not_found",
            )
        config_entry = hass.config_entries.async_get_entry(entry_reg.config_entry_id)
        if config_entry is None:
            raise ServiceValidationError(
                f"No config entry for {eid}",
                translation_domain=DOMAIN,
                translation_key="config_entry_not_found",
                translation_placeholders={"entity_id": eid},
            )
        data: RoombaData = config_entry.runtime_data
        # Same backend question clean_room asks, for the same reason:
        # map_capability is a Classic concept and every Prime robot
        # fails it regardless of what it can actually do.
        #
        # This service delegates the actual start to clean_room, so
        # without changing it here a Prime robot would be refused one
        # step before reaching a path that works.
        if async_get_room_cleaning_backend(config_entry) is None:
            raise ServiceValidationError(
                f"{eid} does not support room targeting. Classic robots need a "
                "finalized Smart Map -- EPHEMERAL-tier robots (900-series) cannot "
                "clean individual rooms; Prime robots need a saved map.",
                translation_domain=DOMAIN,
                translation_key="not_smart_map",
            )
        ms = data.mission_store
        rps = getattr(data, "robot_profile_store", None)

        # Bug-hunt round 4 (seam check) — same resolution incl. UMF
        # fallback as the sensor/overdue paths.
        from .sensor import _region_maps_for
        _rm, _umf = _region_maps_for(data)
        region_map: dict[str, str] = _rm or (_umf or {})

        candidates: list[str] = []
        if ms is not None and rps is not None:
            visit_counts = ms.room_visit_counts(region_map)
            relative = rps.room_dirt_relative()          # rid-keyed
            index = dict(rps.room_dirt_index)            # rid-keyed
            qualifying = []
            for rid, rel in relative.items():
                name = region_map.get(rid, rid)
                if rel < 1.0:
                    continue
                if visit_counts.get(name, 0) < _SMART_ORDER_MIN_MISSIONS:
                    continue
                qualifying.append((index.get(rid, 0.0), name))
            qualifying.sort(reverse=True)                # dirtiest first
            candidates = [name for _, name in qualifying]

        if max_rooms:
            candidates = candidates[: int(max_rooms)]

        if not candidates:
            _LOGGER.info(
                "auto_clean_dirty_rooms: no room passes the dirt-index "
                "trust gate for %s — whole-house fallback", eid,
            )
            await hass.async_add_executor_job(data.roomba.start)
            continue

        candidates = _route_optimize_order(data, candidates, region_map)
        _LOGGER.info(
            "auto_clean_dirty_rooms: starting %s for %s "
            "(dirt-selected, route-ordered)",
            candidates, eid,
        )
        await hass.services.async_call(
            DOMAIN,
            SERVICE_CLEAN_ROOM,
            {"entity_id": eid, ATTR_ROOM_NAME: candidates},
            blocking=True,
        )


async def _handle_reset_service(
    hass: HomeAssistant, call: ServiceCall, part: str
) -> None:
    """Handle roomba_plus.reset_{filter|brush|battery|pad}."""
    entity_ids: list[str] = call.data.get("entity_id", [])
    if isinstance(entity_ids, str):
        entity_ids = [entity_ids]

    ent_reg = er.async_get(hass)

    for eid in entity_ids:
        entry_reg = ent_reg.async_get(eid)
        if entry_reg is None:
            _LOGGER.warning("reset_%s: entity not found: %s", part, eid)
            continue
        config_entry = hass.config_entries.async_get_entry(entry_reg.config_entry_id)
        if config_entry is None:
            _LOGGER.warning("reset_%s: config entry not found for %s", part, eid)
            continue

        data: RoombaData = config_entry.runtime_data
        if data.maintenance_store is None:
            raise ServiceValidationError(
                f"Maintenance store not available for {eid}",
                translation_domain=DOMAIN,
                translation_key="maintenance_store_unavailable",
            )

        # The hour meter the reset is recorded against, so "hours since
        # the filter was changed" can be computed later.
        #
        # Classic reads it from the MQTT state; Prime reports the same
        # thing in a named shadow instead. Without the Prime branch this
        # recorded 0, which would have made every interval since the
        # reset read as the robot's entire lifetime.
        current_hr = 0
        if data.connection_type is ConnectionType.CLOUD_ONLY:
            coordinator = getattr(data, "prime_status_coordinator", None)
            shadow = (coordinator.data or {}).get("ro-stats") if coordinator else None
            runtime = (shadow or {}).get("runtimeStats") or {}
            current_hr = int(runtime.get("hours") or 0)
        else:
            state = data.roomba_reported_state()
            _bbrun   = state.get("bbrun", {})
            _runtime = state.get("runtimeStats", {})
            current_hr = int(_bbrun.get("hr") or _runtime.get("hr") or 0)
        getattr(data.maintenance_store, f"reset_{part}")(current_hr)
        await data.maintenance_store.async_save(hass, config_entry.entry_id)
        _fire_maintenance_reset_event(hass, config_entry, part, current_hr)
        _async_signal_entities(hass, config_entry.entry_id, [
            "filter_last_replaced",
            "brush_last_replaced",
            "pad_last_replaced",
            "battery_last_replaced",
            "filter_wear_rate",
            "brush_wear_rate",
            "pad_wear_rate",
            "filter_days_until_due",
            "brush_days_until_due",
            "pad_days_until_due",
        ])
        _LOGGER.info("reset_%s: executed for %s at %dh", part, eid, current_hr)


# ── IA74-MAINT (v2.7.0) — calendar-based inspect reset services ───────────────

async def _handle_inspect_reset_service(
    hass: HomeAssistant, call: ServiceCall, component: str
) -> None:
    """Handle roomba_plus.reset_{wheel|contact|bin}_cleaning."""
    entity_ids: list[str] = call.data.get("entity_id", [])
    if isinstance(entity_ids, str):
        entity_ids = [entity_ids]

    ent_reg = er.async_get(hass)

    for eid in entity_ids:
        entry_reg = ent_reg.async_get(eid)
        if entry_reg is None:
            _LOGGER.warning("reset_%s_cleaning: entity not found: %s", component, eid)
            continue
        config_entry = hass.config_entries.async_get_entry(entry_reg.config_entry_id)
        if config_entry is None:
            _LOGGER.warning("reset_%s_cleaning: config entry not found for %s", component, eid)
            continue

        data: RoombaData = config_entry.runtime_data
        if data.maintenance_store is None:
            raise ServiceValidationError(
                f"Maintenance store not available for {eid}",
                translation_domain=DOMAIN,
                translation_key="maintenance_store_unavailable",
            )

        getattr(data.maintenance_store, f"reset_{component}_cleaning")()
        await data.maintenance_store.async_save(hass, config_entry.entry_id)
        _fire_maintenance_reset_event(hass, config_entry, component, None)
        _async_signal_entities(hass, config_entry.entry_id, [
            "wheel_last_cleaned",
            "contact_last_cleaned",
            "bin_last_cleaned",
        ])
        _LOGGER.info("reset_%s_cleaning: executed for %s", component, eid)


async def async_handle_reset_robot_profile(call: ServiceCall) -> None:
    """Handle roomba_plus.reset_robot_profile.

    Wipes all self-calibrated learned state in RobotProfileStore so the robot
    starts fresh — useful after moving house, a major layout change, or
    replacing the robot entirely.  Mission history is unaffected.
    """
    entity_ids: list[str] = call.data.get("entity_id", [])
    if isinstance(entity_ids, str):
        entity_ids = [entity_ids]

    ent_reg = er.async_get(call.hass)

    for eid in entity_ids:
        entry_reg = ent_reg.async_get(eid)
        if entry_reg is None:
            _LOGGER.warning("reset_robot_profile: entity not found: %s", eid)
            continue
        config_entry = call.hass.config_entries.async_get_entry(entry_reg.config_entry_id)
        if config_entry is None:
            _LOGGER.warning("reset_robot_profile: config entry not found for %s", eid)
            continue

        data: RoombaData = config_entry.runtime_data
        rps = getattr(data, "robot_profile_store", None)
        if rps is None:
            _LOGGER.warning("reset_robot_profile: RobotProfileStore not available for %s", eid)
            continue

        await rps.async_reset(call.hass, config_entry.entry_id)
        _LOGGER.info("reset_robot_profile: executed for %s", eid)


# ── v3.2.0 ANOMALY-EXPLAIN ──────────────────────────────────────────────────

async def async_handle_explain_mission(call: ServiceCall) -> dict[str, Any]:
    """Handle roomba_plus.explain_mission.

    Rule-based explanation for why a mission was flagged anomalous (L3).
    Resolves in this order:
      1. mission_id explicitly given → look it up directly.
      2. mission_id omitted → most recent mission, whether anomalous or not
         (the response's is_anomalous field tells the caller which case it is
         — this lets "explain the last mission" work as a general-purpose
         call, not just for missions already known to be anomalous).

    Returns three independent pieces of information, not a single merged
    verdict — anomaly_reason (one of a fixed priority order, or None),
    robot_lifted (bbrun.nPicks delta > 0 during that specific mission), and
    error_code (the mission's own recorded error, if any) can all apply
    simultaneously and don't compete with each other for "the" explanation.
    """
    entity_id: str = call.data["entity_id"]
    mission_id: str | None = call.data.get("mission_id")

    ent_reg = er.async_get(call.hass)
    entry_reg = ent_reg.async_get(entity_id)
    if entry_reg is None:
        raise ServiceValidationError(f"explain_mission: entity not found: {entity_id}")
    config_entry = call.hass.config_entries.async_get_entry(entry_reg.config_entry_id)
    if config_entry is None:
        raise ServiceValidationError(
            f"explain_mission: config entry not found for {entity_id}"
        )

    data: RoombaData = config_entry.runtime_data
    mission_store = getattr(data, "mission_store", None)
    if mission_store is None:
        raise ServiceValidationError(f"explain_mission: no mission history for {entity_id}")

    # v3.3.1 EXPLAIN-CLOUD bug-hunt fix — the REST view (api_views.py's
    # ExplainMissionView) gained cloud-only "c_{ts}" id resolution, but this
    # service didn't, despite the contract ("both delegate to
    # MissionStore.explain_mission() ... so the two never drift out of
    # sync"). A mission_id copied from format=records for a cloud-only row
    # would 404 here while resolving fine via REST. Local import matches
    # this module's existing cross-import style (_resolve_pmapv_id etc.).
    record_override = None
    if mission_id is not None and mission_id.startswith("c_"):
        from .api_views import _resolve_cloud_explain_record
        record_override = _resolve_cloud_explain_record(data, mission_id)
        if record_override is None:
            raise ServiceValidationError(
                f"explain_mission: mission not found for {entity_id} (id={mission_id})"
            )

    result = mission_store.explain_mission(
        None if record_override is not None else mission_id,
        record_override=record_override,
    )
    if result is None:
        raise ServiceValidationError(
            f"explain_mission: mission not found for {entity_id}"
            + (f" (id={mission_id})" if mission_id is not None else "")
        )
    return result


# ── F10d — clean_sequence ─────────────────────────────────────────────────────

_CLEAN_SEQUENCE_SCHEMA = vol.Schema({
    vol.Required("entity_id"): cv.entity_id,
    vol.Required("target_entity_id"): cv.entity_id,
    vol.Optional("require_completed", default=True): bool,
    vol.Optional("delay_minutes", default=0): vol.All(int, vol.Range(min=0, max=60)),
})


async def async_handle_clean_sequence(
    hass: HomeAssistant, call: ServiceCall
) -> None:
    """F10d — start robot B when robot A mission ends.

    Subscribes a one-shot state change listener on robot A's vacuum entity.
    When A transitions to 'docked' (completed mission), optionally waits
    delay_minutes, then calls vacuum.start on robot B.

    The listener removes itself after firing once regardless of outcome.

    Args:
        entity_id:         Trigger robot — must finish first.
        target_entity_id:  Target robot — started after trigger.
        require_completed: When True (default), robot B starts only if A docked.
                           When False, B starts even if A is idle/error.
        delay_minutes:     Wait this many minutes after A docks before starting B.
    """
    from homeassistant.core import callback
    from homeassistant.helpers import entity_registry as er

    trigger_entity = call.data["entity_id"]
    target_entity  = call.data["target_entity_id"]
    require_completed = call.data.get("require_completed", True)
    delay_minutes     = int(call.data.get("delay_minutes", 0))

    # Validate both entities belong to roomba_plus vacuum platform
    reg = er.async_get(hass)
    for eid in (trigger_entity, target_entity):
        entry = reg.async_get(eid)
        if entry is None or entry.platform != DOMAIN or entry.domain != "vacuum":
            raise vol.Invalid(
                f"Entity {eid} is not a roomba_plus vacuum entity"
            )

    _LOGGER.debug(
        "clean_sequence: registered — trigger=%s target=%s "
        "require_completed=%s delay=%dmin",
        trigger_entity, target_entity, require_completed, delay_minutes,
    )

    unsub_ref: list = []

    @callback
    def _on_trigger_state_change(
        entity_id: str, old_state: Any, new_state: Any
    ) -> None:
        if new_state is None:
            return
        state_str = new_state.state
        should_fire = (
            state_str == "docked"
            or (state_str in ("idle", "error") and not require_completed)
        )
        if should_fire:
            if delay_minutes > 0:
                hass.async_create_task(
                    _delayed_start(delay_minutes),
                    name=f"roomba_plus_clean_sequence_{target_entity}",
                )
            else:
                hass.async_create_task(
                    hass.services.async_call(
                        "vacuum", "start", {"entity_id": target_entity}
                    ),
                    name=f"roomba_plus_clean_sequence_imm_{target_entity}",
                )
            if unsub_ref:
                unsub_ref[0]()

    async def _delayed_start(delay_min: int) -> None:
        import asyncio as _asyncio
        await _asyncio.sleep(delay_min * 60)
        await hass.services.async_call(
            "vacuum", "start", {"entity_id": target_entity}
        )
        _LOGGER.info(
            "clean_sequence: started %s after %dmin delay (trigger: %s)",
            target_entity, delay_min, trigger_entity,
        )

    from homeassistant.helpers.event import async_track_state_change
    unsub = async_track_state_change(hass, trigger_entity, _on_trigger_state_change)
    unsub_ref.append(unsub)


# ── Registration ──────────────────────────────────────────────────────────────

def async_register_services(hass: HomeAssistant) -> None:
    """Register all Roomba+ domain services. Safe to call multiple times.

    Each service is guarded by has_service() — only registers on first call,
    subsequent entries reuse the same handlers.
    """
    _RESET_SCHEMA = vol.Schema({vol.Required("entity_id"): cv.entity_ids})

    if not hass.services.has_service(DOMAIN, SERVICE_CLEAN_ROOM):
        hass.services.async_register(
            DOMAIN,
            SERVICE_CLEAN_ROOM,
            async_handle_clean_room,
            schema=vol.Schema({
                vol.Required("entity_id"): cv.entity_ids,
                # CLEAN-ROOM-PER-ROOM-PASSES (v2.9.0): room_name is now optional
                # at the schema level — the handler enforces "exactly one of
                # room_name / rooms" so the error message can be specific.
                vol.Optional(ATTR_ROOM_NAME): vol.Any(
                    cv.string,
                    vol.All(cv.ensure_list, [cv.string]),
                ),
                # Bugfix (found while implementing CLEAN-ROOM-PER-ROOM-PASSES):
                # two_pass was read by the handler and documented in
                # services.yaml, but missing from this schema entirely — any
                # caller passing it via hass.services.async_call() with
                # validation enabled (the normal path for YAML automations
                # and the Developer Tools UI) was rejected with "extra keys
                # not allowed @ data['two_pass']". Untested — test_services.py
                # had no coverage that went through real schema validation.
                vol.Optional(ATTR_TWO_PASS): cv.boolean,
                vol.Optional(ATTR_ORDERED, default=True): cv.boolean,
                # CLEAN-ROOM-PER-ROOM-PASSES (v2.9.0): individual pass count
                # per room within the same sequence, e.g.
                #   room_passes: [{name: Kitchen, two_pass: true}, {name: Hallway}]
                vol.Optional(ATTR_ROOM_PASSES): vol.All(cv.ensure_list, [
                    vol.Schema({
                        vol.Required("name"): cv.string,
                        vol.Optional(ATTR_TWO_PASS): cv.boolean,
                    })
                ]),
            }),
            supports_response=SupportsResponse.OPTIONAL,
        )
        _LOGGER.debug("Registered %s.%s action", DOMAIN, SERVICE_CLEAN_ROOM)

    if not hass.services.has_service(DOMAIN, SERVICE_SMART_START):
        hass.services.async_register(
            DOMAIN,
            SERVICE_SMART_START,
            async_handle_smart_start,
            schema=vol.Schema({
                vol.Required("entity_id"): cv.entity_ids,
                vol.Optional(ATTR_ROOMS): vol.All(cv.ensure_list, [cv.string]),
                vol.Optional(ATTR_OVERRIDE_BLOCKING, default=False): cv.boolean,
            }),
        )
        _LOGGER.debug("Registered %s.%s action", DOMAIN, SERVICE_SMART_START)

    if not hass.services.has_service(DOMAIN, SERVICE_CLEAN_OVERDUE_ROOMS):
        hass.services.async_register(
            DOMAIN,
            SERVICE_CLEAN_OVERDUE_ROOMS,
            async_handle_clean_overdue_rooms,
            schema=vol.Schema({
                vol.Required("entity_id"): cv.entity_ids,
                vol.Optional("max_rooms"): vol.All(
                    vol.Coerce(int), vol.Range(min=1)
                ),
            }),
        )
        _LOGGER.debug(
            "Registered %s.%s action", DOMAIN, SERVICE_CLEAN_OVERDUE_ROOMS
        )

    if not hass.services.has_service(DOMAIN, SERVICE_AUTO_CLEAN_DIRTY_ROOMS):
        hass.services.async_register(
            DOMAIN,
            SERVICE_AUTO_CLEAN_DIRTY_ROOMS,
            async_handle_auto_clean_dirty_rooms,
            schema=vol.Schema({
                vol.Required("entity_id"): cv.entity_ids,
                vol.Optional("max_rooms"): vol.All(
                    vol.Coerce(int), vol.Range(min=1)
                ),
            }),
        )
        _LOGGER.debug(
            "Registered %s.%s action", DOMAIN, SERVICE_AUTO_CLEAN_DIRTY_ROOMS
        )

    for _part in ("filter", "brush", "battery", "pad"):
        svc = f"reset_{_part}"
        if not hass.services.has_service(DOMAIN, svc):
            _p = _part

            async def _make_reset_handler(
                call: ServiceCall, p: str = _p
            ) -> None:
                await _handle_reset_service(call.hass, call, p)

            hass.services.async_register(
                DOMAIN,
                svc,
                _make_reset_handler,
                schema=_RESET_SCHEMA,
            )

    # ── IA74-MAINT (v2.7.0) — calendar-based inspect resets ──────────────────
    for _component in ("wheel", "contact", "bin"):
        svc = f"reset_{_component}_cleaning"
        if not hass.services.has_service(DOMAIN, svc):
            _c = _component

            async def _make_inspect_handler(
                call: ServiceCall, c: str = _c
            ) -> None:
                await _handle_inspect_reset_service(call.hass, call, c)

            hass.services.async_register(
                DOMAIN,
                svc,
                _make_inspect_handler,
                schema=_RESET_SCHEMA,
            )

    if not hass.services.has_service(DOMAIN, "reset_robot_profile"):
        hass.services.async_register(
            DOMAIN,
            "reset_robot_profile",
            async_handle_reset_robot_profile,
            schema=_RESET_SCHEMA,
        )

    # ── F10d — clean_sequence ─────────────────────────────────────────────────
    if not hass.services.has_service(DOMAIN, SERVICE_CLEAN_SEQUENCE):
        hass.services.async_register(
            DOMAIN,
            SERVICE_CLEAN_SEQUENCE,
            async_handle_clean_sequence,
            schema=_CLEAN_SEQUENCE_SCHEMA,
        )
        _LOGGER.debug("Registered %s.%s action", DOMAIN, SERVICE_CLEAN_SEQUENCE)

    # ── v3.2.0 ANOMALY-EXPLAIN — explain_mission ───────────────────────────────
    if not hass.services.has_service(DOMAIN, SERVICE_EXPLAIN_MISSION):
        hass.services.async_register(
            DOMAIN,
            SERVICE_EXPLAIN_MISSION,
            async_handle_explain_mission,
            schema=vol.Schema({
                vol.Required("entity_id"): cv.entity_id,
                vol.Optional("mission_id"): cv.string,
            }),
            supports_response=SupportsResponse.ONLY,
        )
        _LOGGER.debug("Registered %s.%s action", DOMAIN, SERVICE_EXPLAIN_MISSION)

    # ── v3.5.0 FULL-BACKUP — create_backup / restore_backup ───────────────────
    if not hass.services.has_service(DOMAIN, SERVICE_CREATE_BACKUP):
        hass.services.async_register(
            DOMAIN,
            SERVICE_CREATE_BACKUP,
            async_handle_create_backup,
            schema=vol.Schema({vol.Required("entity_id"): cv.entity_id}),
            supports_response=SupportsResponse.ONLY,
        )
        _LOGGER.debug("Registered %s.%s action", DOMAIN, SERVICE_CREATE_BACKUP)

    if not hass.services.has_service(DOMAIN, SERVICE_RESTORE_BACKUP):
        hass.services.async_register(
            DOMAIN,
            SERVICE_RESTORE_BACKUP,
            async_handle_restore_backup,
            schema=vol.Schema({
                vol.Required("entity_id"): cv.entity_id,
                vol.Required("path"): cv.string,
            }),
            supports_response=SupportsResponse.ONLY,
        )
        _LOGGER.debug("Registered %s.%s action", DOMAIN, SERVICE_RESTORE_BACKUP)

    # ── ADVANCE-ROOM-V2 (v2.8.0) — manual room-progress override ─────────────
    if not hass.services.has_service(DOMAIN, "advance_room"):
        hass.services.async_register(
            DOMAIN,
            "advance_room",
            async_handle_advance_room,
            schema=vol.Schema({vol.Required("entity_id"): cv.entity_ids}),
        )
        _LOGGER.debug("Registered %s.advance_room action", DOMAIN)

    if not hass.services.has_service(DOMAIN, "run_favorite"):
        hass.services.async_register(
            DOMAIN,
            "run_favorite",
            async_handle_run_favorite,
            schema=vol.Schema({
                vol.Required("entity_id"): cv.entity_ids,
                vol.Required("favorite_id"): cv.string,
            }),
        )
        _LOGGER.debug("Registered %s.run_favorite action", DOMAIN)


async def async_handle_run_favorite(call: ServiceCall) -> None:
    """Runs a saved favorite by ID. V4/Prime only.

    BY ID rather than by name. The name is what the user typed in the
    iRobot app and can change there at any time; an automation keyed on
    it breaks silently when it does. The IDs are published in the vacuum
    entity's `favorites` attribute for exactly this reason.
    """
    hass = call.hass
    ent_reg = er.async_get(hass)
    favorite_id = call.data["favorite_id"]

    for entity_id in call.data["entity_id"]:
        entry = ent_reg.async_get(entity_id)
        if entry is None or entry.config_entry_id is None:
            continue
        config_entry = hass.config_entries.async_get_entry(entry.config_entry_id)
        if config_entry is None:
            continue
        if config_entry.runtime_data.connection_type is not ConnectionType.CLOUD_ONLY:
            raise ServiceValidationError(
                "run_favorite is only available for V4/Prime robots",
                translation_domain=DOMAIN,
                translation_key="favorite_prime_only",
            )

        from .button_prime import async_run_favorite  # noqa: PLC0415

        if not await async_run_favorite(config_entry, favorite_id):
            # Deleted since the attribute was read, or carrying no
            # commands. Raised rather than logged: a favourite that
            # silently does nothing is the failure this whole feature
            # was shaped to avoid.
            raise ServiceValidationError(
                f"No runnable favorite with id {favorite_id}",
                translation_domain=DOMAIN,
                translation_key="favorite_not_found",
                translation_placeholders={"favorite_id": str(favorite_id)},
            )


async def async_handle_advance_room(call: ServiceCall) -> None:
    """Handle roomba_plus.advance_room — manual room-progress override.

    ADVANCE-ROOM-V2 (v2.8.0) — Lewis firmware robots send a non-run phase
    event at every inter-room boundary. Occasionally the progress sensor gets
    stuck on a completed room. This service lets the user manually advance
    current_room_idx by one step.

    Guards:
      1. MissionTimerStore must exist (SMART + cloud robots only).
      2. An active mission must be in progress (mission_id not None).
      3. Robot must NOT be in phase=run (only advance during transitions).
      4. current_room_idx must be < len(planned_rooms) - 1.
    """
    hass = call.hass
    ent_reg = er.async_get(hass)

    for entity_id in call.data["entity_id"]:
        entry = ent_reg.async_get(entity_id)
        if entry is None:
            raise ServiceValidationError(
                f"Entity {entity_id} not found",
                translation_domain=DOMAIN,
                translation_key="entity_not_found",
                translation_placeholders={"entity_id": entity_id},
            )

        config_entry: RoombaConfigEntry | None = hass.config_entries.async_get_entry(
            entry.config_entry_id
        )
        if config_entry is None:
            raise ServiceValidationError(
                f"No config entry for {entity_id}",
                translation_domain=DOMAIN,
                translation_key="config_entry_not_found",
                translation_placeholders={"entity_id": entity_id},
            )

        data: RoombaData = config_entry.runtime_data
        mts = data.mission_timer_store

        # Guard 1: MissionTimerStore only exists for SMART + cloud robots
        if mts is None:
            raise ServiceValidationError(
                f"{entity_id}: advance_room requires a SMART map robot with "
                "cloud credentials (i7/s9/j-series + iRobot account).",
                translation_domain=DOMAIN,
                translation_key="not_smart_map",
            )

        # Guard 2: active mission
        if mts.mission_id is None:
            _LOGGER.debug(
                "advance_room: no active mission for %s — ignored", entity_id
            )
            continue

        # Guard 3: non-run phase (don't advance while actively cleaning)
        state = data.roomba_reported_state()
        phase = (state.get("cleanMissionStatus") or {}).get("phase", "")
        if phase == "run":
            _LOGGER.debug(
                "advance_room: robot in phase=run for %s — ignored (advance "
                "during transition phase only)",
                entity_id,
            )
            continue

        # Guard 4 + actual advance (returns False if already at last room)
        advanced = mts.advance_room(hass, config_entry.entry_id)
        if advanced:
            _LOGGER.info(
                "advance_room: advanced to room %d/%d (%s) for %s",
                mts.current_room_idx + 1,
                len(mts.planned_rooms),
                mts.current_room,
                entity_id,
            )
        else:
            _LOGGER.debug(
                "advance_room: already at last room for %s — ignored", entity_id
            )


# ── FULL-BACKUP (v3.5.0) — create_backup / restore_backup ────────────────────


def _resolve_config_entry_from_entity(
    hass: HomeAssistant, entity_id: str, service_name: str
) -> Any:
    """Resolve a config entry from an entity_id, raising ServiceValidationError
    with a clear, translatable message on any failure along the way."""
    ent_reg = er.async_get(hass)
    entry_reg = ent_reg.async_get(entity_id)
    if entry_reg is None or entry_reg.config_entry_id is None:
        raise ServiceValidationError(
            f"{service_name}: entity not found or not a Roomba+ entity: {entity_id}",
            translation_domain=DOMAIN,
            translation_key="backup_entity_not_found",
            translation_placeholders={"entity_id": entity_id},
        )
    config_entry = hass.config_entries.async_get_entry(entry_reg.config_entry_id)
    if config_entry is None:
        raise ServiceValidationError(
            f"{service_name}: config entry not found for {entity_id}",
            translation_domain=DOMAIN,
            translation_key="backup_entity_not_found",
            translation_placeholders={"entity_id": entity_id},
        )
    return config_entry


def _write_backup_zip(
    backup_dir: str, filename: str, manifest: dict, payloads: dict[str, dict]
) -> str:
    """Blocking: write the manifest + one JSON per store into a ZIP.

    Runs in the executor — file I/O and zipfile compression are both
    blocking calls and must never touch the event loop directly.
    """
    Path(backup_dir).mkdir(parents=True, exist_ok=True)
    zip_path = str(Path(backup_dir) / filename)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("manifest.json", json.dumps(manifest, indent=2))
        for prefix, data in payloads.items():
            zf.writestr(f"{prefix}.json", json.dumps(data, indent=2))
    return zip_path


def _read_backup_zip(zip_path: str) -> tuple[dict, dict[str, dict]]:
    """Blocking: read manifest + all store payloads back out of a ZIP."""
    if not Path(zip_path).is_file():
        raise HomeAssistantError(f"Backup file not found: {zip_path}")
    payloads: dict[str, dict] = {}
    manifest: dict = {}
    try:
        with zipfile.ZipFile(zip_path, "r") as zf:
            names = set(zf.namelist())
            if "manifest.json" not in names:
                raise HomeAssistantError(
                    f"Not a valid Roomba+ backup (missing manifest.json): {zip_path}"
                )
            manifest = json.loads(zf.read("manifest.json"))
            for _attr, prefix in _BACKUP_STORES:
                member = f"{prefix}.json"
                if member in names:
                    payloads[prefix] = json.loads(zf.read(member))
    except zipfile.BadZipFile as exc:
        raise HomeAssistantError(
            f"Backup file is corrupt or not a ZIP: {zip_path}"
        ) from exc
    return manifest, payloads


async def async_handle_create_backup(
    hass: HomeAssistant, call: ServiceCall
) -> dict[str, Any]:
    """Handle roomba_plus.create_backup.

    Concrete use case: migrating Home Assistant to new hardware without
    losing learned state (GridStore coverage history, RoomSegStore room
    identities, RobotProfileStore L-series learning, ...). Writes one ZIP
    per call containing every persisted Store for the target robot.

    v3.5.0 FULL-BACKUP. Unlike the read-only GET /backup REST view (v2.4,
    F15 — JSON only, deliberately excludes maintenance data since that
    endpoint's use case was cross-robot data export), this service's use
    case is explicitly the *same* physical robot on a new HA install — so
    maintenance timestamps (filter/brush/pad reset times) legitimately
    belong to this robot and are included here.
    """
    entity_id: str = call.data["entity_id"]
    config_entry = _resolve_config_entry_from_entity(hass, entity_id, "create_backup")
    data = config_entry.runtime_data
    entry_id = config_entry.entry_id

    payloads: dict[str, dict] = {}
    included: list[str] = []
    excluded: list[str] = []
    for attr, prefix in _BACKUP_STORES:
        store = Store(hass, _BACKUP_STORE_VERSION, f"{prefix}_{entry_id}")
        raw = await store.async_load()
        if raw is None:
            excluded.append(attr)
            continue
        payloads[prefix] = raw
        included.append(attr)

    manifest = {
        "version": 1,
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "robot": {
            "blid": getattr(data, "blid", None),
            "entry_id": entry_id,
            "map_capability": (
                data.map_capability.value
                if getattr(data, "map_capability", None) is not None
                else None
            ),
        },
        "included_stores": included,
        "excluded_stores_no_data": excluded,
    }

    backup_dir = hass.config.path("roomba_plus_backups")
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"roomba_plus_backup_{entry_id}_{ts}.zip"

    zip_path = await hass.async_add_executor_job(
        _write_backup_zip, backup_dir, filename, manifest, payloads
    )
    _LOGGER.info(
        "create_backup: wrote %s (%d stores included, %d had no data)",
        zip_path, len(included), len(excluded),
    )
    return {
        "path": zip_path,
        "included_stores": included,
        "excluded_stores_no_data": excluded,
    }


async def async_handle_restore_backup(
    hass: HomeAssistant, call: ServiceCall
) -> dict[str, Any]:
    """Handle roomba_plus.restore_backup.

    Writes each store's payload back to its HA Store file, then reloads
    every live store instance already held on config_entry.runtime_data so
    the running integration picks up the restored state immediately — no
    Home Assistant restart required.
    """
    entity_id: str = call.data["entity_id"]
    path: str = call.data["path"]
    config_entry = _resolve_config_entry_from_entity(hass, entity_id, "restore_backup")
    data = config_entry.runtime_data
    entry_id = config_entry.entry_id

    manifest, payloads = await hass.async_add_executor_job(_read_backup_zip, path)

    restored: list[str] = []
    for attr, prefix in _BACKUP_STORES:
        if prefix not in payloads:
            continue
        store = Store(hass, _BACKUP_STORE_VERSION, f"{prefix}_{entry_id}")
        await store.async_save(payloads[prefix])
        live_store = getattr(data, attr, None)
        if live_store is not None:
            await live_store.async_load(hass, entry_id)
        restored.append(attr)

    _LOGGER.info(
        "restore_backup: restored %d/%d stores from %s (exported_at=%s)",
        len(restored), len(_BACKUP_STORES), path,
        manifest.get("exported_at", "unknown"),
    )
    return {
        "restored_stores": restored,
        "manifest": manifest,
    }


def async_remove_services(hass: HomeAssistant) -> None:
    """Remove all Roomba+ domain services (called when last entry unloads)."""
    for svc in (
        "run_favorite",
        SERVICE_CLEAN_ROOM,
        SERVICE_SMART_START,
        SERVICE_CLEAN_OVERDUE_ROOMS,
        SERVICE_AUTO_CLEAN_DIRTY_ROOMS,
        SERVICE_CLEAN_SEQUENCE,
        SERVICE_RESET_FILTER,
        SERVICE_RESET_BRUSH,
        SERVICE_RESET_BATTERY,
        SERVICE_RESET_PAD,
        "reset_wheel_cleaning",
        "reset_contact_cleaning",
        "reset_bin_cleaning",
        "reset_robot_profile",
        "advance_room",
        SERVICE_EXPLAIN_MISSION,
        SERVICE_CREATE_BACKUP,
        SERVICE_RESTORE_BACKUP,
    ):
        if hass.services.has_service(DOMAIN, svc):
            hass.services.async_remove(DOMAIN, svc)
